aws/language-servers

server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.test.ts
server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.ts
server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/dependencyGraph.ts
server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/dependencyGraphFactory.ts
server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.ts
server/aws-lsp-codewhisperer/src/language-server/securityScan/types.ts

Previously reviewed PR - https://github.com/aws/language-servers/pull/152
Dependency graph integration was missing in RunSecurityScan function.
- Integrated dependency graph to create resource zip. 
- Updated ScanHandler class methods to logs necessary info and handle exceptions. (logging has been matched with [vscode package ](https://github.com/aws/aws-toolkit-vscode-staging))
- Added execute handler method and connected runSecurityScan with execulteCommand.
- Updated tests
- Verified end-to-end flow
*logged response* for reference -
```
Info: [2024-03-07T01:18:49.198Z] Starting security scan...
Info: [2024-03-07T01:18:50.253Z] Complete project context processing.
Info: [2024-03-07T01:18:50.254Z] Prepare for uploading src context...
Info: [2024-03-07T01:18:50.559Z] Request id: …
```

Integrate Dependency graph with RunSecurityScan function

---

app/aws-lsp-codewhisperer-binary/src/index.ts
server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts

Creating separate server for transform feature which will be part of CWSPRS .

Adding server for transform feature

---

server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts

1.  update security scan parameters to be uppercase aligned with toolkit
2. always register hover handler to avoid seeing onHover not implemented error from client
3. reset the diagnostics before each run

fix several security scan issues

---

server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts

Adjust CodeScan server `executeCommand` to new interface, which supports commands routing.

Adjust CodeScan execute command to new interface

---

chat-client/package.json
package-lock.json

Use the latest types package in the chat client

Consume latest available types package

---

client/vscode/src/inlineCompletionActivation.ts
server/aws-lsp-codewhisperer/src/client/sigv4/service.json
server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
server/aws-lsp-codewhisperer/src/language-server/languageDetection.ts

Updating the JSON model to update supported languages 

Update supported programming languages  for GenerateRecommendations API

---

client/vscode/src/activation.ts
client/vscode/src/inlineCompletionActivation.ts
server/aws-lsp-codewhisperer/src/language-server/languageDetection.ts

Extend list of supported languages with java. Tested locally

Add java to list of supported languages

---

package-lock.json
script/clean.ts
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/index.ts

Releasing new version of server

Upgrade version to 0.0.5

---

chat-client/src/client/mynahUi.ts
client/vscode/package.json
client/vscode/src/chatActivation.ts

Implemented context menu command handling 
https://github.com/aws/language-servers/assets/28572423/62c66c55-42d3-4617-a218-bb52e1988383

Handle context menu commands on the client

---

chat-client/src/client/chat.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.ts
chat-client/src/contracts/serverContracts.ts
client/vscode/package.json
client/vscode/src/chatActivation.ts
package-lock.json
server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts

We want to implement some of the chat events on the chat-client
- Add needed event commands and params
- Implement event communication flow from mynah-ui to client
- Implement event logic
- Add handler in vscode client for testing
Note: unit tests in follow up PR

Implement various chat events

---

app/aws-lsp-json-binary/package.json
app/aws-lsp-json-binary/src/index.ts
app/aws-lsp-yaml-binary/package.json
app/aws-lsp-yaml-binary/src/index.ts
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-json-webworker/src/jsonWebWorkerRuntimeServer.ts
app/aws-lsp-yaml-json-webworker/src/yamlWebWorkerRuntimeServer.ts
core/aws-lsp-core/CHANGELOG.md
core/aws-lsp-core/package.json
package-lock.json
server/aws-lsp-buildspec/package.json
server/aws-lsp-buildspec/src/language-server/buildSpecServer.ts
server/aws-lsp-buildspec/src/language-server/jsonSchemaServer.ts
server/aws-lsp-buildspec/src/language-server/yamlSchemaServer.ts
server/aws-lsp-cloudformation/package.json
server/aws-lsp-cloudformation/src/language-server/cloudFormationService.ts
server/aws-lsp-json/package.json
server/aws-lsp-yaml/package.json

- Renamed `@aws/aws-lsp-json` and `@aws/aws-lsp-yaml` to `@aws/lsp-json` and `@aws/lsp-yaml`.
- Added missing `repository`, `author`, `license` and `engines` fields to `package.json` files
- Set proper descriptions

Added meta information to package.json files and renamed packages

---

app/aws-lsp-codewhisperer-binary/package.json
app/aws-lsp-codewhisperer-binary/webpack.config.js

Include Q chat server in the bundle and the necessary artifacts: two wasm files and the worker file. This has been tested in VS.

Update webpack build for chat server

---

chat-client/src/client/chat.test.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/contracts/serverContracts.ts
chat-client/src/contracts/telemetry.ts
client/vscode/package.json
client/vscode/src/chatActivation.ts
server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts

This PR defines telemetry types and implements the telemetry events

Define telemetry events

---

chat-client/src/client/messager.ts
chat-client/src/contracts/telemetry.ts
client/vscode/src/chatActivation.ts

Add telemetry for insert to cursor position and tidy up the sample extension 

Add telemetry to insertToCursor and update sample extension

---

app/aws-lsp-yaml-binary/src/tests/yamlServerCFInteg.test.ts
package-lock.json
server/aws-lsp-yaml/package.json
server/aws-lsp-yaml/patchYamlPackage.js
server/aws-lsp-yaml/src/language-service/yamlLanguageService.ts

patch script didn't work for windows
script is fixed, the fix is tested on windows laptop

Fixed patching scriptfor windows

---

server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts

Updates tool name displayed with Security scan findings to Amazon Q.

Update security scan tool name to Amazon Q

---

server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts

Specify custom user agent for streaming client

Specify custom user agent for streaming client

---

chat-client/package.json
chat-client/src/client/mynahUi.ts
package-lock.json

- Bumped mynah to latest version which fixes a few bugs:
- Followup button showing up as text
- Inline code suggestions having cut out borders 
- Text input scrolling issues 
- This PR also adds logic so that Authentication buttons are shown on the right side of the UI 

Update mynah & handle auth follow up button

---

chat-client/package.json
package-lock.json

Update package.json to fix internal issue

Update package.json to fix internal issue

---

server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.test.ts
server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
server/aws-lsp-codewhisperer/src/language-server/telemetry/types.ts

Add credentialStartUrl to chat metrics

Add credentialStartUrl to chat metrics

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Release new version of aws-lsp-codewhisperer

Increment aws-lsp-codewhisperer version to 0.0.7

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Increment aws-lsp-codewhisperer version to 0.0.8

---

.husky/pre-commit
package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Bumping @aws/lsp-codewhisperer version to 0.0.10.
- **Feature**: Add Q .NET Transform Server
- Add default response for "How can Amazon Q help me?"
- Allow "0" to be used as partial token in chat handler

Releasing @aws/lsp-codewhisperer@0.0.10

---

.husky/pre-commit
package-lock.json
server/aws-lsp-partiql/package.json

Releasing new lsp-partiql server, version 0.0.3

Bump lsp-partiql version to 0.0.3

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Releasing @aws/lsp-codewhisperer@0.0.11

Releasing @aws/lsp-codewhisperer@0.0.11

---

server/aws-lsp-codewhisperer/CHANGELOG.md

Release new version of lsp-codewhisperer server is needed.
Removed unrelated change from changelog.

Removed unrelated change from changelog

---

server/aws-lsp-codewhisperer/src/language-server/auto-trigger/autoTrigger.ts

the length of `\n` should be 1

fix(amazonq): fix LF doesn't trigger

---

server/aws-lsp-codewhisperer/CHANGELOG.md

Added missing entry for the lsp-codewhisperer@0.0.13 release 

Update lsp-codewhisperer's CHANGELOG

---

app/aws-lsp-partiql-runtimes/package.json
package-lock.json
server/aws-lsp-partiql/CHANGELOG.md
server/aws-lsp-partiql/package.json

Releasing lsp-partiql 0.0.4
- Features: add PRIMARY KEY and table options support PartiQL server grammar

Releasing lsp-partiql 0.0.4

---

chat-client/package.json
package-lock.json

bump chat-client to 0.0.3 and update mynah-ui to 4.15.8
Ran tests against the latest chat-client. Also tested the chat-client bundle in VS on Windows. 

bump chat-client to 0.0.3 and update mynah-ui to 4.15.8

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Release new version 0.0.14 of @aws/lsp-codewhisperer package.

Update @aws/lsp-codewhisperer version to 0.0.14

---

app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-json/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

Vulnerability CVE-2024-45296
update lockfile

Update lockfiles to resolve vulnerabilities

---

app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.test.ts
server/aws-lsp-json/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

Runtimes is out of date
Update Runtimes package to latest in all workspaces.

Update runtimes dependency

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts

1. support transform project with multiple target framework
2. fix file list mismatch with requirement.json

add target framework and fix bug in copy file logic

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Release latest changes in @aws/lsp-codewhisperer package to npm
- Amazon Q Configuration: Amazon Q Configuration Server and implement fetching available Q Customizations (#462).
- Amazon Q Inline Code Completions: Supplemental cross-file context for source code for `java`, `python`, `javascript`, `typescript`, `javascriptreact`, `typescriptreact` language ids (#463).
- .Net Transform: Add transform logSuggestionForFailureResponse (#483)
- .Net Transform: Add logging when polling get transformation status failed (#476).
- .Net Transform: Add target framework and fix bug in copy file logic (#477).
- .Net Transform: Specify StartTransformation error message (#468).

Release @aws/lsp-codewhisperer:v0.0.15

---

chat-client/CHANGELOG.md
chat-client/package.json
package-lock.json

Update @aws/chat-client version to 0.0.4 and add Changelog file.

Update @aws/chat-client version to 0.0.4

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts

minor change to move transform result to artifact folder

move tranform result download location

---

chat-client/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json

Update @aws/chat-client-ui-types to 0.0.8

Update @aws/chat-client-ui-types to 0.0.8

---

app/aws-lsp-yaml-json-webworker/package.json
package-lock.json
package.json

We have some vulnerable dependencies used in the lockfile and some compilation errors in local development
- Update `@types/node` for compilation error
- Update lockfile for vulnerabilities

Update vulnerable dependencies and fix compile error

---

CONTRIBUTING.md

Add documentation for activationEvents for codewhisperer server vscode

Add documentation for activationEvents for codewhisperer server vscode

---

server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
server/aws-lsp-codewhisperer/src/language-server/utils.test.ts
server/aws-lsp-codewhisperer/src/language-server/utils.ts

Refactor common function names and pass extra fields to user trigger decision event
Follow-up changes of PR https://github.com/aws/language-servers/pull/555

Refactor common function names and pass extra fields to user trigger decision event

---

chat-client/src/client/chat.ts

Updated the legal disclaimer text in the footer of the chat client. This is done as a clarification of compliant use according to the AWS AI policy.

Changed legal text in prompt UI footer

---

chat-client/CHANGELOG.md
chat-client/package.json
package-lock.json

Release new version of chat client

Release/chat client0.0.7

---

package.json
script/git-clean.sh

Improve clean up script to prevent caching mechanisms to override changes made in the code and lead to misleading results.
Add `git clean -fdx `to cleanup script for a thorough cleanup

improve clean script to prevent issues with caching

---

chat-client/package.json
package-lock.json

reverted mynah-ui version

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts

add solution file path to requirement.json

---

chat-client/package.json
package-lock.json

Update mynah UI version to last applicable one

Update mynah UI version to last applicable one

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/converter.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts

theres a breaking change in the backend api to remove some unused enum, 
backend change has been deployed to production. the change need to be release ASAP.

remove optional parameters

---

app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

Update @aws/language-server-runtimes dependency to 0.2.25

Update @aws/language-server-runtimes to 0.2.25

---

chat-client/CHANGELOG.md
chat-client/package.json
package-lock.json

Update chat-client package version to 0.0.8

Update chat-client package version to 0.0.8

---

package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Releasing aws-lsp-codewhisperer package 0.0.17

Update aws-lsp-codewhisperer package version to 0.0.17

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/resources/SupportedProjects.ts

Updated supported types so these types are supported by default and wouldn't pop up dialog in Toolkit

Updated supported types

---

server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts

There is new status from background to include step status SKIPPED
Added status

Adding status skipped in step and substep of transformation

---

chat-client/CHANGELOG.md
chat-client/package.json
package-lock.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json

Release request to bump versions of:
* @aws/chat-client to 0.0.9
* @aws/lsp-codewhisperer to 0.0.18

Release @aws/chat-client:0.0.9 and aws/lsp-codewhisperer:0.0.18

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/validation.ts

Adding logs when invalid project is detected in transformation

Adding logs for invalid projects

---

.github/workflows/new_pr.yml

Added a notification in Slack whenever a PR is created.

Added Slack notifier on PR creation

---

chat-client/src/client/chat.ts

Updating legal text in the chat-client footer

Update legal footer text

---

server/aws-lsp-codewhisperer/src/language-server/utilities/supplementalContextUtil/supplementalContextUtil.test.ts

Followup to https://github.com/aws/language-servers/pull/634

Update log stub in supplementalContextUtil.test

---

.github/dependabot.yml

Update Dependabot configuration based on latest state.

codewhisperer-streaming client was moved - update Dependabot config accordingly

---

CONTRIBUTING.md
client/vscode/src/activation.ts

Debugging in the VSCode client is currently broken
Pass the args for debugging correctly and update the README instructions on how to debug in the VSCode client as well as independently. Tested by launching the client in local

Improve and add debugging instructions

---

.github/workflows/publish-lsp-antlr4.yaml

Adding new workflow for publishing the new antlr4 language server to npm

chore: create npm publishing workflow for antlr4 server

---

chat-client/package.json
package-lock.json

chore(chat-client): updated types version

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

Update  language-server-runtimes dependency version
`npm update @aws/language-server-runtimes --workspaces --save
`

chore: bump language-server-runtimes dependency version

---

.vscode/launch.json
CONTRIBUTING.md

Current debugging instructions (with breakpoints) are not complete/precise. In this PR, we specify step by step how to debug with breakpoints.
We also fix the task value set for the preLaunchTask option for the different configurations.

chore: improve vSCode client debug instructions and launch.json config

---

server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts

Prevent override of client request listeners in CodeWhispererServiceIAM in case any listener was setup before. 

fix: prevent override of client request listeners in CodeWhispererServiceIAM

---

chat-client/README.md

This commit is for triggering release please for chat-client package

feat: update mynah-ui to v4.22.1

---

app/aws-lsp-antlr4-runtimes/webpack.config.js
app/aws-lsp-json-runtimes/webpack.config.js
app/aws-lsp-partiql-runtimes/webpack.config.js
app/aws-lsp-yaml-runtimes/webpack.config.js
app/hello-world-lsp-runtimes/webpack.config.js
package-lock.json
package.json

Similar to codewhisperer server, but for all package https://github.com/aws/language-servers/pull/804
Update all related build configurations.

build: fix all standalone builds

---

server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts

For `ListAvailableProfiles` we need to update service definition and bearer token client
Service definitions were updated.
Client was re-generated and updated.

chore: update service definition and types for bearer token client

---

chat-client/README.md
chat-client/package.json
chat-client/src/client/chat.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json

feat(chat-client): openTab returns error for tab create if tabs limit hit

---

chat-client/package.json
package-lock.json

We need to upgrade mynah-ui dependency in chat-client

fix: bump mynah-ui version

---

app/aws-lsp-antlr4-runtimes/package.json
package-lock.json
server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/telemetry/userTriggerDecision.test.ts
server/aws-lsp-codewhisperer/src/language-server/testUtils.ts

flare currently doesn't support pagination for inline suggestions
add pagination support
this depends on interface change in https://github.com/aws/language-server-runtimes/pull/364

feat(amazonq): support pagination for inline suggestions

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
chat-client/src/client/mynahUi.ts
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

Protocol is upgraded in Language Server Runtimes
Bump version 

chore: language server runtimes version bump

---

app/aws-lsp-codewhisperer-runtimes/src/agent-standalone.ts
server/aws-lsp-codewhisperer/src/index.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/README.md
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts

Starting point for implementing agentic chat, separate from the existing chat for now.

feat: create copy of chat server and controller to use in agentic chat

---

chat-client/src/client/chat.test.ts
chat-client/src/client/chat.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/contracts/serverContracts.ts
chat-client/src/contracts/telemetry.ts

Handle file click events in chat client to support file click for context transparency.

feat: handle fileClick events

---

server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts

Quick actions currently don't have any icons
Adding the icons to the Quick Actions

feat: added icons to help and clear action

---

CONTRIBUTING.md

Update CONTRIBUTION.md to add troubleshooting info for Q Chat window not opening automatically in VS Code sample extension.

docs: troubleshooting Q Chat window not visible

---

CONTRIBUTING.md

add bundlng information in contibuting.md

chore: update contributing with bundling information

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: bump runtimes version

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: bump the runtimes version to 0.2.63

---

app/aws-lsp-codewhisperer-runtimes/src/agent-standalone.ts

ExecuteBash is missing
Enable executeBash

feat: enable execute bash tool

---

chat-client/package.json
package-lock.json

chore(amazonq): update mynah ui

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts

Followup to https://github.com/aws/language-servers/pull/1008
- same solution as previous PR. 

fix: update spec to require absolute path

---

.gitignore
chat-client/package.json
package-lock.json

fix(amazonq): include mynah ui beta 6

---

app/aws-lsp-codewhisperer-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts

Updating runtime to enable the `onPromptInputOptionChange` method (see #1013)

chore: update runtimes version

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

fix: up the agent loop limit

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: update runtimes package version across the board

---

chat-client/package.json
chat-client/src/client/chat.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/client/tabs/tabFactory.ts
package-lock.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

agentic chat has stop response disabled
enable it and make it so that when its clicked it returns back an empty answer, which completes the request stream and unlocks the UI

feat: implement stop response

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: bump runtimes

---

chat-client/src/client/mynahUi.ts
chat-client/src/client/utils.ts

fix: incorrect props for fsWrite message

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts

View diff is not implemented
Added missing messageId to mynahUi onFileClick handler. We will use the toolUseId as the messageId to do a map lookup, that way we can conditionally open the diff only for fsWrite tool.

feat: support view diff for fsWrite

---

.gitignore
chat-client/package.json
package-lock.json

chore: remove included mynah-ui dependency

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

Undo button is not implemented
Update onButtonClick handler to handle reverting to the oldContent for a toolUseId.
TODO: need to send a message from controller -> ui to update the card to remove the button and update the card status

feat: fsWrite undo button

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts

fix: adding fixHistory logic for agentic Chat

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- using status in header after button click
- keep the command in body of the message

fix: ui polish for execute confirmation

---

package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts

Previous implementation: https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/codewhispererChat/tools/chatStream.ts#L69
https://github.com/user-attachments/assets/59131a76-66a9-4266-a5c9-e89fda79aa5a

feat: stream the execute bash output

---

chat-client/src/client/chat.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

(fix): update placeholder ghost message

---

chat-client/src/client/mynahUi.ts

- fix: remove code block insert-to-cursor in pp mode
before:
after:

fix: remove code block insert-to-cursor in pp mode

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

fix: some chat messages are not added to history

---

chat-client/src/client/mynahUi.ts

Chang stop generating to stop for hover text of stop buttom

fix: String Change

---

chat-client/src/client/mynahUi.ts

- update pp mode in tab store
- The pp mode is per tab and every time the pp mode change needs to update the tab store. Then use the pp mode in tab store for ui display.
- In Tab1, the pp mode = off. Then click add new tab button, the Tab2 was created with pp mode = on, but the code block still showed `insert-to-cursor`.
Tab1:
Tab2:
- In Tab1, the pp mode = off. Then click add new tab button, the Tab2 was created with pp mode = on, but the code block did NOT showed `insert-to-cursor`.
Tab1:
Tab2

fix: update pp mode in tab store

---

chat-client/package.json
package-lock.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

We were using emoji warning icon, which might cause act differently for different users

fix(agentic): fix the warning icon

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

Reject button stopped working for executeBash tool
https://github.com/user-attachments/assets/c89c2b65-d758-4b4a-a332-0a0852aa0bb8
Cache buttonId and use it when rejection is handled in catch block of toolUse handler.
https://github.com/user-attachments/assets/26b89011-ee0b-49bb-8f44-799c26276089

fix: reject button for executeBash tool

---

server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts

The codewhisperer server fails to load the project context indexer on windows, raising a `ERR_UNSUPPORTED_ESM_URL_SCHEME ` failure. This happens when the library is imported with a regular path on Windows:
https://github.com/aws/language-servers/blob/e4d4ef026c8a60cc1ddf08c981340a902d628016/server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts#L142-L143
Some information from https://github.com/nodejs/node/issues/31710 indicates that code running on Windows must use URLs so that local file paths (including drive letters) are not mistakenly interpreted as things like http urls.
Wrap the path in a URL when running on Windows.

fix(amazonq): avoid ERR_UNSUPPORTED_ESM_URL_SCHEME error when loading indexer on Windows

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts

- Our tool execution flow is not optimal
- Update toolSpec for fsRead, fsWrite and listDirectory

fix: update toolSpec for fsRead, fsWrite and listDirectory

---

chat-client/src/client/texts/pairProgramming.ts

- Existing mynah version has some styling issue which will be fixed in this PR: https://github.com/aws/mynah-ui/pull/312
- To have a quick fix, we change the type from `checkbox` to `switch`

fix: change pair programming  icon.

---

chat-client/src/client/chat.test.ts
chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- thinking doesn't always appear
- stop button disappear sometimes
- upstream the loading message into mynah-ui, so it will always show thinking and stop button in the entire duration

fix: thinking does not always appear

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts

Product asked for another execute base specific stop button during command execution
Add stop button to execute bash window

feat: add stop button for execute bash

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts

- we are not updating the context commands on file add/delete
- add that functionality

fix: update context commands on file add/delete

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

header not updated on execute bash completion
Updated to "Completed" like other tools

fix: update header on execute bash completion

---

chat-client/src/client/mynahUi.ts
chat-client/src/client/texts/pairProgramming.ts
chat-client/src/client/utils.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts

> When the “Files Read" UX object is opened, and it adds a new file read, it then closes.  Super annoying.
https://github.com/user-attachments/assets/97ca9f7e-de45-4571-8942-e4891da5d7a2

fix: Fixes the issue of collapsing the files and folders while streaming response.

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts

1. Execute bash headers flickers during command execution
2. Shell header incorrectly added to other messages
Fixed both

fix: fix execute command header issues

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

getInstance doesn't take any arguments
remove them

fix: ci failing due to invalid argument

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

Execute bash tool status and buttons not properly handled on re-prompt
* Added ignored status for execute bash tool     
We 5 scenarios here for re-prompt, Status Ignored will only be showed for 2 and 3, rest will retain its original status. and for all cases, all buttons will be removed. 
1. After customer rejected the command (UI Shows status Rejected)
2. While waiting for customer approval (UI Shows buttons Run and Reject )
3. Command is running (UI Shows button Stop)
4. Command stopped (UI shows Status Stopped)
5. Command completed (UI shows status Completed)
* Fix small header issue and remove the green check while command is running 

fix: new ignored status for execute bash tool

---

.vscode/launch.json
client/vscode/src/inlineCompletionActivation.ts

Implements automated triggers for special characters and Enter key to improve the user experience with inline completions and edit suggestions.

feat: add automated triggers for special characters and enter key

---

chat-client/src/client/texts/pairProgramming.ts

Reduce size of Pair Programmer header
Before
After

fix: decrease header size for Pair Programmer

---

chat-client/src/client/texts/pairProgramming.ts

- Updating strings for agentic coding experience

fix: updating strings for agentic coding experience

---

chat-client/src/client/texts/pairProgramming.ts

fix: string changes

---

chat-client/package.json
package-lock.json

Release notes: https://github.com/aws/mynah-ui/releases/tag/v4.34.0

chore: bump mynah-ui version

---

.github/workflows/lsp-ci.yaml
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/scripts/test-bundles.js

Adding another step in the Github workflow to test the packaged bundle, to catch up issues where server crashes on starting. This will help in catching such issues earlier. 

chore: add a step in the github workflow to test the packaged bundle

---

server/aws-lsp-codewhisperer/src/language-server/workspaceContext/client.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyDiscoverer.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JSTSDependencyHandler.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JavaDependencyHandler.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/LanguageDependencyHandler.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/PythonDependencyHandler.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts

1. server side workspace context didn't snapshot workspace while remote environment is expired.
2. Remove workspace folder didn't remove and dispose resource correctly
3. didChangeWorkspaceFolder and didChangeDependencyPaths messages sometimes are lost.

fix: improve data synchronization of server side workspace context

---

chat-client/src/client/mynahUi.ts

The Undo buttom not dimmed the card
https://github.com/user-attachments/assets/ac11ed8a-5c1d-4450-82e7-74035bae77ae
https://github.com/user-attachments/assets/9bf43906-d23e-4274-a555-da32047713b6

fix: undo buttom not dimmed the card

---

client/vscode/src/inlineCompletionActivation.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.test.ts
server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
server/aws-lsp-codewhisperer/src/shared/languageDetection.ts
server/aws-lsp-codewhisperer/src/shared/testUtils.ts

merge in changes from feature branch:  https://github.com/aws/language-servers/tree/feature/qflare 
This includes:
- pagination
- language support
- imports
all of these are backward compatible
Most changes have been previously reviewed

feat: merge updates for inline completions

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts

support MCP init timeut
support MCP init timeut

feat: support MCP init timeout

---

chat-client/src/client/mynahUi.ts

When user click stop button, it shows stop instead of stopped.

fix: Stop buttom work unexpected

---

CONTRIBUTING.md
server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts

chore: refactor common customization logic with metadata to a common function and update corresponding CONTRIBUTING.md guide regarding it's usage.

chore: refactor common customization logic to a function and update corresponding contributing guide

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

As product spec defines, we need to truncate the userInputMessage to 500k instead of throwing an exception.
Truncate the userInputMessage to 500k

fix: truncate userInputMessage to 500k

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

- response contain prev suggestions
- only return suggestions from current response

fix: duplicate suggestion in inline response

---

server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts

Need to emit telemetry metrics for NEP
adding new fields for NEP telemetry event

feat: adding new fields for NEP telemetry event

---

server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts

fix: make new fields in UserModificationEvent optional

fix: make new fields in userModificationEvent optional

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
chat-client/src/client/chat.ts
chat-client/src/client/messager.ts
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/client/tabs/tabFactory.ts
chat-client/src/contracts/serverContracts.ts
client/vscode/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

MCP servers need some UI changes to display the active servers.
- Added MCP button as entrypoint to the list.
- Used the history list path to add additional case to display MCP servers.
- updated mynah UI and runtimes versions.
https://github.com/user-attachments/assets/35055db6-908e-4ebe-a910-fbe87ad0cecb

feat: initial MCP servers List UI changes

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

In https://github.com/aws/language-servers/pull/1351, we also render explanatory of tools as soon as it is available in streaming for other commands, which resulted in a less than ideal UX. 
Only do the in time rendering for fsWrite

fix: only do render on partial results for fsWrite

---

server/aws-lsp-codewhisperer/src/shared/utils.test.ts
server/aws-lsp-codewhisperer/src/shared/utils.ts

- error status code in Kibana is 0 or has wrong value
- re-categorize error status code

fix: re-categorize error status code

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts

feat: add refresh mcp server functionality

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

- refresh button has no functionality 
- refresh button functionality
- error handling. currently on error, just log and still display servers to user
https://github.com/user-attachments/assets/268dada5-6697-4d2b-a560-fdf7fdbd6f83

fix: refresh button

---

chat-client/src/client/texts/disclaimer.ts

This change updates the genAI disclaimer text based on our latest guidance.

chore: update genai disclaimer text

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts

- We are slow and inefficient when resolving tasks
- Add grepSearch implementation
- This will not enable the tool

fix: add grepSearch implementation

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

Disable and Delete buttons are not working
- Setting up disable and delete UX changes.
https://github.com/user-attachments/assets/be46f07f-2974-4d9a-a70f-78889394d2f5

feat: adding disable and delete mcp server functions

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

- Missing `Arguments` and `Environment variables` in add config mcp.
- Added cancel functionality and missing fields to add config mcp.
https://github.com/user-attachments/assets/64e1dddc-e52d-4014-b0e7-92509b45359e

feat: adding optional values field to add mcp configuration ux

---

chat-client/src/client/mynahUi.ts

Reverting the code change relating the bug we found on bug bash

fix: Revert stop text align

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- Accidental formatting from previous PR: https://github.com/aws/language-servers/pull/1359#discussion_r2100533366
- Revert the accidental changes.

fix: formatting

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts

support MCP paths for Windows; 
path join needs to be compatible with Windows paths

fix: support MCP paths for Windows

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts

UT was removed previously
Multiple small fixes and add back UTs.

fix: multiple fixes for MCP + add back UTs

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts

fix: check if mcp.json exits when mutating mcp json

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- Adding permissions ux to the mcp ux to chat item summary card.
- Refactoring `mynahUi.ts` and `agenticChatController.ts`
https://github.com/user-attachments/assets/ef799fd0-2ffe-4800-a6ce-818c52260037

feat: adding permissions ux to the mcp 

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts

UI needs to update status and show error message on any MCP failure 
Emit MCP_SERVER_STATUS_CHANGED event on all failure.

fix: emit status change event on MCP error

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

We are not validate user's input for mcp server config right now 
https://github.com/user-attachments/assets/322797f8-77f3-4d05-a382-b8f8803939b2

fix: add validation for user's input

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

Need edit configuration UX
Added edit configuration UX

feat: update server UX

---

chat-client/src/client/chat.ts
chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts

- We need to update servers status dynamically and present failed mcp servers with a fix button with error message
- Event based server update
- Fix configuration button that open server config page

feat: dynamic server update and fix configuration button

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts

Build failure with merge conflict for mcp permission types
merge conflict resolution

fix: merge conflict resolution

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- MCP tools are always available regardless of pair programming on vs off
- Disable MCP tools in pair programming off
- Pair Programmer On:  `All Tools`
- Pair Programmer Off: `Read Only Tools = All Tools - Restricted Tools (MCP + Write Tools)`
- MCP tool name spec will go from `serverName_toolName` to `serverName___toolName`. We need to followup here when that change occurs
- Rare edge cases where is is not just simply `serverName + _ + toolName`. For example, when `serverName + toolName > 64 characters`. There will be some follow logic in `mcpUtils.ts` to account for such cases
https://github.com/user-attachments/assets/226aa087-e0b3-4fc8-8bac-e3922f1551d7

fix: disable mcp tools for pair programmer off mode

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

Fix configuration jump to add mcp server view and does not have all the existing value populated
Use edit mcp view instead

fix: use edit mcp view for fix configuration

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

Now users are able to add duplicate server name
https://github.com/user-attachments/assets/20fb671b-e720-4de7-9859-5b719942334d

fix: Throw an error when user try to add a sever when the server name already exsit 

---

chat-client/src/client/mynahUi.ts

- Tool count is disabled and no tooltip on toolCount

fix: Adding tooltip descriptions to tool count and enabling the count

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

- No validation in list of mcp servers
- Added validation.
https://github.com/user-attachments/assets/cb6a6f5e-7d90-47f9-bfc6-4fb08037d1cb
- Edit server name should be disabled and need to provide option to delete the server.

fix: adding validation for list of mcp servers

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

UI for stop button does not go away when commands fail the  `whichCommand()` check for confirming their existence on the user's system.
Update the `executeBash` UI to show `Completed` for non-user related failures. 
##Testing
https://github.com/user-attachments/assets/04a15638-0f95-4c35-98e8-b01442fbd13c

fix: update executeBash UI for failures during command existence check

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

- If there is a validation error for list of mcp servers, IDE shows success status.

fix: showing error status if there is a validation error in list of mcp servers

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts

- This button is not clickable. 
- Tool descriptions are not being shown. In the screenshot to the right, the description for the "fetch" tool should be shown below the tool name.

fix: ux fixes for mcp list

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts

Multiple issues from bug bash
* Fix workspace config file issue
* Fix default timeout issue, allowing 0 for no timeout
* Fix issue 8,9,10 in https://quip-amazon.com/MH5pAJ39RgtS/Q-Agentic-Chat-Mcp-BugBash

fix: fix ws level config and multiple bugs

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts

code removed in https://github.com/aws/language-servers/pull/1473 was accidentally re-added in https://github.com/aws/language-servers/pull/1455. This pr is to move those code

fix: remove unused util

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
client/vscode/package.json
package-lock.json
package.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: bump runtimes version to 0.2.89

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts

Decision was made to temporarily disable grep search

fix: disable grep search

---

chat-client/package.json
package-lock.json

merge from main

---

chat-client/src/client/mynahUi.ts
package-lock.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

fix: fix for merge conflict errors

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts

- Adding a server through UI for windows was broken, so a user would either have to press refresh button or manually add to their mcp.json config to get the server to work
- I am still not sure why it is okay to have an empty key/value in mergedEnv for mac, but not windows. I will need to investigate more into this.
- Make sure there is no empty key/value in mergedEnv

fix: adding mcp server through UI for Windows

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

feat(amazonq): prefetch logging

---

package-lock.json
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

refactor(amazonq): restructure

---

package-lock.json
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

refactor(amazonq): restructure nep codepath

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts

Right now, when user delete the mcp server, the server only get removed from mcp.json but still exist on default.json(persona file)
The root cause is `this.mcpServers.delete(serverName)` get called before we mutate persona file. My solution reorder the operation by following:
1. Getting the reset servers
2. Remove the server from mcp.json
3. Remove the server from persona file. 
4. Clean up the memory
https://github.com/user-attachments/assets/53e3c099-7633-4903-ab8b-a3c1dc92c940

fix: When user remove the server, the server should aslo get removed from persona file

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

- enhance logic to avoid prefetched suggestions returned wrongly
- disable prefetch by default

fix(amazonq): enhance logic to avoid prefetched suggestions returned wrongly

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts

fix: fix for CI tests for mcp manager

---

chat-client/src/client/mcpMynahUi.test.ts

fix: fix for icon check in tests

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts

fix: fix for agentic chat controller test failures

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

fix(amazonq): nep several fixes / improvement

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

chore(amazonq): cleanup nep path

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

chore(amazonq): cleanup nep prefetch code path

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/diffUtils.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/codeEditTracker.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/supplementalContextUtil.ts

refactor(amazonq): remove duplicate trimSupplementalContext

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/codeEditTracker.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/codeEditTracker.ts

refactor(amazonq): remove duplicate diff util

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/codeEditTracker.ts
server/aws-lsp-codewhisperer/src/shared/models/model.ts

chore(amazonq): move nep pojo to model.ts

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

seems there was a miss when resolving merge conflict

fix(amazonq): completion discard case doesnt send telemetry correctly

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/diffUtils.ts
server/aws-lsp-codewhisperer/src/shared/models/model.ts
server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/supplementalContextUtil.ts

feat(amazonq): utils for NEP(next edit prediction)

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
client/vscode/package.json
package-lock.json
package.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: bump runtimes to 0.2.96

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/editPredictionConfig.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/editPredictionConfig.ts

feat(amazonq): next edit prediction configuration and feature flag

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.test.ts

test(amazonq): test coverage for codewhispererService.ts

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

fix: removing logic to skip suggestion at same location

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

fix: remove checking for predictionTypes in codeWhispererServer

---

chat-client/src/client/mynahUi.test.ts
chat-client/src/client/texts/modelSelection.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts

List of models should be updated
- Remove sonnet 3.5 as it is on a deprecation path
- Add sonnet 4
- Make sonnet 4 the default

feat: update list of models and set default to 4

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- MCP summary card is greyed out and shows invalid toolName.
- Fixed the above issue.

fix(agenticChat): UX fixes for MCP

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/EditPredictionAutoTriggerTestConstants.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/editPredictionAutoTrigger.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/editPredictionAutoTrigger.ts

feat(amazonq): edit predition auto trigger

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/languageDetector.ts

chore(amazonq): reformat nep languageDetector.ts

---

.release-please-manifest.json
chat-client/CHANGELOG.md
chat-client/package.json
package-lock.json
server/aws-lsp-antlr4/CHANGELOG.md
server/aws-lsp-antlr4/package.json
server/aws-lsp-codewhisperer/CHANGELOG.md
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
server/aws-lsp-json/CHANGELOG.md
server/aws-lsp-json/package.json
server/aws-lsp-partiql/CHANGELOG.md
server/aws-lsp-partiql/package.json
server/aws-lsp-yaml/CHANGELOG.md
server/aws-lsp-yaml/package.json

chore(amazonq): sync feat branch with main

---

server/aws-lsp-codewhisperer/src/shared/telemetry/telemetry.test.ts

fix: fix telemetry unit test

---

server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts

On backend, we are observing duplicate `ListWorkspaceContext` calls targeting the same workspace are made at the same time in a fixed interval.
Further investigation shows that there are prior `ListFeatureEvaluations` calls before such symptom occurs, which indicates multiple attempts to initialize the workflow are made.
Prevent workspace context server initialization workflow from overlapping, skipping the subsequent executions when the previous ones haven't finished.

fix(amazonq): prevent workspace context server initialization workflow from overlapping

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

This reverts commit bf596bf8f9b9f5ee82ffa990721f4b5dcbe5cc24.

Revert "chore(amazonq): nep cherrypick codewhispererService.ts (#1689)"

---

server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

Revert(amazonq):  bring back #1689

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/diffUtils.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetry.test.ts

chroe(amazonq): cherrypick codewhispererServer.ts

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/rejectedEditTracker.integration.test.ts

test(amazonq): rejectEditTracker integration test

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.nep.test.ts

test(amazonq): codewhispererServer.nep.test

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/languageDetector.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
server/aws-lsp-codewhisperer/src/shared/streamingClientService.test.ts
server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts

chore(amazonq): cleanup feat branch

---

chat-client/src/client/texts/modelSelection.ts

Model Throttling Error message should be more clear
Change error message to `The model you've selected is experiencing high load. Please switch to another model and try again.`

fix: change model unavailable message

---

chat-client/package.json
package-lock.json

chore: bump mynah-ui

---

package-lock.json
server/aws-lsp-identity/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-s3/package.json

chore: manually bump lsp-core version

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts

- MCP servers init in sequence
- Instead of sequentially initializing each server with await this.initOneServer(name, cfg), uses `Promise.all()` to wait for all initialization promises to complete concurrently
- before
https://github.com/user-attachments/assets/e19a82ca-e88b-4853-a540-3fce6d7e9bab
- after
https://github.com/user-attachments/assets/df3dc75a-ccda-418c-b0f9-f15f596548d5

fix(amazonq): init mcp servers in parallel

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts

- Overall request size was set to 500K which is too conversative
- Readjust the limit to account for max ouput tokens and system prompt

fix: adjust overall limit per request to 570K characters

---

server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts

Reverts aws/language-servers#1755

revert "fix: adding files on windows properly triggers reindexing"

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts

fix: put streakLength under feature flag

---

core/aws-lsp-core/src/util/workspaceUtils.ts

Sometimes when dealing with relative paths to the workspace our isInWorkspace function breaks. 
Added handling for relative paths such that we verify its existance.

fix(amazonq): add handling for relative paths for isInWorkspace

---

.github/workflows/release-please.yaml

build: publish missing servers in release

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

Wrong condition check
Update the order

fix: wrong logical check for permission check

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

chore(amazonq): remove spam log

---

server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/mockData.ts
server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts

changed flag name to enablewebformtransform

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

Thinking... shouldn't appear for file writing operations as we already have a load circle in place
https://t.corp.amazon.com/P265169623/information
Remove additional thinking for long running file write operations.
https://github.com/user-attachments/assets/ce409006-b4cb-4a6b-9642-ebd485753502

fix: remove redundent thinking... for file operations

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts

adding streakLength back for UserTriggerDecisionEvent

feat: adding streakLength back for UserTriggerDecisionEvent

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/agenticChatControllerHelper.ts

further small code quality PR.
further small code quality PR.

refactor(amazonq): futher constant handling and creation of a helper

---

chat-client/src/client/mynahUi.ts

Previously, the icon and the text are hardcode in MynahUI.
Made these 2 variables in config 

fix(amazonq): use config to render the overlay

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts

feat: adding streakLength back to UTDE telemetry

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts

New requirements:
- Replace `"Thinking"` with `"Working"`
- Replace `"Stop"` with `"Cancel"`
https://github.com/user-attachments/assets/5e82bb1e-4ad4-48bf-8838-9ca4954055cc

fix: replace thinking with working and replace stop with cancel

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

fix: editor state does not use the same language id as file context

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts

fix: remove hardcoded EDITS predictionTypes for trigger on acceptance

---

chat-client/src/client/mynahUi.ts

When displaying subscription details, Chat will now re-use an existing "Account details" chat tab if one is open. Otherwise, it will create a new tab.
This avoids having multiple Account details tabs open.

chore: reuse subscription details tab if possible

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts

- Put compaction feature behind a feature flag

fix: put compaction feature behind a feature flag

---

chat-client/package.json
package-lock.json

Upgrade mynah-ui to latest version
Changelog: https://github.com/aws/mynah-ui/releases/tag/v4.36.0

chore(amazonq): upgrade mynah-ui to 4.36.0

---

chat-client/src/client/tabs/tabFactory.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts

fix(amazonq): revert auto-approve feature

---

app/aws-lsp-codewhisperer-runtimes/package.json
chat-client/package.json
chat-client/src/client/mynahUi.ts
chat-client/src/client/texts/paidTier.ts
package-lock.json
package.json
server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/shared/utils.ts

- Showing account details when user clicks account details in IDE
- When user reaches limit we will show the error in the chat 
- This PR uses latest GetUsageLimits API from RTS, to get the details and display them
https://github.com/user-attachments/assets/f5d3867d-dca0-42e8-b8b3-88a0a9d1c3a0
- It relies on ServiceQuotaExceededException to inform the user about monthly request limit reached error.

feat: adding pricing update for IdC users

---

chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts

- The getUsageLimits API has changed from backend. Updating the new contract.
- Also fixed this UI message when user reaches the limit.

Chore(amazonq): Updating contract for getUsageLimits API

---

chat-client/src/client/chat.ts
chat-client/src/client/mynahUi.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts

Feature branch continues to report merge conflicts despite attempts to resolve it.
Try touching the affected files instead of collapsing the conflicts into a no-op commit.

Second attempt to resolve conflicts between feature/subscription and main

---

chat-client/src/client/tabs/tabFactory.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts

feat(amazonq): revert auto-approve

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts

fix: adding acceptedCharacterCount to UserTriggerDecisionEvent

---

.gitattributes
binaries/hello-world.zip

This change is a test using LFS. It has one small hello world zip (containing a text file that says "hello world").
The purpose of this change is to test some internal processes to ensure they are able to successfully consume the repo once it has LFS contents in it.

chore: add a test LFS file to the repo

---

.github/workflows/integration-tests.yml

Github CI script fails
Fix the integ test command

test: fix integ test command

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-buildspec-runtimes/package.json
app/aws-lsp-cloudformation-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-s3-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
client/vscode/package.json
core/aws-lsp-core/package.json
integration-tests/q-agentic-chat-server/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-buildspec/package.json
server/aws-lsp-cloudformation/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-s3/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

fix: use new language server runtime

---

app/aws-lsp-antlr4-runtimes/package.json
app/aws-lsp-buildspec-runtimes/package.json
app/aws-lsp-cloudformation-runtimes/package.json
app/aws-lsp-codewhisperer-runtimes/package.json
app/aws-lsp-identity-runtimes/package.json
app/aws-lsp-json-runtimes/package.json
app/aws-lsp-notification-runtimes/package.json
app/aws-lsp-partiql-runtimes/package.json
app/aws-lsp-s3-runtimes/package.json
app/aws-lsp-yaml-json-webworker/package.json
app/aws-lsp-yaml-runtimes/package.json
app/hello-world-lsp-runtimes/package.json
chat-client/package.json
client/vscode/package.json
core/aws-lsp-core/package.json
integration-tests/q-agentic-chat-server/package.json
package-lock.json
server/aws-lsp-antlr4/package.json
server/aws-lsp-buildspec/package.json
server/aws-lsp-cloudformation/package.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-identity/package.json
server/aws-lsp-json/package.json
server/aws-lsp-notification/package.json
server/aws-lsp-partiql/package.json
server/aws-lsp-s3/package.json
server/aws-lsp-yaml/package.json
server/device-sso-auth-lsp/package.json
server/hello-world-lsp/package.json

chore: update runtime version

---

chat-client/package.json
package-lock.json

Feature branch build should use prerelease mynah-ui for testing
Bump mynah-ui version to 4.36.4-beta.1

chore: bump mynah-ui to beta

---

chat-client/package.json
chat-client/src/client/mynahUi.ts
integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
package-lock.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts

Merge read tool revamp to main
Previously approved PRs:
- https://github.com/aws/language-servers/pull/2078
- https://github.com/aws/language-servers/pull/2049

feat(amazonq): read tool ui revamp

---

chat-client/package.json
package-lock.json

New version of @aws/mynah-ui is available
bump @aws/mynah-ui to 4.36.4

chore: bump @aws/mynah-ui to 4.36.4

---

chat-client/src/client/mynahUi.ts
integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts

This reverts commit c65428bab2cf5e47badf1e3a9453babcf881e60c.

Revert "feat(amazonq): read tool ui revamp"

---

chat-client/src/client/tabs/tabFactory.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts

feat(amazonq): add back auto-approve

---

app/aws-lsp-codewhisperer-runtimes/src/version.json

fix: the style in version json

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/constants.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/editCompletionHandler.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts

config: remove edit completion retry mechanism on document change

---

app/aws-lsp-codewhisperer-runtimes/src/version.json

This merges the released changes for 1.29.0 into main.

chore: merge agentic version 1.29.0

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReview.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReviewTypes.ts

Need to emit a metric for each issue found by the agentic reviewer to reach parity with old behavior.
Emit metrics

feat(amazonq): emit metric for each issue

---

app/aws-lsp-codewhisperer-runtimes/_bundle-assets/qserver-darwin-arm64.zip
app/aws-lsp-codewhisperer-runtimes/_bundle-assets/qserver-darwin-x64.zip
app/aws-lsp-codewhisperer-runtimes/_bundle-assets/qserver-linux-arm64.zip
app/aws-lsp-codewhisperer-runtimes/_bundle-assets/qserver-linux-x64.zip
app/aws-lsp-codewhisperer-runtimes/_bundle-assets/qserver-win32-x64.zip
app/aws-lsp-codewhisperer-runtimes/src/version.json

chore: merge agentic version 1.30.0

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/editCompletionHandler.ts

perf: only process edit requests 1 at a time

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts

Adds infrastructure to detect and utilize IDE terminal integration capabilities in the ExecuteBash tool.
- Added isTerminalAvailable() method to check for IDE terminal support via LSP client capabilities
- Refactored invoke() method to route execution based on terminal availability.
- Added executeViaIDETerminal() method (pending implementation)
- Renamed existing execution logic to executeViaChildProcess()
- Maintains backward compatibility by falling back to child process execution.
- Includes error handling and fallback to child process execution when terminal integration fails.
- Terminal integration implementation is yet to implement.

feat: Add terminal availability detection for IDE integration in ExecuteBash tool

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts

fix(amazonq): add IntelliSense autotriggerType

---

chat-client/package.json
package-lock.json

New version of MynahUI is available
bump @aws/mynah-ui to 4.36.6

chore: bump @aws/mynah-ui to 4.36.6

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/workspaceContext/semanticSearch.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/workspaceContext/semanticSearch.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.test.ts
server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts

Follow-up PR from previous https://github.com/aws/language-servers/pull/2154/commits/36c44d210d992f29ee9059497b775d891804fd8b to feature branch
Bug bash is completed 

feat(amazonq): semantic search tool integration

---

server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts

chore: profile change log is recording stale profile instead of new updated one

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/memorybank/memoryBankController.ts

History size overflow
Further decrease the chance from happening

fix: limit file size for during memory bank analysis

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/memorybank/memoryBankController.ts

windows path not handled properly
fix windows path issue for memory bank, as I cannot test it on windows for now, adding some logs for easier debugging, will remove once fix is verified.

fix: fix windows path issue for memory bank

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/memorybank/memoryBankController.ts

There are few other places we need to normalize the path
* Normalize the path for cleanup and button text handling methods.
* Removed some unnecessary logs

fix: small path fix for button text, remove unnecessary logs

---

chat-client/package.json
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
package-lock.json

This change is going into a feature branch
I have made a change in a mynahui: https://github.com/aws/mynah-ui/compare/main...test-branch
I have created a beta release: https://www.npmjs.com/package/@aws/mynah-ui/v/4.36.7-beta.1
I would like to test the mynahui beta version - model description when hovering over model name

test: mynahui beta version

---

server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts

refactor: removing some redundant code

---

app/aws-lsp-codewhisperer-runtimes/src/version.json
server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQIAMServiceManager.ts
server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/BaseAmazonQServiceManager.ts
server/aws-lsp-codewhisperer/src/shared/streamingClientService.test.ts
server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts

This merges the released changes for 1.36.0 into main.

chore: merge agentic version 1.36.0

---

chat-client/package.json
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/client/texts/modelSelection.ts
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts

merging to feature branch to be able to test the flare manifest
- specifically want to test jetbrains - as there has been past issues with how the drop-down are displayed in JB
- I will have an actual real PR with real description and testing screenshots after

feat: add model description to dropdown

---

chat-client/package.json
chat-client/src/client/mynahUi.test.ts
chat-client/src/client/mynahUi.ts
chat-client/src/client/texts/modelSelection.ts
client/vscode/package.json
package-lock.json
server/aws-lsp-codewhisperer/package.json
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts

same as this test pr: https://github.com/aws/language-servers/pull/2377 with 1 extra change to `agenticChatController`. Looks like i changed a lot but it is only because commit was ammended. 
merging to feature branch to be able to test the flare manifest
- specifically want to test jetbrains - as there has been past issues with how the drop-down are displayed in JB
- I will have an actual real PR with real description and testing screenshots after

test: add model description to dropdown

---

server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts

fix: test fix localWsContext lib possibly fail to load

---

server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/handler/inlineCompletionHandler.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/handler/inlineCompletionHandler.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/textDocumentUtils.test.ts
server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/textDocumentUtils.ts

chore(amazonq): move getTextDocument to textDocumentUtils and add test
