- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/languageDetection.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/types.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/types.ts
need to publish diagnostics, handle hover for security scan findings, add handler for cancel scan and publish the security scan telemetry event
verified that diagnostics, hover and cancel works and telemetry event being sent as expected
> add diagnostics, cancel handler and telemetry for security scan

- app/aws-lsp-codewhisperer-binary/package.json
- app/aws-lsp-yaml-json-binary/package.json
- app/hello-world-lsp-binary/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-yaml-json/package.json
- server/hello-world-lsp/package.json
We are preparing refactoring in `aws-language-runtimes` package, which will introduce breaking changes to imports structure to dependant packages https://github.com/aws/language-server-runtimes/pull/76. 
New version of `aws-language-runtimes` will be next minor bump. To avoid current packages breaking on new minor, pin versions to currently used `0.1.x` minor version range.
> Pin aws/language-server-runtimes to minor version range.

- server/aws-lsp-yaml-json/src/language-server/testUtils.ts
- server/aws-lsp-yaml-json/src/language-server/yamlJsonServer.test.ts
- server/aws-lsp-yaml-json/src/language-server/yamlJsonServer.ts
YAML JSON LSP server needs to support more capabilities.
- Added onDidOpenTextDocument, onHover, onDidFormatDocument capabilities support 
- Added tests for new capabilities
- Added more tests for new capabilities
- ran `npm install && npm run compile && npm test`
- ran YAML JSON server in vscode instance and tested manually
> Added support for format, hover and onDidOpenTextDocument capabilities

- package-lock.json
- server/aws-lsp-codewhisperer/CHANGELOG.md
- server/aws-lsp-codewhisperer/package.json
Due to v0.0.3 not able to be installed because it was depending on local tarball that was not included in the registry, we need to publish a new version of the CodeWhisperer server
Migrate the consumption of `@aws/language-server-runtimes` from local to npmjs, release new version and publish it to npm.
> Release 0.0.4

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/types.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
This change updates the `SecurityScanResponse` that is sent to client when RunSecurityScan is invoked.
Changes include:
* `SecurityScanFindings` data object is created that represents the total findings, findings with fixes and files scanned.
* `SecurityScanResponse` now contains `SecurityScanFindings` and the status of the operation
* Error records the error message when a failure occurs instead of passing it as an object
* Tool name for the security scan is updated to be more concise as `CodeWhisperer`
*  Security scan final output message is refactored to be a bit more clear
> Update SecurityScanResponse to include relevant details when security scan is performed

- app/aws-lsp-codewhisperer-binary/package.json
- app/aws-lsp-yaml-json-binary/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/hello-world-lsp-binary/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-yaml-json/package.json
- server/hello-world-lsp/package.json
Updating runtimes to [0.2.2](https://www.npmjs.com/package/@aws/language-server-runtimes/v/0.2.2)
> Update runtimes to 0.2.2

- package-lock.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/package.json
CodeWhisperer streaming client has unused dependency, which messes with our internal workflow.
Script that uses dependency seem to be unused during build process. Remove it and problematic dependency from the project.
> Remove downlevel command and dependency from CodeWhisperer streaming client

- package-lock.json
- package.json
- server/aws-lsp-codewhisperer/package.json
Postinstall script in CodeWhisperer LSP runs build script of streaming client dependency package. This script fails when `@aws/lsp-codewhisperer` client is installed as a dependency due to missing transient dependencies at installation time.
This breaks workflows, that use `@aws/lsp-codewhisperer` as a direct dependency.
Remove `postinstall` script from `server/aws-lsp-codewhisperer`. Compiling streaming client dependency is triggered in `compile` command still.
> Remove postinstall script to build dependencies

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- Create a chat server skeleton with a proxy variant
- Create session management service that manages the mapping between tabId and api client
- Each tab can have an outgoing request at the same time (we will need to add a restriction there)
- Each outgoing request can be cancelled separately
- Add more tests for the ChatServer as I work on the implementation
- Look into reducing the number of libraries needed for http proxy
- Tested in vscode "Run and Debug" 
- I can make a chat request  
- I can make a request through a proxy 
> Chat server skeleton

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts
This change fixes a bug where when a project was unloaded in the IDE and a new one opened, the security scan findings(diagnostics) associated with the previous project did not get cleared.
This change adds handling for the `workspace/didChangeWorkspaceFolders` [lsp notification ](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders) sent by the client. The handler clears diagnostics associated with the previous security scan run(project).
Bonus: This change also converts the `resetDiagnostic` method to operate asynchronously.
> Clear security scan findings on workspace/didChangeWorkspaceFolders event

- CONTRIBUTING.md
After refactoring of runtime repo, documentation here was outdated
Updated doc with up to date instructions
> Fix guide for npm linking runtimes package after refactorings

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts
Security Scan diagnostic error messages were displayed twice in the IDE hover.
Removes the LSP hover message since the default hover displays the relevant information. 
- Future work to add additional content to this hover can redefine a hover handler - this will add, but not replace, content in the IDE's existing diagnostic hover.
Also changes the Diagnostic's Description to be constructed with the `DetectorName` rather than the `Title`. The `Title` field is a combination of the error code and the `DetectorName`, which was resulting in duplication of the error code
> Fix security scan duplicate hover message

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
getConnectionMetadata will be made optional when enabling the injection of credentialsProvider. Current code will break if the provider does not define the method.
https://github.com/aws/language-server-runtimes/pull/101
Make the method optional since practically it is already optional
> Ensure getConnectionMetadata is defined

- package-lock.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/package.json
Pre-maturely merged, internal process not synced yet
Reverts aws/language-servers#218
> Revert "Bump @aws-sdk/middleware-token from 3.425.0 to 3.564.0"

- app/aws-lsp-yaml-json-binary/src/index.ts
- app/aws-lsp-yaml-json-webworker/src/yamlJsonWebWorkerRuntimeServer.ts
- package-lock.json
- server/aws-lsp-yaml-json/src/index.ts
- server/aws-lsp-yaml-json/src/language-server/yamlJsonServer.ts
LSP server should be customizable and get any json-schema.
Added function to create LSP Server using any json-schema. Added options to customize display name, uri Resolver and allow Comments for JSON files.
ran `npm install && npm run test`
> Added customizable LSP server

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/types.ts
- Create a controller logic to centralize the handler functions so it's more maintainable/readable
- Convert many of the code to use the Result pattern so we can have a more unified error handling pattern
- Tests in `chatController.test.ts` are moved from `QChatServer.test.ts` and are modified accordingly
> Refactor chat handlers

- app/aws-lsp-yaml-json-binary/src/tests/testUtilsCF.ts
- app/aws-lsp-yaml-json-binary/src/tests/yamlJsonServerCFInteg.test.ts
- core/aws-lsp-yaml-common/README.md
- core/aws-lsp-yaml-common/package.json
- core/aws-lsp-yaml-common/patchYamlJsonPackage.js
- core/aws-lsp-yaml-common/patches/markdown/yamlHover.esm.patch
- core/aws-lsp-yaml-common/patches/markdown/yamlHover.src.patch
- core/aws-lsp-yaml-common/patches/markdown/yamlHover.umd.patch
- core/aws-lsp-yaml-common/patches/markdown/yamlLanguageService.esm.patch
- core/aws-lsp-yaml-common/patches/markdown/yamlLanguageService.src.patch
- core/aws-lsp-yaml-common/patches/markdown/yamlLanguageService.umd.patch
- core/aws-lsp-yaml-common/patches/unsafe-eval/yamlSchemaService.esm.patch
- core/aws-lsp-yaml-common/patches/unsafe-eval/yamlSchemaService.src.patch
- core/aws-lsp-yaml-common/patches/unsafe-eval/yamlSchemaService.umd.patch
- core/aws-lsp-yaml-common/src/language-server/yamlLanguageService.ts
- package-lock.json
- we do not want to show footer and header in hover content
- ajv compile require `unsafe-eval` rule to be enabled. We can't enable this rule.
Added patches for markdown hover result and removed ajv usage.
ran `npm install && npm run test`
checked in browser that unsafe-eval is not required after applying the patch
> added patches for markdown and unsafe-eval

- package-lock.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/package.json
Dependabot upgraded the typescript version and the build passed for some reason. It should trigger a version conflict instead due to `typedoc` dependency requiring typescript version 4.x 
Upgrade typedoc to latest version
> Upgrade typedoc version

- server/aws-lsp-codewhisperer/package.json
When  `@aws/lsp-codewhisperer` is consumed as a module, we get this error at build time:
```
ERROR in ./node_modules/@aws/lsp-codewhisperer/out/language-server/chat/chatSessionService.js 16:34-74
Module not found: Error: Can't resolve '@amzn/codewhisperer-streaming' in '.../node_modules/@aws/lsp-codewhisperer/out/language-server/chat'
```
Even though `@amzn/codewhisperer-streaming` are packaged within the builds, build system is not able to resolve that path (e.g. not found in `node_modules` or aliases). Currently, our internal build system relies on manually releasing the streaming package, which is not possible for consumers.
To make it work for consumers,  the most efficient way to solve this is to define a local dependency with a local path in `package.json`. During install command, …
> Fix @amzn/codewhisperer-streaming resolve issue in consumers

- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Browser build of qChatServer gets error in runtime in making Q api calls:  `TypeError: Failed to construct 'Request': Failed to read the 'signal' property from 'RequestInit': Failed to convert value to 'AbortSignal'.`  According to this issue, https://github.com/aws/aws-sdk-js-v3/issues/4582, we should use browser's native `AbortController`.
Browsers have full support for `AbortController` for a while and `AbortController` has been part of Node since v15.0.0. So we shouldn't need to install this that package at all.  `aws-sdk-v3`, which the streaming client uses under the hood, does not support 14.x anymore so we can just to remove `@smithy/abort-controller`
> Remove @smithy/abort-controller to fix browser builds

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
Renaming occurrences of `CodeWhisperer` to `Amazon Q`
> Rename CodeWhisperer to Amazon Q

- package-lock.json
- server/aws-lsp-codewhisperer/CHANGELOG.md
- server/aws-lsp-codewhisperer/package.json
We need to bump a version of CodeWhisperer server for release
Version is bumped to 0.0.6
> Increment aws-lsp-codewhisperer version to 0.0.6

- .vscode/launch.json
- app/aws-lsp-partiql-binary/package.json
- app/aws-lsp-partiql-binary/src/index.ts
- app/aws-lsp-partiql-binary/tsconfig.json
- app/aws-lsp-partiql-binary/webpack.config.js
- package-lock.json
- server/aws-lsp-partiql/.gitignore
- server/aws-lsp-partiql/.prettierignore
- server/aws-lsp-partiql/README.md
- server/aws-lsp-partiql/build-scripts/compile-inline-partiql-wasm.mts
- server/aws-lsp-partiql/build-scripts/compile-partiql-wasm-docker/base64-encode-partiql-binary.mts
- server/aws-lsp-partiql/build-scripts/compile-partiql-wasm-docker/compile-base64-partiql-wasm-binary.dockerfile
- server/aws-lsp-partiql/build-scripts/compile-partiql-wasm-docker/compile-partiql-wasm-binary.mts
- server/aws-lsp-partiql/build-scripts/create-empty-wasm-file.mts
- server/aws-lsp-partiql/jest.config.js
- server/aws-lsp-partiql/package.json
- server/aws-lsp-partiql/src/index.tsx
- server/aws-lsp-partiql/src/partiql-parser-wasm/README.md
- server/aws-lsp-partiql/src/partiql-parser-wasm/partiql_playground.d.ts
- server/aws-lsp-partiql/src/partiql-parser-wasm/partiql_playground.js
- server/aws-lsp-partiql/src/server/error-parsing/lexer-errors.ts
- server/aws-lsp-partiql/src/server/error-parsing/parser-errors.ts
- server/aws-lsp-partiql/src/server/language-server.test.ts
- server/aws-lsp-partiql/src/server/language-server.ts
- server/aws-lsp-partiql/src/server/language-service.test.ts
- server/aws-lsp-partiql/src/server/language-service.ts
- server/aws-lsp-partiql/test-utils/esm-transformer.js
- server/aws-lsp-partiql/tsconfig.json
- tsconfig.json
Adds an LSP server for the [PartiQL language](https://partiql.org/). This server offers diagnostics for PartiQL files by parsing the file using the [Rust parser maintained by the PartiQL team](https://github.com/partiql/partiql-lang-rust).
This parser is compiled to a WebAssembly binary using the bindings maintained by the PartiQL team in the [PartiQL playground package](https://github.com/partiql/partiql-rust-playground). This binary is further encoded as a base64 string in a Javascript file to make it easy to be bundled together with the other assets of the server. See the README for instructions on how to update the binary.
- Tested the server wrapped in the standalone runtime in VS Code:
- Tested the server wrapped in the webworker runtime a web-based LSP client.
- Added unit tests …
> feat: add PartiQL language aserver

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
In npm “^0.0.1” can be resolved only to “0.0.1", not “0.0.2” or “0.1.1".
This is because npm considers a major version “the leftmost non zero digit”. So, “0.0.2" is a major version change.
https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004
Changed dependency to 0.x.x
> Allow upgrading runtime packages within 0.x.x

- server/aws-lsp-yaml-json/patchYamlJsonPackage.js
When `language-servers` is checked out under a directory that contains spaces in the full path, `npm install` will fail to complete due to `patchYamlJsonPackage.js`.
This commit fixes this issue by ensuring file paths are quoted to support spaces in them.
Ensured `npm install` succeeds in a directory with spaces in the full path (i.e. under a user's `Application Support` folder for Sublime Text on OS X).
> Update `patchYamlJsonPackage.js` to handle paths with spaces in `applyPatch`

- package-lock.json
- server/aws-lsp-partiql/.npmignore
- server/aws-lsp-partiql/CHANGELOG.md
- server/aws-lsp-partiql/package.json
We want to release existing PartiQL server as npm package.
Prepared `server/aws-lsp-partiql` project for npm release
> Release @aws/lsp-partiql v0.0.1 to npm

- client/vscode/src/chatActivation.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatTelemetryController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/types.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
Emits metrics for `tabAdd`, `tabChange`, `tabRemove` notifications, as well as `enterFocus` and `exitFocus` telemetry events received from client. 
- Add `chatTelemetryController` which does the following:
- listens to `enterFocus` and `exitFocus` telemetry events from client
- keeps track of tab id to conversation id mapping
- auto append conversation id to related metrics
- Add tests
> Emits basic chat metrics

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- Support `clear` and `help` quick actions
- Register quick actions in the `awsServerCapabilities`
Referenced https://github.com/aws/language-servers/pull/282 and vscode for help text
> Add Chat Quick Action support

- .gitignore
- server/aws-lsp-codewhisperer/src/client/sigv4/codewhisperer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
The CodeWhisperer IAM Server was creating its client using the options type from the CodeWhisperer Token Client. This led to a bug wherein the IAM Server was using `onRequestSetup`, which is not a recognized option for its client. Instead, the proper way to modify HTTP requests in its client is to use `setupRequestListeners`.
This discrepancy is due to the fact that the Service Client's options passed via the factory method for the Token Client [have been modified](https://github.com/andredcoliveira/language-servers/blob/6ba221873b824d611c731230dab91cc3caeda318/server/aws-lsp-codewhisperer/src/client/token/codewhisperer.ts). I think this is unnecessary and might be what led to this bug, which is why I did not modify the IAM Client module to match the Token Client. I would suggest …
> Fix CodeWhisperer IAM "optout" header

- .prettierrc
- .vscode/launch.json
- .vscode/settings.json
- app/hello-world-lsp-runtimes/package.json
- app/hello-world-lsp-runtimes/webpack.config.js
- chat-client/src/client/chat.test.ts
- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- chat-client/src/contracts/serverContracts.ts
- client/vscode/package.json
- client/vscode/src/activation.ts
- client/vscode/src/chatActivation.ts
- package-lock.json
- server/hello-world-lsp/package.json
- server/hello-world-lsp/src/language-server/helloWorldServer.ts
We need to implement Quick Actions support for Chat Client package.
* Registered Quick Actions handlers in Chat Client package.
* Created sample Quick Actions and Chat message handlers in HelloWorld server. Added registration of custom AWS Language server `chatQuickActionsProvider` capability introduced in https://github.com/aws/language-server-runtimes/pull/131.
* Updated sample VSCode client extension to register Chat client synchronously and use `chatQuickActionsProvider` from LSP server InitializeResult handshake to configure Quick Actions in Chat Client.
* Extended Chat Client init function to allow passing configuration from integrating IDE Extension client. This allows to configure chat at start time.
Check on this PR are failing, until runtimes and types are not updated with …
> Added Quick Actions support to Chat Client

- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/package.json
- server/aws-lsp-s3/package.json
The dependencies in the streaming client package have been pinned due to incompatibility with newer versions: https://github.com/aws/aws-toolkit-vscode/pull/4448
This fails our build if package-lock.json is recreated
Revert the version bumps 
> Revert dependabot

- app/aws-lsp-yaml-binary/src/tests/yamlServerCFInteg.test.ts
- package-lock.json
- server/aws-lsp-yaml/package.json
- server/aws-lsp-yaml/src/language-service/yamlLanguageService.ts
YAML patching script is using commands that are. not working on Windows machines, resulting in failed `npm install` script
Temporarily disable patching to unblock development on Windows machines, until a long term solution is developed. 
> Disable YAML patching

- server/aws-lsp-partiql/src/server/language-service.test.ts
- server/aws-lsp-partiql/src/server/language-service.ts
Queries like 
```
SELECT * 
FROM "TableName"."IndexName" 
```
should not result in diagnostics. (see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.select.html)
Currently these result in diagnostics with the error `InvalidInput("\")` which is coming from the extra `\` we add in `normalizeQuery`. The query is directly send to the wasm module [here](https://github.com/aws/language-servers/blob/main/server/aws-lsp-partiql/src/partiql-parser-wasm/partiql_playground.js#L181) so the extra escaping of the `"` doesn't seem to be necessary. 
Same bug was present in the partiql-playground package using the same WASM module and was fixed in the same way in https://github.com/partiql/partiql-rust-playground/pull/16.
Removed the replacement of `\"` by `\\"` in the …
> fix: partiql - don't report diagnostics for quoted identifiers

- chat-client/package.json
- chat-client/src/client/chat.test.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
If user has an outgoing request and use the generic commands, the chat history becomes a mess. 
Note: 
- Change `sinon.stub` -> `sandbox.stub` in `chat.test` since there is only a `sandbox.restore()`, which affected the other test file.
- Changed `mynah.test` to use `beforeEach` setup as it is difficult to debug shared setup
- Clear all tabs after each test since both test files seem to share the same UI (with the same tab limit)
vscode current opens up a new tab if there is an outgoing request. This PR mimics their behavior.
> Send Generic command to new tab if current tab is busy

- server/aws-lsp-partiql/CHANGELOG.md
- server/aws-lsp-partiql/package.json
We need to bump a version of PartiQL server for release
Version is bumped to 0.0.2
> chore: Increment @aws/lsp-partiql to 0.0.2

- package-lock.json
`npm ci` fails because the `package.json` and `package-lock.json` are out of sync after we bumped the partiql server 
Ran `npm install` locally which updated the package-lock and now they are in sync
> [PartiQL release] Updating package-lock.json before releasing the partiql server 0.0.2

- .github/workflows/lsp-ci.yaml
Our GitHub actions use `npm install` which means that the resulting dependency tree can be different from what is in a `package-lock.json`.
Switched to the `npm ci` which is recommended for automated environments such as GitHub actions
https://docs.npmjs.com/cli/v10/commands/npm-ci
More info: [Why developers should use npm ci instead of npm install and its benefits?](https://support.deploybot.com/article/131-why-developers-should-use-npm-ci-instead-of-npm-install-and-its-benefits)
> Run npm ci instead of npm install in GitHub actions

- .github/workflows/lsp-ci.yaml
- server/aws-lsp-yaml/patchYamlPackage.js
Recently code committed to one of the monorepo subpackages resulted in build errors on Windows machines. This project targets cross-platform execution and development targets, and should not block engineers.
Configure CI Build and Test workflows to run in Windows runners to catch build problems for every code contribution.
> Run workflows on Windows

- app/aws-lsp-yaml-json-webworker/package.json
- package-lock.json
We have 9 vulnerabilities in our dependency tree:
```
debug  <=2.6.8
Severity: high
deep-extend  <0.5.1
Severity: critical
pkg  *
Severity: moderate
underscore  1.3.2 - 1.12.0
Severity: critical
bower-license  >=0.1.0
Depends on vulnerable versions of bower-json
Depends on vulnerable versions of npm-license
Depends on vulnerable versions of underscore
```
It turns out that 8 out of 9 vulnerabilities (except for `pkg`) are transitive dependency of `license-checker` and `oss-attribution-generator`. These are abandoned projects, and we don't even use them but just declare them in the package.json. 
Removing them fixes the issues. 
> Removed unused and vulnerable dependencies

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- package-lock.json
Updating mynah to the latest version, this gets rid of the outdated `ws` dependency downstream. 
Also with mynah 4.10, the ability to specify `code` option in `addToUserPrompt` was introduced, updated the chat client to make use of it
> Bump mynah version in chat client

- .github/workflows/lsp-ci.yaml
- chat-client/package.json
- client/vscode/package.json
- core/aws-lsp-core/package.json
- package-lock.json
- package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-yaml/package.json
The package fails builds on Windows. One of the reason is that we have `cp` in our npm scripts which only works on linux. 
Another problem was that we ran `prettier -- check` in some subpackages. In windows git automatically converts linux's `LF` line endings into Windows' `CRLF` when pulling files. It works generally, because git also converts them back to the linux's `LF` before staging or committing the files. And our husky git hooks also run prettier before committing so that prettier will convert the line endings to linux's LF even if git wouldn't. 
But it all breaks because we had npm script that ran `prettier check` on running. And the command fails on windows as it notices `CRLF` line endings which are not allowed.
- Use shx tool to make linux-specific calls cross platform
- Run …
> Fixing Windows problems - prettier CRLF and linux cp tool

- server/aws-lsp-partiql/jest.config.js
The partiql tests were failing on windows because jest couldn't transform an esm module to cjs
Turned out that the jest configuration had linux style path separators and that's why babel esm transformations didn't apply to the esm file on windows.
Changed the regex matcher to only include the filename. 
> Fixed partiql tests failing on windows

- chat-client/src/client/chat.test.ts
- chat-client/src/client/mynahUi.ts
If toolkit has to keep track of the tabs, it is difficult to do so currently because there isn't an event for the initial tab. So chat-client should emit an event on start up.
I think setting trigger to "click" might make sense, but unsure about this.
> Emit initial add tab event

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/README.md
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/package.json
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/commands/ExportResultArchiveCommand.ts
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateAssistantResponseCommand.ts
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/commands/GenerateTaskAssistPlanCommand.ts
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/models/models_0.ts
- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/protocols/Aws_restJson1.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.ts
Codewhisperer streaming client package used in Codewhisperer LSP is 2 months old and outdated.
* Updated `@amzn/codewhisperer-streaming` package to latest version used in AWS Toolkit https://github.com/aws/aws-toolkit-vscode. Tested Chat functionality with sample VSCode extension.
* [`Reference.recommendationContentSpan`](https://github.com/aws/language-servers/pull/327/files#diff-21a75ff27b821e42265decb7a14a13858a5244ba32b4fb3eca9cc55ba3e4c8ecR279-R280) interface is not compatible with Chat [`ReferenceTrackerInformation`](https://github.com/aws/language-server-runtimes/blob/4480b87a81c84dda229538fed7cbf165a44dc971/types/chat.ts#L36-L39) class anymore: `start` and `end` fields are defined as optional now. I had to adjusted [`chatEventParser`](https://github.com/aws/language-servers/pull/32 …
> Update Codewhisperer streaming client package

- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatEventParser.ts
- A spinner is showing up after the screen is cleared.  We should just terminate early in the chat-client chat request logic for `/clear` command
- Thumbs up and down are not showing up due to missing `canBeVoted` - we should set `canBeVoted` to true by default unless otherwise specified
As a bonus, we will add a default `What can Amazon Q help me with?` for `/help` command like vscode does
> Set message can be voted; fix clear command

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
Unfortunately, we have to send a fake telemetry which seems to be the only way in time constraint. We will intercept it on toolkit side and handle it differently.
> Send feedback as telemetry back

- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
/clear quick action caused a `generating your answer` chat item to be added that would not go away because the server would respond with an empty object causing the chat client to create an empty chat item. This would cause mynah to create a chat item that assumed it was going to be filled with data and therefore had the `generating your answer` string
chat client will not try to create a chat item if the server response is an empty object 
> Make sure clear quick action doesn't get stuck loading

- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
This is likely a blocker. Token is getting reused in the same session, which means any reauth won't be propagated to the api calls. New tabs would always have the most up to date token.
client does not need to be destroyed as per the comments in the package
> Instantiate a new chat client on every request

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/clientTelemetry.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/types.ts
- Track document position and inserted code when user uses the insert code to cursor functionality and insert to a queue
- When an entry has been added for at least five minutes, we use use fastest-levenshtein to calculate edit distance between the current text in the same position and the original inserted text.
We are able to get the E2E flow working in VS by forcing the cursor state and document identifier through, but they should be added to the interface later on.
✅ Tested E2E flow in Visual Studio 
> Add Chat modify code telemetry

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
Security scan error messages were vague and did not provide enough information on what the error being returned from LSP was
Update wording on error messages to describe the issue rather than returning internal objects
> Ensure errors are useful message for security scan

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.ts
- Clean up some unneeded logging. 
- Remove partial response data from response error since they won't be encrypted.
> Clean up logging and remove q data from response error

- server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts
Typo in /help quick action where `selected code` was missing from the example questions.
Update text to include the missing string
> Fixing typo in /help quick action

- script/link_bundled_dependencies.ts
Running `npm pack` in `aws-lsp-codewhisperer` directory references files from parent directories (which are mostly dependencies of bundledDependencies, that don't need to be part of the final bundle) which causes `npm publish` to fail.
This PR updates our prepack script to copy bundled dependencies instead of symlinking them. When I run `npm pack` with this configuration I don't see any files from the wrong scope being referenced
> Update prepack script to copy instead of symlink bundled dependencies

- .vscode/launch.json
- app/aws-lsp-partiql-runtimes/package.json
- client/vscode/src/extension.ts
- package-lock.json
https://github.com/aws/language-servers/issues/374
>PartiQL / JSON / YAML server are not able to launch after https://github.com/aws/language-servers/pull/328 and https://github.com/aws/language-servers/pull/326
- Explicitly start the Language Client after config
- Fix launch configuration for PartiQL, YAML, and JSON servers
- chore: Update PartiQL server used in the runtime app
> Fix servers not starting in VSCode

- app/aws-lsp-yaml-json-webworker/package.json
- client/vscode/package.json
- package-lock.json
- package.json
Upgrade Typescript dependency as an alternative to this dependabot CR: https://github.com/aws/language-servers/pull/370.
Typescript update in CodeWhisperer streaming library was excluded.
> Upgraded ts dependency version without CW streaming client upgrade

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
The progress completion handler in VS always start the token as 0 then increment after each request. The very first request will not have partial result because 0 is falsey. 
partialResultToken can be both numbers and strings, so it is reasonable to expect that 0 should work as a token. Requires https://github.com/aws/language-server-runtimes/pull/171  to work
> Allow "0" to be used as partial token in chat handler

- client/vscode/package.json
- client/vscode/src/activation.ts
For testing the PartiQL LSP server, we now have to create files which have the wrong extension.
Add partiql language to the extension and activate when a PartiQL file is opened.
> Add PartiQL files to VSCode dev extension activation

- app/aws-lsp-partiql-runtimes/package.json
- package-lock.json
- server/aws-lsp-partiql/CHANGELOG.md
Releasing new @aws/lsp-partiql, version 0.0.3. In PR #407, only the server package has been upgraded.
Upgrade the version in app package accordingly. Also update the CHANGELOG.md for partiql server.
> Bump @aws/lsp-partiql to 0.0.3 in app package

- server/aws-lsp-codewhisperer/src/language-server/netTransform/converter.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
When multiple projects/ solution is selected with multiple projects, source framework for project is randomly selected. This causes .net8 projects to be selected to transform and backend will reject this request because that project is already transformed
Added logic to get minimum version of dot net and set it as source framework
only for cwspr API
- [ ✔] Pull request title describes the changes without ambiguity
- [ ✔] Added screenshots of visual/UI changes 
- [ ✔] Added Unit test coverage
- [ ✔] Removed all developer references (internal URLs, etc)
- [ ✔] Removed unused code, comments, references, namespaces
- [ ✔] Used constants/readonly where needed
- [ ✔] Used appropriate data structures
- [ ✔] Used consistent naming convention
- [ ✔] Used predefined Toolkit themes for UI elements
- …
> Fixing issue with random source framework selection

- .vscode/launch.json
- client/vscode/package.json
- client/vscode/src/activation.ts
- client/vscode/src/chatActivation.ts
- client/vscode/src/sampleCommandActivation.ts
- The sample extension was failing at startup due to misconfigured commands, fixed that
- The sample extension was designed to work only with encrypted chat meaning the hello world server wasn't working, fixed that
- Did small refactor on the sample extension to tidy up the code and reduce duplicate code
- Updated the launch configuration of token server and hello world server to use a temporary profile, using the temp-profile allows to debug in a clean environment that ensures no confusion happens between installed extensions and the sample extension (https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_72.md#extension-debugging-in-a-clean-environment) 
> Fix sample extension 

- package-lock.json
- server/device-sso-auth-lsp/README.md
- server/device-sso-auth-lsp/package.json
- server/device-sso-auth-lsp/src/index.ts
- server/device-sso-auth-lsp/src/language-server/SsoAuthServer.ts
- server/device-sso-auth-lsp/src/language-server/sso/builderId.ts
- server/device-sso-auth-lsp/src/language-server/sso/model.ts
- server/device-sso-auth-lsp/src/language-server/tsUtils.ts
- server/device-sso-auth-lsp/tsconfig.json
This is port of Device Auth SSO flow, implemented in sample VSCode client to LSP Server.
It implements custom `ssoAuth/authDevice/getToken` LSP command to retrieve SSO token, and start SSO flow if required. See [README](https://github.com/aws/language-servers/compare/device-auth-sso-lsp?expand=1#diff-5e02c79a2bd5dfb1d2c367fb1cb46e2de9c7ba54b3e85d296230551288b4f702) with more detailed documentation.
Caches token on filesystem and supports only `standalone` runtime.
This Capability can be used to inject device token management flow as part of  Language Servers runtime bundles.
Requires this PR to be released in Language Server Runtimes repo https://github.com/aws/language-server-runtimes/pull/185
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Implement sample device auth SSO flow in LSP server

- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContexts.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/utils.ts
The expected behavior is that users can ask questions about active document so we need to include a default position and allow collapsed position.
> Allow sending document without active focus in Chat requests

- package-lock.json
- server/aws-lsp-codewhisperer/CHANGELOG.md
- server/aws-lsp-codewhisperer/package.json
CodeWhisperer Language Server release is required.
Increment the version and update the changelog for the release.
> Releasing CodeWhisperer Language Server 0.0.12

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
customer seeing auto-trigger doesn't seem to be triggering
auto-trigger should always trigger on Enter and Special characters, only for Classifier trigger type we need to check the classifier result if it's above threshold
> fix(amaoznq): fix autotrigger often doesn't trigger

- .gitignore
app/aws-lsp-partiql-binary/ is being tracked by git.  No other *-binary are tracked by git based on https://github.com/aws/language-servers/tree/main/app. .gitignore was already ignore app/aws-lsp-partiql-runtimes, so this appeared to be a miss in the pattern.
Updated app/aws-lsp-partiql-runtimes in .gitignore to app/aws-lsp-partiql-* to ignore the build artifacts as well.
> Add app/aws-lsp-partiql-binary/ to .gitignore

- .vscode/launch.json
- server/aws-lsp-codewhisperer/src/client/streamingClient/codewhispererStreamingClient.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
Unable to connect to Q via specific proxy settings
Pass ca cert to CodeWhisperer SDK client
> Add ca certificate config in CW SDK client

- server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
In the `transformHandler.ts`, polling to get transform status will return `FAILED` as job status if caught one error. But the error can be caused by network issue or the API call timeout.
This PR adds the retry policy to `pollTransformation` from the server, it will retry 3 times after the first failure occurs. 
> Add retry to pollTransformation

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
Depend on the latest @aws/language-server-runtimes 0.2.15 that honors shared aws config in the standalone runtime
> update @aws/language-server-runtimes dependency to 0.2.15

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
Following up to https://github.com/aws/language-servers/pull/441, the previous PR added a linear delay to each retry, that may fall to synchronization problems
Changing from linear delay to exponential delay to avoid synchronization problems
> Change from linear delay to exp delay for .NET transform API calls

- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/transformHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts
In LSP, we were setting job status to failed on any API failure from cwspr. 
fixing to ignore this error and poll again. 
> Removing manually setting job status to failed after any error from cwspr API

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
When StartTransform is failed due to the credentials are not allow-listed, the logged error message is "Invalid transformation specification" which is confusing. 
Update the error message indicating permissions issues.
[ ✔] Pull request title describes the changes without ambiguity
[ ✔] Added screenshots of visual/UI changes
[ ✔] Added Unit test coverage
[ ✔] Removed all developer references (internal URLs, etc)
[ ✔] Removed unused code, comments, references, namespaces
[ ✔] Used constants/readonly where needed
[ ✔] Used appropriate data structures
[ ✔] Used consistent naming convention
[ ✔] Used predefined Toolkit themes for UI elements
[ ✔] Used appropriate method and property access levels (private vs public)
[ ✔] Avoided global and singleton references where possible
[ ✔] Enforced DRY …
> Update StartTransform error message

- app/aws-lsp-codewhisperer-runtimes/src/token-standalone.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
The proxy version of `QConfigurationServer` was wrongly named as `QCustomizationServerTokenProxy` where it should have been named as Configuration server
Renamed to `QConfigurationServerTokenProxy`
> Rename customization server to configuration server

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/validation.ts
Project Type validation was disabled. Only valid project types can be used for transformation.
Enable Project Type Validation. If the project type is not valid return NotSupported in case of a project transformation or the unsupported projects list in case of a solution transformation.
> Enable Project Validation

- .mocharc.js
- .vscode/launch.json
- server/aws-lsp-identity/package.json
"Unit Tests" and "Unit Tests (Current File)" didn't do anything and seemed to not be configured for the current state of the repo where there doesn't appear to be a "test" directory (outside of chat-client, which its "test" directory didn't conform to the launch.json configurations above anyway) and tests end with '.test.js'.  Unit tests can be run from VSC using both configs with this update.
Added .mocharc to and set some sane defaults.
Updated aws-lsp-identity package.json test scripts to conform to other packages in repo.
> Fix unit testing in VSC and update aws-lsp-identity test scripts to conform to repo

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
The "FAILED" status during polling transformation is typically due to build validation failures. Currently, no guidance is logged when the job status fails. 
Add logs to recommend that customers clear the binary cache and retry.
> [Team Review] Add logging when polling get transformation status failed

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
Following up comments on this PR: https://github.com/aws/language-servers/pull/476
There are probably other places where we log some suggestion after a failure message.
Addressed comments on the above mentioned PR. Rephrase the suggestion message and put it into a function.
> Add transform logSuggestionForFailureResponse

- client/vscode/package.json
- client/vscode/src/credentialsActivation.ts
- client/vscode/src/sso/connectionBuilder.ts
- client/vscode/src/sso/model.ts
The sample extension currently doesn't support identity center login which means some functionality can't be tested using the sample extension 
Updated the sample extension so that now the extension exposes two versions of `Obtain token` command, one for builderid and one for identity center. 
I tested both options and logging in through both methods work as expected. Also verified that list customizations request is successful after Identity center login 
> Add identity center login to the sample extension

- chat-client/.npmignore
- chat-client/CHANGELOG.md
- chat-client/package.json
- package-lock.json
Chat client package doesn't export built bundle into npm.
Publish `build` directory to npm.
> Fix export for chat-client npm package; release v0.0.5

- .github/workflows/publish-chat-client.yaml
- .github/workflows/publish-lsp-codewhisperer.yaml
- .github/workflows/publish-lsp-yaml.yaml
`name` field in some Github workflows is incorrect.
Fix names of workflows.
> Fix publish to npm workflows names

- .vscode/launch.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-identity-runtimes/src/standalone.ts
- app/aws-lsp-identity-runtimes/tsconfig.json
- client/vscode/package.json
- client/vscode/src/activation.ts
- client/vscode/src/extension.ts
- client/vscode/src/identityActivation.ts
- package-lock.json
- server/aws-lsp-identity/README.md
- server/aws-lsp-identity/package.json
- server/aws-lsp-identity/src/index.ts
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.test.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.test.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConifgProfileStore.test.ts
- server/aws-lsp-identity/src/utils/asyncEvent.test.ts
- server/aws-lsp-identity/src/utils/asyncEvent.ts
- server/aws-lsp-identity/src/utils/duckTyper.ts
- tsconfig.json
This PR pending merge and publication of new @aws/language-server-runtimes package due to protocol updates.  See https://github.com/aws/language-server-runtimes/pull/222 for details.
1. Added simple AsyncEvent implementation of event pattern to support easy usage in the identity server as well as chaining to JSON-RPC server to send.  Existing Node and JavaScript events were too heavyweight and unsuitable for this application.
1. Added app/aws-lsp-identity-runtimes modeled after other apps in the app folder to support launching standalone runtime of identity server.
1. Added outFiles to support debugging of ts-mocha launch.json configuration.
2. Removed notes about using identity-management for imports instead of service-interface after guidance in prior PR.
3. Removed unnecessary …
> Add SsoTokenChanged, profile bug fixes, and testability of aws-lsp-id enity in vscode client

- chat-client/package.json
- chat-client/src/client/chat.test.ts
- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/contracts/telemetry.ts
- client/vscode/package.json
- client/vscode/src/chatActivation.ts
- package-lock.json
Currently chat client doesn't send a message notifying about copy to clipboard events. It only sends a telemetry message. If a chat client destination wants to listen for copy events and handle the events on their side, they need to listen to telemetry events rather than listening to a dedicated copy to clipboard event. 
Chat client now sends a dedicated `COPY_TO_CLIPBOARD` message alongside with the copy information so that destinations can now handle the case explicitly. 
- Tested using the updated sample extension, verified that the extension receives the event when `copy to clipboard` is clicked on the chat UI
> Send copy to clipboard message from the chat client

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
In https://github.com/aws/language-servers/pull/499/files the dependency on @aws/chat-client-ui-types wasn't updated in aws-lsp-codewhisperer
And `^0.0.6` cannot be resolved to `0.0.7` because in semantic versioning it's a major version bump. That is because a major version is the leftmost non-zero number. 
Updating the dependency to 0.0.7
> Update @aws/chat-client-ui-types to 0.0.7

- package-lock.json
- server/aws-lsp-codewhisperer/CHANGELOG.md
- server/aws-lsp-codewhisperer/package.json
Releasing @aws/lsp-codewhisperer@0.0.16
- Amazon Q Inline Code Completions: The server now supports all languages supported by Q, including `go`, `php`, `rust`, `kotlin`, `terraform`, `ruby`, `shell`, `scala`
- Amazon Q Inline Code Completions and Q Chat:  Extend Chat and Completion Telemetry with Customization (#493).
- .Net Transform: Transform result is moved to the artifact location (#495).
> Bump lsp-codewhisperer version to 0.0.16

- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.ts
- server/aws-lsp-identity/src/sso/cache/index.ts
- server/aws-lsp-identity/src/sso/cache/ssoCache.ts
Adds cache for client registration and sso token files stored in $USER/.aws/sso/cache.  Leverages existing smithy-type and AWS SDK for JavaScript code where possible.
ssoCache.ts contains the cache interface along with a few supporting classes (SSOToken is reused from smithy-types, SsoClientRegistration added here in similar manner).  
FileSystemSsoCache is implementation for standalone runtime.  If an when webworker runtime needs an SsoCache, the interface can be implemented for it at that time (e.g. BrowserStorageSsoCache).
The cache is very basic, it just gets and sets the sso tokens and client registrations.  As it is a cache, it tends to swallow many errors so as to just allow the object to be recreated and not break the user experience.  For sso tokens, they will expire each hour, …
> Add cache for client registration and sso token

- server/aws-lsp-codewhisperer/src/language-server/netTransform/resources/SupportedProjects.ts
- ASPNet Webforms is not a supported project type.
- Remove ASPNet Webforms from supported project types.
> remove webforms from supported projects

- .github/dependabot.yml
The streaming client is not to be manually updated, this means any dependabot PRs pointing to that directory should be ignored. Currently we still get those PRs
There currently is no option to exclude the entire subdirectory from the scan, but there is a workaround to autoclose the PRs that only targets the streaming client https://github.com/dependabot/dependabot-core/issues/4364#issuecomment-2006542987. 
> Ignore streaming client from dependabot PRs

- .github/dependabot.yml
The streaming client is not to be manually updated, this means any dependabot PRs pointing to that directory should be ignored. Currently we still get those PRs
Simple version of https://github.com/aws/language-servers/pull/507
> Ignore streaming client dependency update

- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
Service definition .json file for bearer-token based Amazon Q server is outdated
* Updated service definition and generated Typescript definition file using script from VSCode Toolkit https://github.com/aws/aws-toolkit-vscode/blob/1ca150164b6a88be6130d09876433b7330b4f1de/CONTRIBUTING.md#aws-sdk-generator
* Tested that Amazon Q server compiles and InlineCompletions and Chat work with updated client
> Amazon Q Server: Update service definition and types for bearer token service client

- .vscode/tasks.json
- client/vscode/src/chatActivation.ts
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/clientTelemetry.ts
- server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.test.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.ts
Currently the chat server is not capable of handling insertToCursor position event. With the recent addition of `applyWorkspaceEdit` functionality to the runtimes (https://github.com/aws/language-server-runtimes/pull/233) the server becomes capable of handling the event. This PR enables the chat server to handle `insertToCursorPosition` event
This PR accommodates for existing usages of the chat server and won't cause breaking changes for existing destinations
In addition: 
- Updated the sample extension to test the server handling the insert event 
- Minor: Updated `cSharpDependencyGraph` test file to prevent the tests from breaking whenever there are changes to the runtimes package
- Minor: Also updated the tasks.json file: removed unused task and removed the label from compile task …
> Handle insertToCursorPosition event in the chat server

- .vscode/launch.json
- client/vscode/src/identityActivation.ts
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/identityService.test.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.test.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.ts
- server/aws-lsp-identity/src/sso/cache/ssoCache.ts
- server/aws-lsp-identity/src/sso/utils.test.ts
- server/aws-lsp-identity/src/sso/utils.ts
This PR adds InvalidateSsoToken to IdentityServer and IdentityService.  
SsoCache.removeSsoToken was added so that the SSO token cache file in ~/.aws/sso/cache could be deleted.  While passing null/undefined to the existing SsoCache.setSsoToken could've been used to perform the same function, a separate function name was chosen to make intent clear and avoid silent bugs where the SSO token should've been set, but was actually null/undefined.
tryAsync has been removed and replaced by idiomatic use of Promise.catch to perform the same function without an extra dependency.
identityActivation.ts in vscode sample client updated for purposes of validating InvalidateSsoToken during development.
> Add InvalidateSsoToken and convert tryAsync to catch

- chat-client/package.json
- package-lock.json
chat-client still depended on @aws/language-server-runtimes-types@0.0.6
updated the dependency to 0.0.7
> Update @aws/language-server-runtimes-types dependency to 0.0.7

- server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.test.ts
Changes introduced in https://github.com/aws/language-servers/pull/535 caused test builds to start failing. Reverting the changes in order to unblock builds
> Revert cSharpDependencyGraph unit test changes

- client/vscode/src/identityActivation.ts
- server/aws-lsp-identity/src/sharedConfig/saveSharedConfigFile.test.ts
- server/aws-lsp-identity/src/sharedConfig/saveSharedConfigFile.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.ts
This PR fixes error on file write when the file and/or directory does not exist.  identityActiviation.ts updated only for the purposes of developing/verifying fixes.  Unit tests added for build-time validation.  
1. Majority of saveSharedConfig file was just wrapping the readFile followed by a large for-loop in a filepathExists check.  The for-loop was not changed otherwise.  
2. No longer swallowing error in fileSystemSsoCache.writeSsoObjectToFile, ensuring directory exists and errors will bubble up to caller now.
> Fix file does not exist bugs and add tests

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codePercentage.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codePercentage.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/types.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
We need to emit CodeCoverageEvent telemetry to Amazon Q SendTelemetry API.
* Added new `emitCodeCoverageEvent` method to `TeleetryService`
* Extended `CodePercentageTracker` to track customization used and call `emitCodeCoverageEvent` at scheduled time
* Extended unit tests to cover new methods
* Bug fix: in existing telemetry sent over LSP channel, we used `codewhispererAcceptedTokens` to send length of all accepted recommendations. Per reference implementation in VSCode, we should use `codewhispererSuggestedTokens` for this. Switched to using `codewhispererSuggestedTokens` for this event
Reference implementation https://github.com/aws/aws-toolkit-vscode/blob/6c420c7f8c2f03fc1c6236669d701b2581cba6e0/packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts#L132-L146. …
> Amazon Q: Emit CodeCoverageEvent to CodeWhisperer.SendTelemetryEvent API

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/csharpDependencyGraph.test.ts
- server/aws-lsp-codewhisperer/src/language-server/dependencyGraph/dependencyGraph.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
Currently, in the standalone Workspace file system, there are some unreasonable default options passed to the Node.js fs functions, which can be confusing to the developers and produce unexpected results.
Updated interface in the language-server-runtimes repo: https://github.com/aws/language-server-runtimes/pull/247. 
Applied the necessary changes in the language servers to use the modified workspace interface.
> Update workspace fs interface to use expected defaults

- server/aws-lsp-codewhisperer/src/client/streamingClient/codewhispererStreamingClient.ts
- server/aws-lsp-codewhisperer/src/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
Making AWS Q endpoint url configurable. 
When `AWS_Q_ENDPOINT_URL` is set, sdk clients will use it instead of the default endpoint. 
The SDK clients will also honour `AWS_Q_REGION` but if the endpoint url already contains a region then it will be ignored based on my observations which is the desired behaviour. 
> Make AWS Q endpoint url configurable

- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
Condition in `TelemetryService.shouldSendTelemetry` uses flag value computed at object creating time in constructor using values from `CredentialsProvider`. Tokens and metadata in `CredentialsProvider` may be not available at Language Server starttime, or can change in runtime, which results in `shouldSendTelemetry` value being computed incorrectly.
When language server starts, it does not have credentials set by client, which results in `shouldSendTelemetry` always being falsy and not sending telemetry.
Calculate `ssoConnectionType` on each `sentTelemetryEvent` invocation to use up to date data from `CredentialsProvider`
> [Amazon Q] TelemetryService bugfix: recalculate connetionType in shouldSendTelemetry event from credentialsProvider at invocation

- .vscode/launch.json
- .vscode/tasks.json
- app/aws-lsp-identity-runtimes/src/standalone.ts
- client/vscode/src/identityActivation.ts
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/identityService.test.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.test.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.test.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.ts
- server/aws-lsp-identity/src/language-server/ssoTokenAutoRefresher.test.ts
- server/aws-lsp-identity/src/language-server/ssoTokenAutoRefresher.ts
- server/aws-lsp-identity/src/language-server/utils.test.ts
- server/aws-lsp-identity/src/language-server/utils.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.test.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationServer.test.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationServer.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/resources/auth.css
- server/aws-lsp-identity/src/sso/authorizationCodePkce/resources/index.html
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.ts
- server/aws-lsp-identity/src/sso/utils.ts
identityActivation.ts only contains changes for validating during development.
Removed potential PII from error messages created by identity server.
ensureSsoAccountAccessScope added to ensure that sso:account:access scope is added to scopes if it doesn't exist before calls to registerClient and createToken.
Observability interface added that holds references to logging and telemetry features currently.  An instance of observability is plumbed through all aws-lsp-identity classes/functions that can emit logging/telemetry.  Actual log/emitMetric calls will be added in an upcoming PR.
Added a ServerBase and supporting types in language-server/utils.ts for making IdentityServer and future servers easier to write.
IdentityServer updated to be class extending ServerBase, IdentityServerFactory …
> Bug fixes and preparing for observability additions

- package.json
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/identityService.test.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.test.ts
- server/aws-lsp-identity/src/language-server/profiles/profileService.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.test.ts
- server/aws-lsp-identity/src/language-server/profiles/sharedConfigProfileStore.ts
- server/aws-lsp-identity/src/language-server/ssoTokenAutoRefresher.test.ts
- server/aws-lsp-identity/src/language-server/ssoTokenAutoRefresher.ts
- server/aws-lsp-identity/src/language-server/utils.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.test.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationServer.test.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationServer.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/fileSystemSsoCache.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.ts
Added logging throughout the aws-lsp-identity server.
Moved a couple of functions to methods in fileSystemSsoCache.ts to make logging easier.  These functions did not need to be separate as they're used exclusively by the FileSystemSsoCache class.
> Add logging to identity server

- server/aws-lsp-codewhisperer/src/language-server/netTransform/converter.ts
The converter for .NET transformation currently does not support .NET 9 as an option.
A one-line addition to the `targetFrameworkMap` has been made that adds .NET 9 as an option for transformation.
> Add 'net9.0' to target framework map

- server/aws-lsp-codewhisperer/src/language-server/netTransform/converter.ts
The converter for .NET transformation currently does not support .NET Standard 2.0 as an option.
A one-line addition to the `targetFrameworkMap` has been made that adds .NET Standard 2.0 as an option for transformation.
> Add 'netstandard2.0' to target framework map

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
```[build:types] src/runtimeConfig.ts(41,14): error TS2742: The inferred type of 'getRuntimeConfig' cannot be named without a reference to '@smithy/node-http-handler/node_modules/@smithy/protocol-http'. This is likely not portable. A type annotation is necessary.```
Ensure the same version for `@smithy/node-http-handler`. Based on https://stackoverflow.com/questions/63806168/need-help-fixing-or-suppressing-this-typescript-error-ts2742
> Fixed build in another dependent environment for error TS2742

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
Add logging support for error in case of failures from Send Telemetry Event API call. 
The approach applies the same method of handling error as has been done for vscode. Reference: [link](https://github.com/aws/aws-toolkit-vscode/blob/77bd8a75539c7b1b7ba3c6489861babe4a986753/packages/core/src/codewhispererChat/controllers/chat/telemetryHelper.ts#L342)
It logs an error message with the requestId, if the error is of the type of AWS Error. 
> Add logging support in case of failures from STE call

- .vscode/launch.json
- package-lock.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-identity/src/sso/utils.ts
Added HTTPS proxy to SSO OIDC client for identity server when HTTPS_PROXY is passed.  Optionally, AWS_CA_BUNDLE can be passed as well.  This is based on:
1. https://github.com/aws/language-servers/blob/main/server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
1. https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html
1. https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrate-client-constructors.html
> Add HTTPS proxying to identity server

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
HTTP proxy setup does not work for CodeWhisperer capabilities except Q Chat.
* Fixed bug in `httpOptions` AWS Configuration passed to `CodewhispererService` in `proxy-servers` versions of capabilities: proxy agent object was not passed in correct field expected (https://github.com/aws/language-servers/pull/579/files#diff-6f77316cd6785df25fcc13badc7a24b9fa77b4e594455d07011c4ccc817d0be2R25-R27)
* Switched to `hpagent` package for all proxies. `proxy-http-agent` that was used originally was also misconfigured - arguments passed were not in correct shape.
Tested with local proxy setup using Charles and Sample VSCode extension on my Macbook. Verified that with setting `HTTPS_PROXY` and `AWS_CA_BUNDLE` in https://github.com/aws/language-servers/blob/main/.vscode/launch.json#L90-L91 result in …
> Amazon Q: fix proxy server configuration

- server/aws-lsp-codewhisperer/src.gen/@amzn/codewhisperer-streaming/src/runtimeConfig.ts
The function not having a return type was causing problems
Let's add any as a return type to suppress the problems
> Add return type to getRuntimeConfig function definition

- client/vscode/src/notificationActivation.ts
This was causing build problems, because `notificationFollowupRequestType` is defined as a `ProtocolNotificationType` we shouldn't use `sendRequest` but rather use `sendNotification` when sending it 
` const notificationFollowupRequestType: ProtocolNotificationType<NotificationFollowupParams, void>;`
Change `sendRequest` to `sendNotification` 
> Change sendRequest to sendNotification in the notification sample

- client/vscode/src/notificationActivation.ts
Temporarily disabling the notification sample extension because it is causing issues when building against latest runtimes which has updated parameter structure for notifications
> Temporarily disable the notification sample extension

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
The version bump is causing problems with builds
Revert the version bump to fix builds
> Downgrade @smithy/node-http-handler to 2.5.0

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts
This PR trims logs that don't add value to customer experience.
1. The response Json string from PollTransform and GetTransform endpoints
2. The duplicate logging for sending API request
Example of updated log
During the planning:
```
Info: [2024-11-08T01:14:02.911Z] Received transformation job Id: 63f66812-eb87-458a-8f89-f043eb2ebd9c
Info: [2024-11-08T01:14:08.797Z] aws/qNetTransform/pollTransformForPlan
Info: [2024-11-08T01:14:09.147Z] Start polling for transformation plan.
Info: [2024-11-08T01:14:09.147Z] The valid status to exit polling are: COMPLETED,PARTIALLY_COMPLETED,PLANNED,TRANSFORMING,TRANSFORMED
Info: [2024-11-08T01:14:09.148Z] The failure status are: FAILED,STOPPING,STOPPED,REJECTED
Info: [2024-11-08T01:14:09.148Z] Transformation status: ACCEPTED
Info: …
```
> Trimming logs to not show steps

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
We need to give customers control of whether they want to transform their .NET Standard projects.
We pass a flag from the UI and write it to the requirement.json so the CLI in the service backend will know whether to leave .NET Standard projects or try to transform.
Test older IDE UI code against LSP changes and verified no exception when flag is not passed in the request.
> Pass .NET Standard flag to requirement.json

- client/vscode/package.json
- client/vscode/src/activation.ts
- client/vscode/src/chatActivation.ts
- client/vscode/src/inlineCompletionActivation.ts
Chat integration in sample VSCode extension does not pass active text document as context for requests. We can't fully test context collection in Language Servers.
Add active text document or first visible non-log document as parameter for chat prompt requests from the client VSCode extension.
> VSCode Client: attach textDocument context to chat requests

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
Reference: https://issues.amazon.com/issues/AWS-Cloud9-28845
The PR aims to initialize proxy settings in Code Whisperer base class rather than fetching the value passed from constructor. 
- The PR loads the proxy configurations from the code whisperer base class and sets the proxy configurations once the client is initialized. 
- The PR also contains the requisite changes to update the client specific AWS configuration, rather than loading global configurations. 
- Other servers which were using CodeWhispererServer/IAM - TokenProxy now no need to pass this proxy configuration in the constructor.
- The above changes have been tested on local environment. 
> Load proxy configurations in code whisperer base class

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codePercentage.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codePercentage.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/userTriggerDecision.test.ts
* CodePercentage is emitted with 0 values when there were failed calls to service API. Expected behaviour - it should not emit telemetry
* When returned suggestion is right-merged with document content, it sometimes resulted in incorrect calculation of accepted token count being more than total document changes.
* CodeCoverage event calculation is not in sync with VSCode implementation. Up to date implementation is in https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core/src/codewhisperer/tracker/codewhispererCodeCoverageTracker.ts and it contains next changes:
* New line characters inputs are treated as 1 character
* Whitespace-only changes are ignored
* Inserts over 50 characters are ignored
Port logic from https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core …
> Amazon Q: port logic for CodePercentage modifications calculation

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
* Add GetSsoTokenResult.updateCredentialsParams to avoid decrypt/recrtyt in destinations #603
* Update @aws/language-server-runtimes to 0.2.26 
* Ref PR : https://github.com/aws/language-servers/pull/603/files
> Update @aws/language-server-runtimes to 0.2.26 and Add GetSsoTokenResult.updateCredentialsParams to avoid decrypt/recrtyt in destinations

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
Updating the language-server-runtimes dependency to 0.2.27
> Bump language-server-runtimes dependency to 0.2.27

- client/vscode/src/activation.ts
- client/vscode/src/notificationActivation.ts
- server/aws-lsp-notification/src/language-server/notificationServer.ts
- server/aws-lsp-notification/src/language-server/notificationService.ts
Test notifications routing logic with real client.
Related change: https://github.com/aws/language-server-runtimes/pull/259
> Testing notifications routing with test vscode client

- .vscode/launch.json
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/language-server/ssoTokenAutoRefresher.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.test.ts
- server/aws-lsp-identity/src/sso/cache/refreshingSsoCache.ts
The token would not be refreshed after the stored expirationAt date in the cached file.  This date was always an hour after the call to createToken to get a new access token.  The expected behavior is if you have a refreshToken, try to use it and you will either get a new accessToken or an error if the session has expired.
The code in refreshingSsoCache was updated to reflect the expected behavior.
https://docs.aws.amazon.com/sdkref/latest/guide/understanding-sso.html#idccredres3
> Fixes early SSO token expiration bug.

- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.test.ts
error TS2454: Variable 'telemetryService' is used before being assigned.
Use stub instead of unassigned variable.
> Fix issue with telemetryService used before defined

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
node `fs` is used to read proxy configurations. This results in webpack bundling to fail since it's not available in browser
Use the `workspace.fs` feature injected from runtimes instead
- Inject workspace to server creation
- Create mock `workspace` for tests
Note: to be tested in local
> Inject fs feature for reading proxy configs

- .github/workflows/new_pr.yml
Currently, steps for dependabot PRs are failing
Do not push slack notifications for dependabot PRs.
> Skip publishing Slack notification for Dependabot PRs

- .github/dependabot.yml
Major version bumps on `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` cannot happen separately as they come from the same parent package and share common peer dependencies. We can make dependabot group these dependencies so that both versions gets updated in 
See recent update attempt on `@typescript-eslint/parser` failing: https://github.com/aws/language-servers/pull/643
Also see 4 month period in the past where dependabot was constantly trying to bump typescript-eslint dependencies:
> chore: update dependabot config to group @typescript-eslint dependencies

- .github/dependabot.yml
We want dependabot to ignore the streaming client and not publish PRs for the streaming client but it is still creating PRs for it (see latest PR by dependabot https://github.com/aws/language-servers/pull/657) Putting `*` in the ignore clause doesn't seem to ignore the whole package so let's try ignoring every dependency explicitly 
> chore: Update dependabot to ignore all dependencies of streaming client

- .commitlintrc
- .husky/commit-msg
- .husky/pre-commit
- .husky/pre-push
- CONTRIBUTING.md
- package-lock.json
- package.json
Commits contributed to main branch lack standard format, which makes collecting change logs and analyzing their impact for Semantic Versioning difficult.
Add configuration to enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification when creating commits during local development.
* Install [`commitlint`](https://github.com/conventional-changelog/commitlint) and setup initial minimal configuration for commit messages.
* Setup `pre-commit` git hook to run `commitlint` check when commit is created locally.
* Updated CONTRIBUTION.md doc with overview of Conventional Commits and types and scopes, supported in Language Servers monorepo.
This is initial setup, and it can be extended to support more scope or packages easily.
By submitting this pull request, I …
> chore: setup conventional commit linting rules

- .github/dependabot.yml
- package-lock.json
PRs created by Dependabot do not follow Conventional Commit spec by default.
Configure Dependabot to use Conventional Commit.
> chore: set dependabot to use conventional commit

- CONTRIBUTING.md
- chat-client/CHANGELOG.md
- chat-client/package.json
- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- chat-client/src/client/texts/disclaimer.ts
- client/vscode/package.json
- client/vscode/src/chatActivation.ts
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
Currently, we show long disclaimer on the bottom of chat: [source](https://github.com/aws/language-servers/blob/main/chat-client/src/client/chat.ts#L51). This needs to move to promptInputStickyCard with "Acknowledge" button in every active or newly added tab, until user clicks that "Acknowledge" button. When user hits that, it should disappear from all the tabs and shouldn't be visible ever again.
- Shortened the legal disclaimer in the footer (always visible)
- Added `disclaimerAcknowledged` event to `OutboundChatApi` (`DISCLAIMER_ACKNOWLEDGED` has been added to the contract in `language-server-runtimes`, will be available through NPM once a new release is made there)
- Extended the ChatClientConfig by a boolean flag `disclaimerAcknowledged`
By submitting this pull request, I confirm …
> feat(chat-client)!: add legal disclaimer with acknowledgement button

- release-please-config.json
Release-please automation use `bootstrap-sha` value to mark starting point for the automation to work. Merged commit was already released.
Move bootstrap-sha to latest merged commit in main.
> chore: move starting commit for release-please to latest commit

- chat-client/package.json
- package-lock.json
Stop using versions marked as `0.0.x` and start using version `0.1.0`
> chore(chat-client): bump chat client ui types dependency

- app/aws-lsp-yaml-json-webworker/package.json
- core/codewhisperer-streaming/package.json
- package-lock.json
- package.json
* Streaming client dependabot PRs must not be merged 
* Reverting last 2 commits updating dependabot changes 
> fix: revert dependabot updates for streaming client

- .husky/pre-push
If conventional commits through git hooks were ignored (with `--no-verify`), then pushing to remote will still succeed. Let's add an additional layer to it.
Add commitlint command to the prepush script
> chore: add commit linting to prepush hook

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
Adds the ability to handle virtual spaces to chat server
> feat: handle virtual spaces when inserting code to cursor position

- chat-client/README.md
No information about how to use the chat-client.
Extended README with chat-client events and configuration.
> chore(chat-client): extend chat client README with list of events supported and config

- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
When running `npm run test` in `server/aws-lsp-codewhisperer`, all tests pass but the test task does not finish/close because we forgot to dispose some resources we created, in particular it's about the `chatController` object.
Dispose via` chatController.dispose()`
> perf: dispose chat controller in chatController tests

- server/aws-lsp-codewhisperer/src/client/streamingClient/codewhispererStreamingClient.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
**this is a short term fix, to fix the webworker bundling. We will implement a better solution very soon.**  
We want to avoid having nodejs specific logic (process.env.VARIABLE) in lsp-codewhisperer as it breaks the webworker bundling, for which `process` is not defined.
If/else check to see if we are in node.js env
I tested the changes by testing the proxy
> fix: make proxy nodejs specific logic available only for nodejs runtime

- server/aws-lsp-codewhisperer/src/client/streamingClient/codewhispererStreamingClient.ts
- server/aws-lsp-codewhisperer/src/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/transformHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
Inject AWS_Q_REGION and AWS_Q_ENDPOINT_URL env variables via runtime to avoid having node.js specific logic (i.e. process.env.VARIABLE) in lsp-codewhisperer.
Inject the variables via runtime. The variables are pass down to the services via constructor, passing them down via setters/update function can leave room for errors, where the variables are passed via env, we forget to call those setters, and the values are set to the default value unintentionally.
**Some tests are currently failing due to the changes, once my approach is validated I will fix them.** 
I manually tested the following scenarios only via the token vscode client:
- Env variables are not set - inline suggestion and chat should work (using default values)
- Env variables are set to wrong values, inline suggestion and …
> refactor:  inject AWS_Q_REGION and AWS_Q_ENDPOINT_URL env variables via runtime

- release-please-config.json
Due to the empty commits we made last week, release please now tries to make a version bump on every subpackage. 
By changing the inception commit of release-please I am aiming to fix the wrong release created by release please and have release please only release actually changed subpackages.
> chore: change release-please manifest to fix false major version bumps

- server/aws-lsp-codewhisperer/.eslintrc.js
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanDiagnosticsProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codePercentage.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetryService.ts
Related to the bug: https://github.com/aws/language-servers/pull/725
Enable [`@typescript-eslint/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises/) to catch similar cases in the future.
You can see, given the fix has not been merged yet, the build is failing: https://github.com/aws/language-servers/actions/runs/12808835517/job/35712403951?pr=728
> chore: eslint config to catch floating-promises

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
V1642391964
Currently when we are packaging artifacts.zip on the IDE, the nuget packages are part of 
1. default "packages" folder in the root solution/ source Code
2. newly created the references folder in artifactsWorkspace. 
This is causing increased artifacts size.
we are not using packages folder from sourceCode for transformations in Qnet CLI, we are only using nuget packages from references folder. 
So we can safely delete packages folder before zipping to save on space.
Simple example on saving space is 
Sample applications - Bobs Bookstore
Size of packages folder - 241MB
size of Artifacts zip BEFORE below changes of deduping - 179 MB
size of Artifacts zip AFTER below changes of deduping - 89 MB
we are saving almost 45% space in artifacts zipping and thereby for uploads. This will …
> fix: removing duplicated nuget packages folder

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/transformHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
Node limit for 2 GiB for fs.readFile .  ‘File size is greater than 2 GiB’ is common error in node with fs.readFile. 
Reference https://github.com/nodejs/node/issues/55864 
We are using fs.readFile in 3 places in language server code. 
use fs.createReadStream instead.
> feat: bugfix for artifacts upload

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
This reverts commit 8634490f588558f30ebcd3b72660ea5ab1c2e451.
The dependabot update brought in dependencies without pre approved licenses, reverting it for quick fix.
Revert. 
> fix: revert "chore: bump archiver from 6.0.2 to 7.0.1"

- .github/workflows/lsp-ci.yaml
- server/aws-lsp-codewhisperer/src/client/sigv4/codewhisperersigv4client.d.ts
- server/aws-lsp-codewhisperer/src/client/sigv4/service.json
The codewhisperer sigv4 client is out of date and doesn't include `supplementalContext`. 
Generated the client from the latest model from the [aws-toolkit-vscode](https://github.com/aws/aws-toolkit-vscode/blob/3a03e95599e5254341ee4e8acae6c39bdeee70a8/packages/core/src/codewhisperer/client/service-2.json)
> chore: update the generated codewhisperer sigv4 client

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/transformHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- CodeFIles list is missing from Requirements.json. 
- Requirements.json gets created as artifact when user starts transformation
Some changes with PR https://github.com/aws/language-servers/pull/749 introduced delays in writing codeFiles list to requirements.json
We do not need codeFiles from requirements.json for transformation job but it is needed for summary generation. 
On IDE, this summary is parsed to update counts, diffs for file changes
This reverts commit 71c0a19974428037160152cc7e40cd6c399ceec9. 
Verified that after reverting this commit, we could get successfully .bak files in view diff screen
failing test CI job does not seem to be connected with nettransform. will connect with flare team for more guidance on it. 
when I run ```npm run test``` locally, gave me all successful …
> Revert "feat: bugfix for artifacts upload (#749)"

- .github/workflows/new_pr.yml
Messages to Slack were being sent through the GitHub CI workflow, even for Draft PRs.
Filter to just run on non-draft PRs.
> ci: don't send slack messages for new prs in draft mode

- server/aws-lsp-codewhisperer/src/language-server/utilities/supplementalContextUtil/crossFileContextUtil.ts
Windows tests are failing (because of [breaking github action env. changes](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/))
Updated the tests to create a proper fileURL from any file uri.
> chore: fix failing tests for windows github actions

- CONTRIBUTING.md
add documentation for region and endpoint override
Check how is rendered here: https://github.com/aws/language-servers/blob/frapicc/region-and-endpoint-override-doc/CONTRIBUTING.md#endpoint-and-region-override
> docs: add documentation for region and endpoint override

- core/aws-lsp-core/src/language-service/serverBase.ts
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-notification/src/language-server/notificationServer.ts
- server/aws-lsp-notification/src/notifications/toolkits/criteriaFilteringFetcher.ts
`initialize` method on ServerBase was not async and required implementations to handle catching errors and returning to meet the LSP return type of `HandlerResult<..., InitializeError>`.
Other changes:
* Added ServerState enum to ServerBase to support NotificationsServer
* Cleaned up showNotification impl in NotificationServer
* Fixed typo in CriteriaFilteringFetcher
Simplified implementation of `initialize` method so error handling isn't necessary (handled by wrapper in ServerBase) and async code in initialize is now possible.  Updated IdentityServer for the initialize function declaration change.
Tested with `npm run test` and using vscode sample client IdentityServer function to see various identity server functions called/return values.
By submitting this pull request, I confirm that …
> refactor: simplify initialize overrides in ServerBase and servers extending it

- release-please-config.json
Release Pull Requests managed by release-please do not trigger Github Actions automatically, blocking releases. 
This is caused by using default `GITHUB_TOKEN` in release-please Action:
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
There are several workarounds to this issue. The easiest and more straightforward is to mark Release-Please Pull Requests as draft, and require person to move PR to "Open" state. When done by human, Github Actions will start as usual.
Other possible workaround include using managed PAT, manually force-pushing something to release PR or closing and re-opening PR immediately by human. I prefer to try Draft …
> ci: open release-please pull requests as draft

- release-please-config.json
Release Please PRs created by bot don't trigger GitHub workflows. Using draft PRs doesn't solve the issue - PR should be submitted by human to trigger GitHub checks on PR.
Adding a message to release please PR footer with instructions on how to workaround the problem.
> ci: update release-please PR footer with troubleshooting information

- server/aws-lsp-codewhisperer/.npmignore
`*.test.*` files are included in the `@aws/lsp-codewhisperer` npm package.
Updated `.npmignore` to exclude test files.
Impact:
* Removed 96 unnecessary files
* Reduced package size by 84.9kB
* Reduced unpacked size by 0.6MB
> chore: ignore test files in the lsp cw package

- CONTRIBUTING.md
- client/vscode/src/activation.ts
Remove `--preserve-symlinks` option from nodejs debugger, so that we can set breakpoints directly in the packages in monorepo and not from the relative symlinked path under `node_modules` folder.
There's no specific reason we need to use the `--preserve-symlinks` option and it's easier and more natural to set breakpoints in the packages in the monorepo.
> chore: remove preserve--symlink from nodejs debugger option

- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.ts
`codeDiffTracker.ts` uses NodeJS-spicific API - [Timeout->refresh()](https://nodejs.org/api/timers.html#timeoutrefresh) which doesn't exist in the browser. 
In the browser [`setInterval()` return a numeric `intervalID`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval#return_value) instead of a `Timeout` and calling refresh on it causes a runtime exception. 
The `codeDiffTracker` uses the `Timeout->refresh()` API to ensure that the delay between execution will start only after the metrics have been flushed. 
This can be easily achieved in a cross-platform manner by using a recursive timeout instead of the `setInterval` + `Timeout.refresh()`. 
https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval#ensure_that_execution_duration_is_shorter_than_interval_freque …
> fix: replace setInterval with recursive setTimeout for browser compatibility

- app/aws-lsp-codewhisperer-runtimes/README.md
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/webpack.config.js
- package-lock.json
Update in https://github.com/aws/language-server-runtimes/pull/335 will fail the build, as it introduces `.node` static files as part dependencies of standalone runtime.
Configure webpack to load `.node` files correctly at `build` directory.
> build: update bundling of Codewhisperer language server

- .vscode/launch.json
- client/vscode/src/activation.ts
- client/vscode/src/credentialsActivation.ts
VSCode sample client works only with encrypted connection to Language Server runtime.
Allow to start unencrypted connection, controlled with `ENABLE_ENCRYPTION` env variable.
> chore: add options to start VSCode client with unencrypted connection

- package-lock.json
- package.json
manual update the version of commitlint/cli and commitlint/config-conventional to 19.8.0 as dependabot by default open 5 PRs at max and 19.8.0 version is available in language-server-runtimes.
> chore: update the version of commitlint/cli and commitlint/config-conventional to 19.8.0

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/src/iam-webworker.ts
- app/aws-lsp-codewhisperer-runtimes/webpack.config.js
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
We want to check whether webworker bundling of lsp-codewhisperer iam fails at compile time to prevent breaking it without noticing it. The `package` github action which runs npm run package (which does the bundling) will fail if webworker bundling fails.  
**Note**: The second commit is to prove the failing of the github action, I will revert it before merging.
add a new config for webworker iam and add new config in webpack config file
> feat(aws-lsp-codewhisperer-runtimes): add webworker iam bundling

- client/vscode/src/activation.ts
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/qDeveloperProfiles.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
Currently, we have functionality for fetching and returning Q developer profiles, but by default we have it disabled. Instead, iff the client signals support for Q developer profiles, we should return them in the applicable `GetConfigurationFromServer` requests (`aws.q`, `aws.q.developerProfiles`)
At initialization, we check the `AWSInitializationOptions` in `InitializationParams` for the structure:
```
q: {
developerProfiles: boolean;
}
```
If these params are present, and the `developerProfiles` flag is explicitly set to true, we update the corresponding flag in `ServerConfigProvider`, which then in turn enables fetching and returning the Q developer profiles.
Testing: added unit tests that verify the flag-checking mechanism, as well as the initialize handler correctly setting the …
> feat(amazonq): handle client signalling support for q developer profiles

- server/aws-lsp-codewhisperer/README.md
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
The `aws.q` section was recently extended with `aws.q.developerProfiles`, which is currently also not enabled by default. It would be useful to have some usage examples on how to fetch these configurations with the `aws/getConfigurationFromServer` request
Added context and examples to README.md
Testing: built-in vs code README viewer.
- also removed a missed "WIP comment" in `qConfigurationServer.ts`
> docs(amazonq): add docs to README for aws/getConfigurationFromServer request

- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/src/token-standalone.ts
- client/vscode/src/identityActivation.ts
- package-lock.json
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/identityService.test.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.test.ts
- server/aws-lsp-identity/src/sso/authorizationCodePkce/authorizationCodePkceFlow.ts
- server/aws-lsp-identity/src/sso/deviceCode/deviceCodeFlow.test.ts
- Add device code as selectable auth flow
- Refactor PKCE flow to use params structure
- Add IdentityServer to cw lsp activation and update version
- Add example message handlers in the sample vscode app
> feat(identity): enable device code

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/BaseAmazonQServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
Updating initialization flow for AmazonQTokenServiceManager:
1. Now it must be initialized in consuming Server inside as part of `lsp.onInitialized` handler, to ensure that LSP connection was initialized and `InitializeParams` are cached in `lsp` feature.
2. Reading `q. developerProfiles` initialization option from cached `InitializeParams` to toggle Developer Profiles support in manager instead of passing a flag. 
3. Computing `customUserAgent` from cached `InitializeParams` instead of using setter in consuming code.
> feat(amazonq): update initialization flow for AmazonQTokenServiceManager

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/qDeveloperProfiles.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/testUtils.ts
The Q Configuration server should use the correct regional endpoints for fetching customizations. When connection type is `builderId`, the region and endpoint should be discovered in the following order:
the region set by the client -> the region set in runtime -> the default region
In case of connection type being `identityCenter`, the region determined by the selected Q developer profile should be used instead
1. Use the new `AmazonQTokenServiceManager` and its cached codewhisperer service in `ServerConfigurationProvider`, which already handles the underlying connection type differentiation. This also allows us to remove the service factory.
2. Extend `AmazonQTokenServiceManager` to setup the cached codewhisperer service according to the aforementioned region discovery chain in case of …
> feat(amazonq): integrate q service manager with configuration server

- .github/workflows/new_pr.yml
The Slack notification workflow fails on PRs from forked repositories. These failures are false positives and create unnecessary noise in our CI pipeline.
Reason is that GitHub Secrets are not passed to the runner when a workflow is triggered from a forked repository, because of security reasons.
Disabling slack notification workflow for PRs coming from forks. We could think of some better solution that will work with forks in the future.
> fix: disable slack notifications for PRs from forks

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionManagementService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
We need to add regionalization support to Q Chat Server.
* Extend AmazonQTokenServiceManager to expose factory method to create instance of `CodeWhispererStreaming` client with currently active region and endpoint
* Integrate Q Chat server to use new method
* Remove obsolete configuration passed in various Q Chat server service classes.
> feat(amazonq): intergrate regionalization support into Q Chat server

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererService.ts
Many Codewhisperer APIs were extended with new optional `profileArn` field.
Attach new `profileArn` field to API calls which support it.
Tested by making API calls and looking at network proxy interceptor to make sure selected profileArn is attached.
> feat(amazonq): attach profileArn to API calls when available

- server/aws-lsp-codewhisperer/src/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransformServer.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.ts
The security scan server should use the correct region based on either the selected Q developer profile, or in case of the `builderID` connection type, use the correct region based on the expected discovery chain.
Integrate with the security scan server with the amazon q service manager, using only the codewhisperer client provided by this singleton. The service manager is setup to select the correct region based on the above mentioned requirements, so using this client ensures the security scan server meets the region selection requirements as well.
> feat(amazonq): add regionalization support to security scan server

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
The PR introduces changes to cancel in-flight update profile requests, so only the recent request is honored whereas the old request in progress gets cancelled. This is implemented using CancellationTokenSource, calling cancel() on the source instance changes the isCancellationRequested property of the token to true, hence enabling us to return an error for the old request.
> feat: Cancel inflight update requests

- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.test.ts
- server/aws-lsp-codewhisperer/src/language-server/telemetry/codeDiffTracker.ts
CodeDiffTracker does not await for recordMetric callback when it's async method, which may result in uncaughtRejection and crash node process.
Await for recordMetric call to catch rejections
> fix(amazonq): await for recordMetric in CodeDiff tracker

- client/vscode/package.json
- client/vscode/src/selectQProfileActivation.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/utils.ts
We received the request to support uninitialising profile selection in `updateConfiguration` by sending empty profile.
Instead of listening just for a `string` in `params.settings.profileArn`, we now also listen for `null`. When we receive `null`, the code whisperer service is reset and the state is set back to `PENDING_Q_PROFILE`.
Testing: 
- Added unit tests for transitions:
- `INITIALIZED` ->(null) `PENDING_Q_PROFILE`
- `PENDING_Q_PROFILE_UPDATE` ->(null) `PENDING_Q_PROFILE`
- Tested E2E flow with the bundled vs code client
Additional fixes:
- Added missing cancellation of on going profile updates when we receive credentials event
- Altered request cancellation handling to not restore state to avoid race conditions when e.g. cancellation is initiated by credential deletion or null.
By …
> feat(amazonq): add support for setting profile to null

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererSecurityScanServer.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/securityScan/securityScanHandler.ts
Q developer scans were failing to execute due to a couple of issues. This change adds fixes to address them.
Changes included:
* Scans were timing out due to a lower timeout limit. It has now been updated to 15mins matching other IDE's timeout limits for project scans. Reference [VSCode timeout](https://github.com/aws/aws-toolkit-vscode/blob/b048f97449b6265d97a51676acc3464aeefa4c06/packages/core/src/codewhisperer/models/constants.ts#L264)
* Missing parameters specifying the scope of the scan has now been added to the `UploadToS3` call and the `CreateScanJob` call of the scan process. At this time only `PROJECT` scope is supported. Support for file auto scans is out of scope. Reference [VSCode request](https://github.com/aws/aws-toolkit-vscode/blob/b048f97449b6265d97a51676acc3464aeefa4c06/p …
> fix(amazonq): specify code analysis scope and scan name when running scans

- server/aws-lsp-codewhisperer/src/constants.ts
Amazon Q launches support for new FRA region
Adding eu-central-1 endpoint to list of supported endpoints
> feat(amazonq): add eu-central-1 endpoint

- client/vscode/package.json
- server/aws-lsp-codewhisperer/README.md
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
In some use cases, the client has more information about the context in which the code is being edited. For example, when the editor is run in a web environment on a specific page. Then providing this additional information to Q improves quality of the suggestions. And without the context the recommendations can be barely useful, especially when editing an empty file. 
The additional information will be added to the file's left content of the request. If no extra context is passed, the left content is not modified.  
The extra context is passed to the server as workspace configuration under `aws.q.inlineSuggestions.extraContext`. 
Using the supplemental context field was considered, but it was later discovered that it's supported not for all languages. Thus, modifying the left content …
> feat(amazonq): accept extra context for Q Inline Suggestions

- server/aws-lsp-codewhisperer/src/language-server/chat/agents/docGeneration/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/agents/docGeneration/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/agents/shared/i18n.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/agents/shared/types.ts
Initial commit for doc migration to flare
Migrated from aws-toolkit-vscode commit: feat(amazonq): basic paginated suggestions using language server ([#6803](https://github.com/aws/aws-toolkit-vscode/issues/6803))
Basic paginated inline suggestions implementation using language server
(related: https://github.com/aws/language-servers/pull/831)
---
- Treat all work as PUBLIC. Private `feature/x` branches will not be
squash-merged at release time.
- Your code changes must meet the guidelines in
[CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#guidelines).
- License: I confirm that my contribution is made under the terms of the
Apache 2.0 license.e01574f3427de0bef053662707bd4cea95f8986f
Passed local build
By submitting this pull request, I confirm that …
> chore: migrate types constants and errors files for doc

- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
This change addresses a bug where full/absolute path of the active text document is being sent instead of the relative Path expected with a ChatPromptRequest. 
See [here for payload shape ](https://github.com/aws/language-servers/blob/ee04afc7775e83bfa3868b4b661cf59ff3c7f949/server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts#L54) which expects relativePath in the request.
Validated that chat can answer questions related to active file with this change
> fix(amazonq): use relative path of document with chat params

- server/aws-lsp-codewhisperer/src/language-server/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
Current switch between Q Service manager type in InlineCompletions server does not work in code bundled in production mode with webpack.
Use flag to explicitly set Service type for InlineCompletions server. This is temporary fix and will not be needed after refactoring in progress.
> fix(amazonq): select corrert Service manager mode in completion server factory

- release-please-config.json
New release-please PR included already released changes https://github.com/aws/language-servers/pull/880.
Apparently release-please looked back at the oldest release for 2 packages that didn't change and used that point in time to collect change log. This resulted in already release changes being processed again.
Move last release sha to previous release to skip released changes.
> ci: move release-please last release pointer commit

- app/aws-lsp-codewhisperer-runtimes/README.md
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/public/index.html
- app/aws-lsp-codewhisperer-runtimes/src/main.ts
- app/aws-lsp-codewhisperer-runtimes/src/mock-fs.js
- app/aws-lsp-codewhisperer-runtimes/tsconfig.json
- app/aws-lsp-codewhisperer-runtimes/webpack.config.js
- package-lock.json
We want to check whether webworker bundling of lsp-codewhisperer iam fails at **runtime** time to prevent breaking it without noticing it, we already check for build time issue (https://github.com/aws/language-servers/pull/833). 
In this PR we create the infrastructure needed to run the webworker on a webpage locally on browser with a webpack dev server. This is needed to then create tests to do the check to enforce a functioning server on browser before merging.
As this monorepo uses commonjs, i had to override as use es module is tsconfig, as commonjs is not compatible with browser.
tests PR: https://github.com/aws/language-servers/pull/887
Summary:
- Fix current bundling issues (mock-fs)
- Fix package to work on browser (tsconfig and webpack to use es module instead of commonjs)
- …
> feat: bundling and infra to deploy webworker in webpage on local webserver

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
bump runtimes and comply to new version of ChatHandlers protocol (see [PR](https://github.com/aws/language-server-runtimes/pull/391/files#diff-3b7ccc3150a65fa49ffbc0f6d5f2beb4a487251387f744a5a58a75768fde5de0R129)) by adding an empty implemenetation for the new `onInlineChatPrompt` in the classes using Chat.
> chore: bump runtimes version and add empty onInlineChatPrompt implementation

- server/aws-lsp-codewhisperer/src/language-server/amazonQServiceManager/AmazonQTokenServiceManager.ts
Logging in is AmazonQTokenServiceManager.ts noisy.
Switch noisy log to debug loglevel
> fix(amazonq): reduce noisy logging from Q Service Manager

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
Bump the version of runtimes to 0.2.52 to be able to populate the requestId in the InlineChat response structure for the [PR](https://github.com/aws/language-servers/pull/897)
> chore: bump the version of runtimes

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- chat-client/package.json
- chat-client/src/client/chat.test.ts
- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.ts
- client/vscode/package.json
- client/vscode/src/chatActivation.ts
- package-lock.json
- package.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
We need to support context commands sent from server to chat-client. This is expected to work through 'aws/chat/sendContextCommands' protocol.
- Upgrade to the latest "@aws/language-server-runtimes" package
- Show context commands as quick actions in chat client (available via `@`)
Tested with fake data:
> feat: context data selection support in chat-client

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/qChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
- server/aws-lsp-codewhisperer/src/language-server/proxy-server.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/BaseAmazonQServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/factories.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/factories.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
- server/aws-lsp-codewhisperer/src/shared/constants.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetry.test.ts
We currently need to maintain a fallback codewhisperer service in the inline completions server because it supports both token and iam credentials. Refactoring this server would enable us to optimize the reuse of the new amazon q service manager.
- Centralize workspace configurations within the service manager
- By adding the `getConfiguration(): Readonly<AWSQWorkspaceConfigs>` method to `BaseAmazonQServiceManager` we can refer to the up-to-date workspace configurations maintained within the service manager
- Introduce an `AWSQConfigurationCache` wrapper which orchestrates manipulation of the cached configuration within the service manager in a type-safe manner
- Factor our handling configuration update events to a reusable function
- Factor out region and endpoint discovery to reusable …
> feat(amazonq): optimize service manager reuse

- chat-client/src/client/chat.test.ts
- chat-client/src/client/mynahUi.ts
- package-lock.json
Q response can provide a context with file list. This feature is not available in chat client
Added the above to chat client
> feat: add context transparency feature

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/artifactManager.processPrivatePackages.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/mockData.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
Update artifact manager for qct .net to include private package support
ArtifactManager Updates:
- store core compatible assembly files in thirdpartypackages folder under references
- update the requirement.json created with relative path to files in the above folder.
Testing positive case, verify artifact.zip was created properly
example artifact.zip after change.
[artifact.zip](https://github.com/user-attachments/files/19558786/artifact.zip)
Also test negative case where PackageReferences not provided in the request, make sure requirement.json and artifact content still created properly.
> feat: update artifact manager for qct .net to include private package support

- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
Clients should be able to send null profile to server when client is not connected without receiving an error.
When connection type is `none`, only throw an error in `handleProfileChange` when profileArn is not null.
Testing: added new unit test and send a null profile in bundle client
> fix(amazonq): do not throw when receiving null profile while client not connected

- chat-client/package.json
- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/contracts/serverContracts.ts
- package-lock.json
Custom form needs to be supported in chat-client as a UI to create prompt files.
- If context item is selected with `'create-saved-prompt'` id, show the create prompt form
- If Submit button or corresponding "enter" key was pressed, send `createPrompt` request to extension/chat server.
> feat: support create prompt form in chat-client

- server/aws-lsp-codewhisperer/src/client/streamingClient/codewhispererStreamingClient.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.test.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
We need to cache the streaming client and be able to abort inflight requests on profile/connection changes.
- initialize the streaming client with a token provider function that invokes the credentials provider before each request
- Add a wrapper around the streaming client that stores the abort controllers of inflight requests, similar to the solution for the regular codewhisperer service
- This also allows us to add the active profile arn to incoming requests rather than making it the responsibility of the caller
Testing: new unit tests and validated chat still works in bundled minimial vs client.
> feat(amazonq): add streaming client caching and inflight-request cancellation

- chat-client/src/client/mynahUi.ts
Main branch is failing build caused by a compile error https://github.com/aws/language-servers/actions/runs/14333867432/job/40175897377.
This likely happened because the `onFileClick` property was implemented in two different commits (-([this](https://github.com/aws/language-servers/pull/919) and [this](https://github.com/aws/language-servers/commit/b95fe1e1a63f6df469bcd0c5e58a66c0819feb55#diff-b68ed2121e608d8cb0c35bb3021bfdc77a4fc0bd423d7b79cbead1e290c15300R32-R330)) and was not detected as a conflict by github.
Remove the duplicate property
> fix: remove duplicate property

- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
If an account that has more than one developer profile queries `aws.q.developerProfiles`, the response is a list containing the first profile ten times. A paginator is missing in the call to list all profiles.
Add the missing `nextToken` paginator.
> fix(amazonq): add missing paginator to list profiles call

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
The tests for executeBash currently mock the underlying process providing little confidence the flow works properly, as child processes can behave in unexpected ways on different OS. 
After removing the mocks for executeBash the tests still pass on windows. I suspect this is because Git for Windows includes Git Bash which includes `which` and other unix utilities. However, this may not be the case on customer machines.
- remove the mocks, and test the actual flow. 
- add proper windows support by using `where` instead since Node spawned processes [default to command prompt](https://nodejs.org/api/child_process.html#default-windows-shell), which supports `where` by default. 
> feat: add proper windows support for executeBash and remove mocks in tests.

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
The fsRead tool has had changes since https://github.com/aws/language-servers/pull/894 was merged. Additionally, the `validate` and `invoke` methods were combined previously, but have been separated here until the final implementation is more stable, and refactoring can be done with less churn. 
- sync up to https://github.com/aws/aws-toolkit-vscode/blob/8e00eefa33f4eee99eed162582c32c270e9e798e/packages/core/src/codewhispererChat/tools/fsRead.ts#L17
- add TODO comments as hints for where work is still needed to integrate the tool to mirror its VSC implementation. 
- add a test for working with the `queueDescription` function. 
> chore: sync fsRead with VSC branch. 

- chat-client/package.json
- chat-client/src/client/features/history.test.ts
- chat-client/src/client/features/history.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- package-lock.json
Some followup improvements needed: wrong history icon, unit tests missing
- Setting recent history icon
- Updating `mynah-ui` to latest that does not require setting empty `tabId`
- Added unit tests
> fix: replaced icon for history and added tests

- core/aws-lsp-core/package.json
- server/aws-lsp-codewhisperer/package.json
The new tests added recently in the recent PRs containing the ones defined in aws-lsp-codewhisperer and core packages, sometimes take more than 2s to execute (2s is the default mocha timeout). Tests taking more than 2s fails. 
Mocha has a default timeout of 2000ms per test case. Mocha provides us the capability to override this timeout value or even disable timeout when we provide 0 value to the timeout function. https://mochajs.org/#test-level
Raising this PR to disable the timeout for the mentioned sub folders above.
> fix: disable timeout for tests in aws-lsp-codewhisperer and core sub-folders

- core/aws-lsp-core/src/util/processUtils.test.ts
This test is flaky and is failing CI on unrelated changes. Ex. https://github.com/aws/language-servers/actions/runs/14414451928/job/40491802663#step:5:1583
The cause is not immediately clear, and requires some investigation. Not able to reproduce locally by repeating the test suggesting it is related to either bleed-through from another test or a CI specific. 
- Skip the test to avoid blocking other work while root-sourcing the issue. 
- This test is non-critical, as it related to the child process logging functionality. 
- Follow up with a longer term fix and attempt to root cause the issue. 
> test: skip flaky child process tracker test

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
The test case fixed was failing in the internal pipeline as the response is expected to be different in case `ls` command is run against empty current working directory and on pipeline current working directory seems to be empty. Changed the test case to test the structure instead. `result.output.content.exitStatus` in case of ls on empty directory is not 0 but instead -2 and `result.output.content.stdout` is an empty string.
> fix: fix execute bash test command failing on pipeline

- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
There can be some latency while loading developer profiles, caused by either a poor internet connection, a sluggish backend, or both. Clients need a way to cancel the request for loading profiles.
Wire in support for the Cancellation Token.
This change is being done in tandem with VS Toolkit change https://github.com/aws/aws-toolkit-visual-studio-staging/pull/2443
> fix(amazonq): add cancel support to loading developer profiles

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
Add **onTabBarAction** and **getSerializedChat** to Omit list of Chat handlers so internal build do not fail. This is temporary and can be removed post actual implementation of the methods in both of these classes. 
> fix: add onTabBarAction and getSerializedChat to Omit list of Chat handlers

- client/vscode/src/chatActivation.ts
correct the return type in the chatActivation file to fix one of the broken internal build errors.
> fix: correct the return type to fix internal build

- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/qChatServerIAM.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/qChatServerToken.test.ts
this PR is a folllowup of https://github.com/aws/language-servers/pull/945, which adds some basic tests for the IAM client for q chat server.
> test: add tests for q chat server IAM

- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
In some cases workspace folders will be null. Currently this causes an exception to be thrown by the context server's initializer and crashes the server.
Removed an unnecessary exception raised when workspace folders is not provided. This is already handled by subsequent code which passes an empty array in this case.
> fix: handle undefined workspace folders in context controller

- chat-client/src/client/features/history.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
Click on empty history list item open chat window and sends `conversationClicked` event to language server.
* Do not invoke click event on empty history item in chat client
* Do not handle click event on "empty" history item in language server
> fix(chat-client): disable click event for empty history list item

- app/aws-lsp-codewhisperer-runtimes/src/agent-standalone.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Tool Results need to be passed back into the model for the next request.
Add user and assistant responses to the history, and add tool results to the current message.
> Agentic chat

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
Currently language server will fetch Developer Profiles from all supported region at update, which may add unnecessary latency to whole UpdateProfile request.
Fetch profiles only from region from requested profileArn
> fix(amazonq): fetch profiles only for requested profile region when updating profile

- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
`require.main` may be undefined in cases such as the Webpack build process. This previously would have resulted in an exception.
Handling for case where `require.main` is undefined, with fallback attempt being made to resolve off `__dirname` to discover the import. Ultimately if the library cannot be found indexing will not be available but will not break other LSP functionality.
> fix: handle indexing library import when require.main is undefined

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/addtionalContextProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContexts.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.ts
- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
We need to support files/folders/code symbols/prompts as context command in agentic chat, and also show user the context referenced in chat response
note telemetry update will be followup in next PR
related VS Code change: https://github.com/aws/aws-toolkit-vscode/pull/6999
> feat(amazonq): support context commands in agentic chat

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/shared/models/constants.ts
- server/aws-lsp-codewhisperer/src/shared/models/model.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.test.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/supplementalContextUtil.ts
Supplemental Context included in suggestions requests currently does not include inline project context
Port over vscode toolkit implementation to include project context in supplemental context sent in suggestions request. Leverages vector library and local project context addition to the language server component.
_**Note:**_ This code is reliant on PR #982 re-enabling the localProjectContextController's ability to find the vector library.
> feat: enable inline project context in suggestion requests

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/shared/models/constants.ts
- server/aws-lsp-codewhisperer/src/shared/models/model.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.test.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/supplementalContextUtil.ts
Reverts aws/language-servers#983
> Revert "feat: enable inline project context in suggestion requests"

- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
When parsing the AmazonQWorkspaceConfiguration object, two parameters are using the old parameter names.
Refactored to use correct parameter names.
> fix: parsing AmazonQWorkspaceConfiguration

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/addtionalContextProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
- moving contextComandProvider into agenticChatController instead
> fix(amazonq): move context command provider to agentic chat controller

- core/aws-lsp-core/src/util/workspaceUtils.test.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
There have been recent changes to the VSC implementation that are not reflected here. 
- Sync up to most recent changes: https://github.com/aws/aws-toolkit-vscode/blob/741c2c481bcf0dca2d9554e32dc91d8514b1b1d1/packages/core/src/codewhispererChat/tools/listDirectory.ts#L19
- In VSC, they re-implement a regex type checker. Instead of doing that I simplified the code to use regex directly. See [here](https://github.com/aws/aws-toolkit-vscode/blob/0eea1d8ca6e25243609a07dc2a2c31886b224baa/packages/core/src/codewhispererChat/tools/listDirectory.ts#L19) for the VSC implementation. 
- Centralize path validation object, rather than having two identical implementations. 
> chore: resync listDir tool with VSC

- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
There have been recent changes to the VSC implementation that are not reflected here. 
Sync up to most recent changes: https://github.com/aws/aws-toolkit-vscode/blob/741c2c481bcf0dca2d9554e32dc91d8514b1b1d1/packages/core/src/codewhispererChat/tools/executeBash.ts#L132
There are two items marked for future work:
- expose a function to check if workspace contains a file (in runtimes). 
- generalize a proper way to handle tool cancellation. 
> chore: sync executeBash tool with vsc version

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
There have been recent changes to the VSC implementation that are not reflected here. 
Sync up to most recent changes: https://github.com/aws/aws-toolkit-vscode/blob/16aa8768834f41ae512522473a6a962bb96abe51/packages/core/src/codewhispererChat/tools/fsWrite.ts#L42
> chore: sync FsWrite tool with vsc version

- chat-client/src/client/withAdapter.test.ts
- chat-client/src/client/withAdapter.ts
Tab bar actions for chat History and Export do not work in tabs handled with injected hybrid controller.
Do not route tab bar events to injected controller, handle all in Chat Client itself. There's no use case to route them outside
> fix(chat-client): do not route onTabBarButtonClick to custom handler

- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContexts.test.ts
Moved from https://github.com/aws/language-servers/pull/987. 
Q doesn't know what the workspace folder path is. When I ask it "what is the path to my workspace" it tries to use a few tools, then fails, then tries to find from the root directory, which takes a very long time and basically forces the user to delete the tab. 
This works on the VSC implementation. This is affecting how tools are used.
- Ensure it is passed as context similar to how agentic-chat feature branch does it
- added a unit test
- can be verified end-to-end with the following prompt:
> fix: add workspace folders as context for agentic-chat

- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
We don't need to wait until indexing finish to init the instance of projectContext controller
> fix(amazonq): init localContextController don't wait for indexing finish

- chat-client/src/client/tabs/tabFactory.ts
when a chat adapter is passed into createMynahUi onStopChatResponse is defined causing "stop generating" to show on the regular chat panel
set cancelButtonWhenLoading to false in the tab factory which always disables "stop generating"
> fix(amazonq): hide stop generating button in hybrid chat

- core/aws-lsp-core/src/util/workspaceUtils.test.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Follow up: https://github.com/aws/language-servers/pull/969#discussion_r2051179501. 
This utility function didn't do exactly what its expected to do. See the discussion linked above for more information. 
- use the initializeParams to determine if a file is part of the workspace. 
- inject the lsp into the tools so that we can fetch these workspace folders. 
~~Do the initializeParams update when the info changes? Ex. if I open a new workspace, are these updated? In my testing, the answer appears to be yes, because the language server reloads, but would like to confirm this somehow.~~
answered below, thanks @jpinkney-aws. 
> fix: isInWorkspace should work on closed files. 

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
FsWrite will try to write files in the workspace via `./filename`, but this is not supported in the tool. 
This also leads to files being written to home directory by default, but we want workspace by default. 
- update the spec such to make the instructions to the model clear. 
- This is in-line with VSC-side implementation. 
> fix: update fsWrite spec specify absolute path only

- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
When `resolvePaths` in `withSymlinks({ resolvePaths })` is set to true, `fdir` uses the absolute path to the symlinked directory. However, ignore, unless `allowRelativePaths` is toggled on, [throws on paths outside the base workspace folder directory](https://www.npmjs.com/package/ignore#:~:text=options.allowRelativePaths%3F%3A%20boolean%20since%205.2.0), so path's beginning with `..` will throw.
Exclude directories that are outside the current workspace folder. If `includeSymlinks` is set to true, then use the relative path for the directory (i.e. with prefix `absolute/path/to/symlink/in/workspace/**`), which would arguably provide better context to Q.
> feat: improve symlink handling

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Currently, history is not persisted if I use agentic chat and sign in via IdC, but work if I sign in via BuilderId.
Apparently, Q API does not return `conversationId` anymore in response (reason to be clarified).
Given a lot of chat functionality, including history, depends on `conversationId` present, we set it to random UUID. We set it for agentic chat only, base chat based on `SendMessage` continues working as before.
> fix: history not persisted for agentic chat via IdC signin

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Chat history was not included on every request unless the history was just rehydrated before the first prompt.
Add the chat history from the chat database on the initial request for each prompt.
> fix: add history to request on each chat prompt

- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- chat-client/src/client/texts/pairProgramming.ts
- chat-client/src/client/withAdapter.ts
- chat-client/src/contracts/chatClientAdapter.ts
- chat-client/src/contracts/serverContracts.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Missing pair programming toggle
Add pair programming toggle on the bottom left of chat
Depends on https://github.com/aws/language-server-runtimes/pull/449
> feat(amazonq): add pair programming toggle

- chat-client/src/client/chat.test.ts
- chat-client/src/client/mynahUi.ts
We had export for tabs open from history working fine, but it turns out export is not supported with card items with `type: ChatItemType.ANSWER_STREAM`. Flare, unlike vscode, uses MynahUI streaming card items. So, export is not working if you try to export active tabs (not open from history, but with content streamed from server).
Convert card items with `type: ChatItemType.ANSWER_STREAM` to card items with `type: ChatItemType.ANSWER` at the end of streaming response.
https://github.com/user-attachments/assets/36e1431b-e7f2-4d5c-8041-9476d87a1216
Next steps:
Work with @Jurredr  and @dogusata to ensure export support for all types of card items.
> fix: export for answer-stream card item

- chat-client/package.json
- chat-client/src/client/chat.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/utils.ts
- package-lock.json
New fields added need to be passed to mynah-ui
- bump runtimes version
- add utils to convert runtime types to mynah types
- pass `header` and `buttons` to mynah-ui
> feat: add header and buttons to chat response

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Initial FsWrite tool message implementation
- Send header params from controller
- Update mynahUi to handle tool specific messages. Things like fullWidth and padding do not belong in the flare library, so we need custom logic to add them in the UI.
> feat: initial fsWrite chat message

- chat-client/package.json
- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- chat-client/src/client/texts/pairProgramming.ts
- chat-client/src/client/withAdapter.ts
- chat-client/src/contracts/chatClientAdapter.ts
- package-lock.json
agentic chat is missing the pair programmer card
implement it with the following behaviors:
1. If the pair programming card was dismissed in a previous session, never show it again
2. Continue showing the pair programming card in new basic chat tabs until you click the "X" to dismiss it. Once the "X" is pressed it will never be shown for future tabs in the current chat-client session or future sessions
3. If you have multiple basic chat tabs open and click X on one of them it only closes the programmer mode card for that single tab
> feat: add pair programmer card

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-yaml-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
internal pipeline always uses latest runtimes which not compatible with current version. 
- update runtimes and implement stubs for new `onButtonClick` method. 
> chore: bump runtimes to 0.2.69

- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContexts.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
`@workspace` is not supported in agentic chat context commands now.
The support for `@workspace` was added. It relies on local workspace indexing working.
TODO in followup PRs: prompt customer to enable indexing if it's disabled.
> feat: add @workspace context in agentic chat

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
FsWrite card always shows +0 -0 for diff changes. This is happening because we aren't comparing with the old content before the tool executed.
- Refactor fsWrite to move out all the logic relating to getting the contents before/after the change
- Ensure we are always comparing with the old content (we are now storing this in a tool lookup map)
- Fixed an issue where openDiff did not work for nested file paths because relative file path was not used
> fix: added/deleted lines is incorrect

- .vscode/launch.json
Enabling Q profiles and communication encryption by default slows down development cycle.
disable profiles and encryption when launching Q language server for testing
> chore: disable profiles and encryption for Q language server by default

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
update the language-server-runtimes to 0.2.72 which includes the optional cancellation token for tools
> chore: update language-server-runtimes to 0.2.72

- chat-client/package.json
- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/utils.ts
- client/vscode/package.json
- client/vscode/src/chatActivation.ts
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
Currently we don't have a way to support additional context commands from the client side.
Adding support for this
> feat: added support for injecting additional context commands

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- currently execute bash output json to chat message
- have UI message for asking user confirmation and handle reject/ accept onButtonClick
- write stderr/stdout to chat message
remaining work:
- currently commented out blocking on user confirmation ([this line](https://github.com/aws/language-servers/pull/1041/files#diff-0da876fbe798d89b1ae25052ceca6949c8b334ed02f207f1f5c45b3d5dbeebf0R465)) because intermediate messages are somehow not streamed to the chat window (the confirmation buttons are not there yet)
- testing to verify once we block on user confirmation the buttons are functioning as expected
- polish UI to match the mock
> feat(amazonq): initial UI for execute bash chat message

- chat-client/src/client/tabs/tabFactory.ts
- remove examples from welcome message
before:
after change:
> fix: remove examples from welcome message

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
Explanation from tools are not rendered in the chat
Render explanation as directive chat from tools
> feat: add explanation text as directive

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
The reject button causes the chat to hang since its caught in the agentic loop. 
- Create a new `ToolApprovalException` that we bubble up to escape the loop. 
- For other errors, we still feed them back to the model. 
- This is separate from cancellation via the stop button, so I avoided re-using the same language. 
https://github.com/user-attachments/assets/3e4fdd94-26ae-49b6-8b19-3a7640900dfb
- 
> fix: reject should terminate agentic loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
File click did not work for list/read because the workspaceRoot was getting appended twice in the path.
Use the path parameter directly 
> fix: wrong path for file click uri

- core/aws-lsp-core/src/util/awsError.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
tools can't be canceled
- plumb the cancellation token through to the tools
- tools can optionally handle the cancellation token if it makes sense. e.g. execute bash/list directories makes sense, write file and read file doesn't
- when a token is cancelled, it bubbles up the main agentic loop, sending an answer back to the chat-client and unlocking the UI 
> feat: add cancellation handling to tools

- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.ts
- client/vscode/src/chatActivation.ts
flare is using "highlightCommands" and vscode is using "highlightCommand". We can either fix it in flare or we can convert what the frontend receives from the backend in vscode to use highlightCommands
"highlightCommands" -> "highlightCommand" in flare
> fix: highlight command mistype

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- fix issue that json output is still shown due to missed `break` in prev rebase
- update the header buttons for user confirmation 
> feat: update confirm header after button click WIP

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- `fsWrite` tool tends to favor doing line-by-line replaces which causes
an increase in latency.
- Updated the tool spec to add an important guideline around the fsWrite
tool usage - restricting strReplace command to only simple single-line
replacements, while recommending the create command for multi-line
edits.:
`* IMPORTANT: For the `fsWrite` tool, only use the `strReplace` command
for simple, isolated single-line replacements. If you are editing
multiple lines, always prefer the `create` command and replace the
entire file content instead.`
|     | Build with strReplace | Build without strReplace |
| -------- | ------- |  ------- |
| renaming a single function |  16s  |  17s |
| translate comments (multi-line replace +19 -20) |  98s  | 20s |
By submitting this pull request, I confirm …
> fix: update fsWrite toolSpec

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
See the attached demo:
https://github.com/user-attachments/assets/ae59d434-941b-4633-99c6-3164c362ffee
- The core of the problem is that rather than writing the new block after the tool confirmation, we should update the previous. However, I want to be careful how I allow overwriting of previous blocks.
- However, I want to be careful how I allow overwriting of previous blocks. Therefore, the `writeBlock` function returns a `blockId` (really an index), that allows us to modify it later.  relevant: https://github.com/aws/language-servers/pull/984#discussion_r2049707634
- I imagine this will be very useful for undoing previous tasks and updating their resulting blocks. 
- I went to add a test suite and it was disabled so marked re-enabling and fixing the tests there as a follow-up. 
By …
> fix(amazonq): avoid double rendering on confirmation.

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
https://github.com/aws/aws-toolkit-vscode/commit/6f0dc14877457d9ce0a174a9a8b567a6265ea6f1
- We currently include codeReferences as part of the history field in
the request which can sometimes cause validation issues
- We are currently only retrieving the last 10 messages in the history. This will break the history validation
- Do not include references in request history
- Retrieve entire history then call fixHistory when sending request
> fix: do not include references in request history

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- Existing plugin shows read files multiple times and emitted per file.
- Use a `messageIdToUpdate` state to store the messageId and update this for next read tool messages.
- This code change is equivalent to this PR: https://github.com/aws/aws-toolkit-vscode/pull/7006 in `feature/agentic-chat` branch.
- I will send out a follow up PR supporting List directory UX changes and mode refactored code.
> fix: ux polishing for read tool messages.

- chat-client/src/client/utils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
Card should be updated after undo is clicked
Implement the chat update mechanism on button click
Refer to https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/amazonq/webview/ui/apps/cwChatConnector.ts#L394-L404 for previous implementation.
> feat: send chat update on undo

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
User permissions check for reading files/list directory outside of workspace is not setup.
- add permission check for fsRead and listDirectory tools
- Adds permission cards for allowing access
> feat(agentic chat): add permission check for all tools and add UI permission cards

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
- https://github.com/aws/aws-toolkit-vscode/commit/67a3b4bd0a0b484a5bb5929446aa077070d359aa
- https://github.com/aws/aws-toolkit-vscode/commit/62f6ac5de345f7408d02251d2d957e146b3eaffc
- Inconsistent History Sources: Initial request gets history from DB, subsequent requests build history in memory. History is manually built in memory rather than consistently using the database as source of truth
- Incomplete History Storage: `#handleFinalResult` only saves initial prompt and final answer, losing all intermediate steps when re-loading history. We also don't store the toolUses
- Fix the history to maintain invariants before each request
- Retrieve the history from DB instead of in-memory
- Do not include chatHistory for requests going to Mynah
- Store all user and assitantResponse Messages
- …
> fix: ensure chat history consistency by fixing database state before each request

- chat-client/src/client/chat.test.ts
- chat-client/src/client/chat.ts
- chat-client/src/client/utils.ts
We were seeing empty yellow header on top of followup buttons, like "Authenticate"
Do not set header with empty properties.
Also fixed: TypeError: object is not iterable
> fix: remove undefined header from followup authenticate button

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
We would show the full path for the modified file, which makes users sometimes hard to read
https://github.com/user-attachments/assets/1ea7c9a0-59fc-4b7a-80f0-175e5695323e
> fix(agenticChat): Only show the file name in chat

- chat-client/src/client/mynahUi.ts
- File list cards should not be full width
- Tool cards should never have code block actions
- Tool cards with buttons should have clear status
> fix: tool cards have the wrong props

- client/vscode/src/chatActivation.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
When we click `Reject` button for shell command, that message chat item body is added twice.
Prevent writing duplicate block for shell command written on Reject command click
https://github.com/user-attachments/assets/13b65a9b-aade-4e34-ab29-658f4e652feb
> fix: prevent double-writing executeBash command block on Reject button click

- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/tools/relevantTextDocuments.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/tools/relevantTextDocuments.ts
Local project context is available in Flare but not currently wired up to Q chat.
Added support for enriching Q chat requests with local project context. Context is added when chat requests contain the `@workspace` context command and are available whether files are open in the editor or not.
> feat: support for project context in Q Chat

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
Permission check cards are appearing for all the files inside workspace. This is happening due to regresion in workspace.getTextDocument failure which works only for open documents on editor.
- Fixing workspace check for all tools with lsp.
> fix(chat-client): workspace checks for permission cards

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
context transparency list was not being sent, due to changes to joinResults in https://github.com/aws/language-servers/pull/1039
Send Context transparency list just once, at the beginning of the assistant response. This avoids conflicts between context transparency list and any context lists returned from assistant
https://github.com/user-attachments/assets/a28568f3-560a-4fa3-b9ce-c62a1af7d16f
> fix: context transparency list not displayed

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- https://github.com/aws/aws-toolkit-vscode/pull/7081
- https://github.com/aws/aws-toolkit-common/pull/1014
- Want to see the distribution of tools that LLM either used directly or suggested
- Emit metric toolUseSuggested after LLM invokes any tool
- also bump toolkit commons version in hybridChat branch so that these events from flare actually get sent to kibana: https://github.com/aws/aws-toolkit-vscode/pull/7147
> fix: metric to show tool distribution

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/shared/db/chatDb/chatDb.ts#L298
We only need the toolResult in the userMessageContext. This is causing validation exceptions as we are not taking the other fields into account when calculating the character count in the history
Only store the toolResult in userMessageContext
Verified that the history file now only stores toolResult in userMessageContext:
```
"messages": [
{
"body": "run ls &amp;&amp; pwd",
"type": "prompt",
"origin": "IDE",
"userInputMessageContext": {}
},
{
"body": "I'll run the `ls` command to list the files in the current directory and then `pwd` to show the current working directory.",
"type": "answer",
"toolUses": [
{
"toolUseId": "tooluse_eFrk87EMQ9GSwENNdhvhvw",
"name": …
```
> fix: add formatChatHistoryMessage to chatDb

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Service is sometimes throwing ValidationException with reason `CONTENT_LENGTH_EXCEEDS_THRESHOLD` if content becomes too large.
Validate the tool output to ensure the results are not too large
Previous implementation: https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/codewhispererChat/tools/toolUtils.ts#L75-L90
> fix: validate tool output content size

- client/vscode/package.json
- client/vscode/src/selectQProfileActivation.ts
There is currently no convenient way to list and select Q developer profiles in the sample vs code extension.
Add a new command to the vs code sample extension, which:
1. queries the available q developer profiles (based on the active bearer token)
2. displays a vscode quickpick menu with the retrieved profiles
3. sets active profile to the one selected from the quickpick menu
Testing: verified it works by starting a token server, obtaining IDC credentials and then running the command.
> test(amazonq): add simple flow for selecting Q profile in vscode sample extension

- chat-client/src/client/texts/pairProgramming.ts
The mode switch for pair programmer mode has to be checkbox instead of a switch component.
Changed `switch` to `checkbox`.
> fix: convert switch to checkbox for PPM mode

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.ts
The "create a saved prompt" user experience was lacking proper validation, allowing users to input an invalid file name. If an invalid name was entered and creation failed, no validation error message was shown.
Add validation logic to the saved prompt creation flow with regex enforcement, and display an error message if user input is not valid.
https://github.com/user-attachments/assets/49f8f93e-c9f8-4d8f-8c51-8fd9602170c9
> fix(amazonq): add validation for create a saved prompt UX

- chat-client/src/client/mynahUi.ts
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
required UX for the grep search result
1. adding the grepSearch tool to support search for text content in files within a directory and its subdirectories. 
2. using the vscode-ripgrep npm module to implement the tool: https://github.com/microsoft/vscode-ripgrep
3. tested the tool local E2E, check the following screenshot
> feat: add the grepSearch tool

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Bash command and output should be combined in a single code block
> fix: execute bash output formatting

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Adding the file search tool to support search a directory/subdirectory by regex patterns
Adding the file search tool to support search a directory/subdirectory by regex patterns
> feat: add file search tool

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
Error handling for backend requests is non-existent and the existing error handling elsewhere relies on flaky checks. 
Testing these changes with @jpinkney-aws, we identified 3 problems fixed by these changes. 
- backend errors cause chat to hang. 
- the stop button doesn't always stop the action depending on the time it was pressed. 
- the authenticate button doesn't pop-up, its blocked by "thinking...". 
- forward backend error message to the client to be displayed in chat. 
- on error, send a progress update to the client to kill the thinking bubble. 
- centralize error handling to minimize flaky checks. 
- In addition to unit tests, these changes were tested e2e. See demo below for a demonstration where I have the model always fail on the second iteration of the agentic loop. …
> fix: implement proper error handling.

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- thinking don't show up in second round of messages because the ID used wasn't unique
- sometimes it takes a while from us rendering text response to processing toolUse
- listDir/read/search shows result before running the tool
- switch to use `uuid` instead in iterations
- add additional loading message between text response to toolUse processing
- move list/read/search result to after tool run
> fix: further improvements for thinking/loading

- chat-client/src/client/chat.test.ts
- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- client/vscode/src/chatActivation.ts
Regional dev profile support for chat client.
> feat(chat-client): support profile banner changes

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
- error metric not emitted properly 
- correctly emit error metric 
- correctly get the requestID and errorMessage for the error
- port over `getHttpStatusCode` and its helpers from here: https://github.com/aws/aws-toolkit-vscode/blob/c22efa03e73b241564c8051c35761eb8620edb83/packages/core/src/shared/errors.ts#L648
> fix: error message metric now correctly emitted

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- No tool tip if user hover over folder or files in fileListTree view.
- Fixed by passing description in the context list.
https://github.com/user-attachments/assets/d962ead4-2ba3-40f7-974f-585fb4a4e26b
> fix: adding tooltip description to filePaths

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
There is no return message for rejecting command
> fix(chat-client): return message for rejecting command

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
Sometimes the server can respond with an invalid JSON as input and causing the entire process to stop/hang.
1. Handle the error gracefully so that it doesn't stop the agentic loop partway through
2. Send the error back to the server as a valid ToolResult with error
Previous implementation: https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/codewhispererChat/controllers/chat/controller.ts#L754-L758
> fix: invalid json aborts the loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
- not emitting `languageServerVersion`
- missing one additional case when emitting error metric. `errorMessage` and `requestID` might be nested one level deeper in `err.cause`
- emit `languageServerVersion` for agentic chat metrics such as `amazonq_messageResponseError`, `amazonq_addMessage`, `amazonq_toolUseSuggested`
- before emitting error metric, include additional check for setting `errorMessage` and `requestID`
> fix: emit languageServerVersion and add addtional case for error metric 

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
LLM can sometimes hallucinate and think it has access to tools it shouldn't in the current mode.
Add client side check to verify if a tool can be executed depending on the current mode. When this happen, we tell the LLM implicitly that this tool use is not allowed in the current mode and the LLM will correct itself and avoid using that tool.
> fix: pair programming mode toggle is not respected

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
the loading after streaming text response doesn't get cleared out, causing the extra thinking in the end of response. The issue is the text streaming itself actually takes a long time to resolve. That is still under investigation.
- this will remove the extra thinking
- need to followup on the text streaming slowness
> fix: extra thinking in the end

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
We are unable to debug ISE issues due to an issue with our logger, where we are only able to log INFO level logs.
Change some important logs to INFO level logs
> fix: change log-level for request logs

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
Uploading Screen Recording 2025-04-25 at 5.04.09 PM.mov…
Stop button is not killing long running bash executions.
- stop button kills the shell executions with periodic listener running for execute bash
> fix: stop button kills the shell executions

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
If a user tried to create a saved prompt but the `~/.aws/amazonq/prompts` directory did not already exist, server would error with `Error creating prompt file: Error: ENOENT: no such file or directory, open '/Users/ammathu/.aws/amazonq/prompts/test.md'`
Recursively create user prompts directory
> fix(amazonq): recursively create directory for saved user prompts

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Missing "Undo all changes" functionality
- Added an "Undo All Changes" button that appears after non-fsWrite tool uses when there are pending file changes
- Refactored the tool use tracking system to store tool use data in the chat session instead of the trigger context
- Implemented tracking of related file changes to group them for the undo-all functionality
- Added new methods to handle the undo-all operation and update UI state accordingly
https://github.com/user-attachments/assets/efb84b85-d6db-4af5-b67b-d10730c3bf15
> feat: undo-all button

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/codeSearch.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/codeSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
To support the semantic search for the code base. 
* add this code search tool to using the LocalProjectContextController to support semantic search, similar as the workspace falcon. 
* no UI is required for this semantic search tool. 
> feat: add the code search tool to support semantic search in the workspacke

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
User intents are no longer relevant for chat.
Remove the guessing capability.
> fix: remove guessIntentFromPrompt functionality while preserving user Intent property

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
`@Code` is showing file names instead of code symbol name 
Display code symbol names in list. See corresponding code in https://github.com/aws/aws-toolkit-vscode/blob/3171de5e4a90c9e8b4aec0965fcd5c9bc0235745/packages/core/src/codewhispererChat/controllers/chat/controller.ts#L590
Before
After
> fix(amazonq): `@Code` items show symbol name instead of file name

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
Previous JSON parse fix (https://github.com/aws/language-servers/pull/1141) did not work fully, the LLM keeps retrying the same input and ends up in a loop.
Set an explicit userInputMessage to tell the LLM to break the task down when it encounters this exact issue.
> fix: llm not breaking down requests when input is too large

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
New tools causing regression.
Temporarily remove tools from tool server.
> feat: remove fileSearch and codeSearch tools from Amazon Q language server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- For context, here is the agentic-chat branch PR which I am porting over to language-servers: https://github.com/aws/aws-toolkit-vscode/pull/6979
- We would like metrics based on these **product requirement definitions**:
1) Command execution acceptance rate: 
- [#Commands that users click run on] / [#Commands generated that required user to click run on]
2) Diff acceptance rate: 
- As all diffs are auto-accepted, the acceptance rate is calculated by: 1 - [#Diffs rejected] / [#Diffs generated]
- Rejection is defined as user specifically pressing the Undo button
3) Stop chat: 
- User specifically clicks Stop button
- Implicit stop: user interrupts current ongoing message with new message 
- emit `amazonq_interactWithAgenticChat` metric
- tested in kibana
By submitting this pull request, I …
> fix: telemetry for agentic chat interactions

- chat-client/package.json
- package-lock.json
Previous mynah-ui version added an extra `}` at the end of every detailedListItem description
Upgrade to latest mynah-ui version which includes a fix: https://github.com/aws/mynah-ui/releases/tag/v4.31.1
Screenshot:
> fix(chat-client): upgrade to mynah-ui 4.31.1

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Clicking on file link in Q message response doesn't work on Windows machine. This breaks Create a saved prompt UX, and clicking on file links in context transparency list/ fsRead tools responses.
Pass the proper URI string to window/showDocument request
> fix: clicking files on Windows doesn't work

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Backend error messages are expected to be shown directly to the customer in chat. However, there are other error messages we don't want to show, and should show a generic message. 
- Implement an error wrapper with a `code` field, that allows each type of error to have its own handling. 
- Expand reach of `try` block such that any internal errors surfaced are caught and returned as `ResponseError`. This also makes this easier to test. 
- updated a unit test, and added another for generic behavior. 
- Backend error (replacing backend call with an error)
https://github.com/user-attachments/assets/12b44857-6a52-4d8f-8e7b-55fcac374429
- generic error (throwing an error elsewhere in the agentic loop)
https://github.com/user-attachments/assets/8ded36f1-018d-401e-8a7f-0a90ee818f59
By submitting …
> feat: allow backend errors to be handled seperately

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
Tool spec descriptions are inconsistent.
Make them follow a consistent scheme, and clearly articulate usage.
> docs: standardize tool descriptions for fsRead, fsWrite, and listDirectory

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- package-lock.json
- Tooltip remains if there is a prompt option value change.
- Codes are not wrapping in tool use
- Removed unnecessary handling which overrides the prompt options after value change. Options keep their values, it doesn't require an override. 
- With new version of mynah-ui, used the option `wrapCodes` to wrap the codes for tool uses.
> fix: prompt options override

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
When the agent exceeds our threshold (currently 100), the frontend doesn't render anything. This is because we return a ResponseError without a valid ChatResult body. 
- Centralize all error handling to the `handleRequestError` method. I.e. do not return response errors from anywhere else. This allows us to ensure we are returning valid ChatResults in the data field. 
- Show a specialized message for agent loop exceeding. 
https://github.com/user-attachments/assets/ef4b2ddc-5355-4658-bb85-c77984ebf330
> feat: show agentLoop error in chat

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- reference agenticChat branch pr: https://github.com/aws/aws-toolkit-vscode/pull/7069
- want to differentiate between a message without tool use (ex: what time is it) and a message with tool use (ex: write a docstring for my function)
- for both successful messages and messages that resulted in error, see if this message was apart of an agentic loop.
- An agentic loop is when the LLM asks to run a tool and the LLM receives the results back of running the tool.
> fix: see if message is apart of agentic loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- Context list is send to mynah for every execution in runAgentLoop so this shows as flickering ux.
- Fixed this issue by adding a session variable(`session.contextListSent`) to send context list only once
https://github.com/user-attachments/assets/dca980c2-d2e8-41e3-a265-f804cd720051
> fix: fix for context list flickering ux

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
https://github.com/user-attachments/assets/61f09416-bdd1-4f54-84c1-755016b8fd04
https://github.com/user-attachments/assets/26f60083-3816-4249-8622-0df751c3d07e
- Q not asking for permission to run commands outside my project
- Allowing read access to a folder should implicitly give read acecss to all subfolders
- fixed workspace checks for cwd in execute bash
- fixed execute bash warning icon
- Added approvedPaths setup for each tab which adds approved paths, clears it when tab closes and checks for approved paths.
> fix: allowing access to a folder should implicitly give access to sub folders

- chat-client/src/client/mynahUi.ts
there is bug in the input prompt popup UI to display the max prompt chars size as 4000. 
This is cause as use the default flare chat ui config as following. 
```
userInputLengthWarningThreshold: 3500,
maxUserInput: 4096,
```
Fix this issue by override the default flare chat ui config in the language server package. verified with a large prompt
> fix: override the MynahUi maxUserInput config

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
A customer reported an issue where after gathering too much context, they receive a 4xx exception for the input being too long:
- Show a special customer-facing message for this issue
- Added unit tests to verify issue
- Reproduced issue and verified message:
> feat: show customer facing message for inputTooLong error

- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
This metric was not being emitted on the VSC side because it contained missing fields. This is due to a typo in the metric name. 
- fix the typo
- verified this is emitted via IDE logs. 
```
[debug] telemetry: amazonq_messageResponseError {
Metadata: {
metricId: '0355b2b6-53fa-4d6e-9a8b-bb23d57ff8c2',
traceId: 'd4fe8c26-7f0e-406d-8e69-538d45c17478',
parentId: '8165cc0a-1852-45a7-b0d7-79a9ee3de2e8',
cwsprChatHasCodeSnippet: 'false',
cwsprChatTriggerInteraction: 'click',
cwsprChatActiveEditorTotalCharacters: '0',
cwsprChatResponseCode: '500',
cwsprChatRequestLength: '4',
cwsprChatConversationType: 'AgenticChat',
requestId: 'eb03a038-f468-44d6-966e-6356827e4b68',
reasonDesc: 'Encountered an unexpected error when processing the request, please try again.',
credentialStartUrl: …
```
> fix: typo in response code metric field

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/addtionalContextProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
Telemetry was being incorrectly reported for `@Files`, `@Folders`, `@Prompts`. Missing telemetry for `@Code`
Fix metrics being emitted for `@Files`, `@Folders`, `@Prompts` and metric for length of open file (`cwsprChatFocusFileContextLength`). add metrics for `@Code` count and length
> fix: telemetry for `@Files`, `@Folders`, `@Prompts`, `@Code`

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
STE requests are failing for addMessage because:
- we are not passing profileArn
- timeBetweenChunks has a limit of 100
- add profileArn
- cap timeBetweenChunks length
> fix: add profileArn for STE and fix timeBetweenChunks

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
This is happening when there is a tool error which is automatically retried.
When this happens, populate the user input content to make the LLM respond with some new response.
> fix: duplicate explanation

- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/errors.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
When a throttling exception is thrown with the ListAvailableProfiles API, the error is swallowed and client is informed of a generic failure without information on the cause of the failure. Since clients do not have this information, a vague message is shown to the user similar to `Unable to retrieve profiles`. We want this to be bubbled upstream to the client
Whenever a throttling exception is thrown with the ListAvailableProfiles API, a ResponseError with a specific awsErrorCode `E_AMAZON_Q_PROFILE_THROTTLING` is now sent back for the client to interpret and use for showing an appropriate message to the user.
Note: When atleast one of the calls fail for ListProfiles invoked for different regions but no profiles are found, a throttling error will be thrown back to the client.
By …
> fix: bubble up throttling error for ListAvailableProfiles API to client

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
we have no way to send an event from the client side and trigger it in flare. This is needed for events like "explain issue" from VSCode's security scan, which triggers a event that gets displayed to the user, and a separate event that gets sent to the backend
wire up an autosubmit event that when enabled takes a prompt from sendToPrompt and automatically submits it
**note**: the extended types were for testing, if this API is agreed upon i'll make the changes in the runtimes package
Related VSCode PR: https://github.com/aws/aws-toolkit-vscode/pull/7194
> feat: implement new sendToPrompt params

- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
- for some features that doesn't depend on vector indexing, we should still initialize the library but have the setting to control if we build vector index
- refactor to always call `init` and add check for if we need to call `buildIndex`
> feat: use enableLocalIndexing to control actual indexing

- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- `amazonq_interactWithAgenticChat` metric is missing result field
- cwsprChatConversationId field is sometimes empty
```
[warning] telemetry: invalid Metric: "amazonq_interactWithAgenticChat" emitted without the `result` property, which is always required. Consider using `.run()` instead of `.emit()`, which will set these properties automatically. See https://github.com/aws/aws-toolkit-vscode/blob/master/docs/telemetry.md#guidelines
```
```
[debug] telemetry: amazonq_interactWithAgenticChat {
Metadata: {
missingFields: 'cwsprChatConversationId',
metricId: '7c7f05c6-e94b-47c2-a72a-90302dcd56e2',
traceId: '3f8f394a-3960-4b28-950d-a1e6f803ae80',
parentId: '5926c802-8732-4894-8ff0-6d512fd24814',
cwsprChatConversationType: 'AgenticChat',
credentialStartUrl: 'https://amzn.awsapps.com/start', …
```
> fix: add result field for agentic chat interaction telemetry

- chat-client/src/client/mynahUi.ts
Quick actions like `/help` would be stuck in `thinking ` and not render any response because the `/help` response is hardcoded and immediately streamed without any partial result. With the latest changes in the chat-client, the logic to create a chat item was put inside the `if (partialResult)` block which caused no chat item to be created for cases when there is no partial result.  
This is a quick fix to ensure that a chat item is created if no chat message exists when we have a full result. There is now small code repetition and the logic can be cleaned up further in the future 
> fix: immediate full results not getting rendered e.g /help

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- Falcon context is forgotten in history and is only passed when it's in current message
- fix: keep falcon context in history
> fix: keep falcon context in history

- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
`indexCacheDirPath` was passed to buildIndex incorrectly instead of project root path
this will result in index of different projects overwrite each other, @workspace might respond with a different project's code
pass in project root
> fix: fix project root not passed to buildIndex

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/addtionalContextProvider.ts
- Flacon context is shown only in the first conversation per tab.
- No tool tip for the context list filepaths.
- Fixed two issues.
https://github.com/user-attachments/assets/d42b44b7-b7a9-4ef4-9ca0-b12f06179371
> fix: fix the context list bug and show the tooltip

- core/aws-lsp-core/src/util/loggingUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Logs on errors before:
```
025-04-29 15:09:48.698 [info] [Error - 3:09:48 PM] [2025-04-29T19:09:48.696Z] QModelResponse: {"code":"QModelResponse","requestId":"89eb2f69-a649-4746-a354-72124dc5bb05"} 
2025-04-29 15:09:48.698 [info] [Info  - 3:09:48 PM] Error occurred during chat request: Error: Encountered an unexpected error when processing the request, please try again.
```
Logs on errors after:
```
2025-04-29 14:58:04.499 [info] [Error - 2:58:04 PM] [2025-04-29T18:58:04.497Z] {
"code": "QModelResponse",
"requestId": "1589319b-a4e8-448c-8814-701c090fd3c1",
"name": "Error",
"message": "Encountered an unexpected error when processing the request, please try again.",
"cause": {
"name": "InternalFailure",
"$fault": "client",
"$metadata": {
"httpStatusCode": 500,
"requestId": …
```
> feat: extend logging utilts to support errors

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
This can happen if there is a read operation between write operations. Since read updates get added to an existing card it can look confusing.
Don't reset the undoAll state and don't show the undoAll button when there is a read or list operation. 
> fix: undo all appears between writes

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
There are certain requests that we know will fail before they are made. One example is if the prompt message is over 600k characters. 
- add a pre-validation step for verifying the request that will throw user-facing error messages. 
- implement check for input message exceeds the backends limit. 
- overwrite the message with one of 600,001 characters. 
- unit test for full flow.
> feat: add prevalidation step for request

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/texts/pairProgramming.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- Spacings are not properly adjusted
- Header button status `dimmed-clear` was not being applied
- Updated mynahui to refine spacings and the switch component
- Updated fixed static button status handling on header.
- `header` status fields without a status color applied should get the `disabled` color instead of the `weak` color.
- `header` is not possible to update partially, it requires all or none
- `switch` component styles are not matching
- `status` for the `header` is only available on the right side, it should be optional to put it on the left
- spacings are not matching the expected designs
- spacing after a DIRECTIVE without lines or horizontally center aligned was wrong
- no option to horizontally align the DIRECTIVE card to center without having the side lines
- Refreshing …
> fix: updated spacings through mynah-ui update

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
When we get a code reference event we aren't writing the chat result to the result stream, causing the code reference to not get sent back to the editors
Handle code reference events and send them back to the editors
> fix: add code reference to response stream

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- No message is shown to the user if user click on `Stop` button.
- Fixed this issue
https://github.com/user-attachments/assets/e910c1fb-a8fa-4ab2-9ae1-6aab8943516f
> fix: adding message if user clicks on stop button

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
The entire request can be useful for debugging customer issues. 
- Log the raw request, no truncation, no filtered keys. 
> fix: log entire raw request

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
FsRead and ExecuteBash output already has truncation logic. Since we are checking the size of the overall JSON, sometimes the tool can be truncated but still throw an error for character limit exceeded.
Skip the validation for FsRead and ExecuteBash for now.
> fix: output validation is incorrect for json output

- chat-client/src/client/tabs/tabFactory.ts
- client/vscode/src/chatActivation.ts
Stop button showing but not supported in non-agentic chat.
Also, highlight command is confusing in non-agentic chat  in test client.
- Show "Stop" button only in agentic chat
- Inject feature flags for agentic chat only, as non-agentic is not supporting this functionality yet
> fix: stop button showing in non-agentic chat

- server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.getTransformationErrorCode.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/validation.ts
Currently, our backend language server emits detailed failure reason messages (as strings), but doesn't include standardized failure codes. This creates several challenges:
- Frontend code must rely on string matching against error messages to determine appropriate UI responses
- String matching is fragile - any wording changes to error messages can break frontend behavior
- When issues occur in production, it's difficult to trace which specific error condition triggered a given frontend response
- Inconsistent error handling across the frontend codebase
This PR implements a standardized failure code system in the language server:
- Added a FailureCode enum in the language server
-  Enhanced error responses to include both:
- Human-readable failure reasons (existing)
- failure codes (new) …
> feat(amazonq): add error code handling for transformation jobs

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- Unnecessary warning for normal shell commands
- Fixed this.
> fix: removing warning icon for shell commands

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- `cwsprChatTimeToFirstChunk` field had a typo causing this specific field to be missing when `amazonq_addMessage` metric is emitted
- `cwsprChatTimeBetweenChunks` should not have zeros
- fix typo
- don't append value to cwsprChatTimeBetweenChunks if it is 0
> fix: typo in cwsprChatTimeToFirstChunk and remove all zeros

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
In default cases, Shell execution outside of workspace is not showing warning.
- Continue in default case and not return requiresAcceptance value.
> fix: fix for permission case for execute bash

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Message validation in bedrock occasionally fails due to a mismatch between the number of toolUses and expected number of toolResults in subsequent messages:
```
(ValidationException) when calling the ConverseStream operation: Bedrock error message: The model returned the following errors: messages.54: Did not find 2 `tool_result` block(s) at the beginning of this message. Messages following `tool_use` blocks must begin with a matching number of `tool_result` blocks. 
```
We filter out toolUses by this `stop` flag in the response from the model [here](https://github.com/aws/language-servers/blob/main/server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts#L676). In the history we store all toolUses regardless of this stop flag …
> fix: only keep toolUses with `stop` = true in history

- chat-client/src/client/mynahUi.ts
- Permission check card status are duplicating after agentic loop completion.
- fixes this removing status for additional messages in final result overwrite.
https://github.com/user-attachments/assets/0602b93d-187f-4752-8425-c697f7f5b33b
> fix: fix for status duplicates for permission checks

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- the undo-all-changes button needs to use icon undo
- update undo-all-changes button icon to undo
Before change:
After change:
> fix: update undo-all-changes button icon to undo

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatEventParser.ts
requestId is the single most important piece of information for the backend team in order to effectively debug these issues and its only visible at the `trace` level. 
log it by default at `info` level, along with the rest of the response metadata. 
```
2025-04-30 19:06:55.971 [info] [Info  - 7:06:55 PM] [2025-04-30T23:06:55.966Z] generateAssistantResponse Response: {
"httpStatusCode": 200,
"requestId": "1e8a80f1-4d78-47fe-933d-ffe9f29efafe",
"attempts": 1,
"totalRetryDelay": 0
}
```
> feat: add request id to default log level

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
update runtimes version to 0.2.78 to be able to get awsServerCapabilities from aws/getConfigurationFromServer extension.
> chore: update runtimes version

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- the shell command header ignored status is not correct.
- update header ignore status based on figma doc: https://www.figma.com/design/DNKqLHITCpqAv9RGHKnWQQ/Agentic-Chat-Experience-2025?node-id=1923-25197&p=f&t=3vRozznGwps0u62q-0
Before change:
After change:
> fix: update header ignore status

- core/aws-lsp-core/src/util/workspaceUtils.test.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
The `readDirectoryRecursively` utility was using the exclude directories as patterns. This results in the listDirectory and fileSearch tool ignoring files that are prefixed by the pattern. For example, `build-test` would be ignored, or a file named `output.txt` since it contains `"out"`. 
- use explicit ignore entries that apply at the entry level rather than the entire path level. 
- add a logging statement for when a directory is skipped. 
- added a unit test 
- created a demo folder to test e2e:
- This folder also contains a `node_modules` folder with some files in it, which are ignored. 
> fix: switch to ignore entries over patterns

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- LLM apologizes for when listDirectory fails because project is too big
- Make LLM less apologetic, increase listDirectory result size to reduce the chance of this happening
> fix: make LLM less apologetic, increase listDirectory result size

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextUtils.ts
When a user enters `@workspace`, a Context menu should appear in the response listing all the file chunks sent to Q
Send relevant text documents to contextList
> fix: show context transparency list when using @workspace

- app/aws-lsp-codewhisperer-runtimes/src/agent-standalone.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Have basic MCP function working
* Add basic invoking and result messages for MCP (Final message format is still TBD)
* Require acceptance for MCP tool invocation
* Minor fixes for regression
Enabled the MCP LSP servers so product can start testing the basic function(without UI). and it won't be customer facing.
> feat: basic invoking and result message for MCP

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
There is a service side timeout of 180 seconds. If the stream doesn't complete in that time it causes ISE.
Handle this case by checking if the stream has exceeded 170 seconds on the client. If it has, abort the process and attempt to retry the request again by with smaller steps.
> fix: server side timeout causes ISE

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- fast follows - Reject Run (reject should be darker)
- related figma doc link: https://www.figma.com/design/DNKqLHITCpqAv9RGHKnWQQ/Agentic-Chat-Experience-2025?node-id=3378-28742&p=f&t=7wrhUKUKSPHc2XTS-0
- update reject button status the same as run button
Before change
After change
> fix: update reject button status

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
https://github.com/aws/aws-toolkit-vscode/pull/7059
We show the system generated messages in the UI when reloading chat history. These should be hidden from users
Add a flag for determining whether we should display the messages when reloading from chat history
See video:
https://github.com/user-attachments/assets/5ef114d7-29ae-40c9-8321-b20e0fd3ba41
> fix: hide non-user-generated messages when reloading history

- chat-client/src/client/mynahUi.ts
when user reject/stop command, all other text in the command should also be disabled color. 
This is a prefix, the fix won't work until mynah release the newest version
> fix: prefix if user reject/stop command, whole card should be dimmed

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
We are conditionally reacting off `isEnabled` in the context controller for whether to send a chat response indicating the user should enable workspace indexing to complete their request. This is not working as expected since the context controller may be enabled while indexing is not.
Moving the check to `isIndexingEnabled` which explicitly indicates that workspace indexing is enabled within the controller.
> fix: use proper condition for trigger index enablement response

- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
Local project indexing stub was accidentally merged.
Revert the stub.
> chore: revert local indexing stub

- .vscode/launch.json
- client/vscode/src/activation.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
* Added `CustomizationWithMetadata` interface that extends `Customization` with `region` and `profileArn` fields.
* Added feature flag `customizationsWithMetadata` to client capabilities for opt-in functionality. Client extension must set `initializationOptions.aws.awsClientCapabilities.q.customizationsWithMetadata` flag to opt-in into new functionality.
If `customizationsWithMetadata` flag is set, when `aws.q.customizations` section is requested with `onGetConfigurationFromServer`, server will:
1. fetch all Profiles available to customer.
2. fetch all Customizations across all fetched Profiles.
3. Return list of `CustomizationWithMetadata` objects.
> Customizations profiles update

- core/aws-lsp-core/src/util/workspaceUtils.test.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/listDirectory.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
- Current listDirectory result shows all files/directories with full path which has a lot of duplicates
- Make it return tree-like result which saves a lot of characters
- On the same repo, output character count before the change: 18632, output character count after the change: 7348
> fix: update listDirectory tool to output in tree-like format to reduce size

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
We currently try to estimate and trim the number of tokens in each request before sending to the server. However, this is an estimation and is not always accurate. As a result, we see a number of `Input too long` errors in our metrics.
We also force users to open a new conversation tab to continue.
- Clear current tab history for `inputTooLong` errors to allow users to continue in current chat tab
- Rephrase customer-facing message
Skip through the video if needed:
https://github.com/user-attachments/assets/7ac68c98-1169-4635-b6b1-a66da2549686
> fix: clear history for `inputTooLong` errors

- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
When errors and user cancellations happen, the undo all state is not reset. This can lead to the "Undo all changes" button appearing unexpectedly.
Call `#showUndoAllIfRequired` method in the error and cancellation handlers. Also reset the state even if there is only 1 write operation in the set.
> fix: errors/cancellation not resetting undoAll state

- server/aws-lsp-codewhisperer/src/language-server/netTransform/resources/SupportedProjects.ts
netTransform `unsupportedViewComponents` list is out-of-dated.
Update `unsupportedViewComponents` to reflect the netTransform GA feature. 
> chore: update netTransform unsupportedViewComponents

- .github/workflows/lsp-ci.yaml
- app/aws-lsp-codewhisperer-runtimes/scripts/test-bundles.js
The command introduced in the [PR](https://github.com/aws/language-servers/pull/1228) to test the generated bundle is `test-bundles`. With new PRs post merge of the PR mentioned, I could not see the logs for testing bundles in the packaging step ([Test bundles](https://github.com/aws/language-servers/actions/runs/14876033430/job/41773390164?pr=1276) step has no logs) executed as part of Github workflow action. 
Incorrect command was being used in the lsp-ci.yaml file `test:bundles` instead of `test-bundles`. The PR contains the fix for the same. Also, tested the github actions workflow on my local for Ubuntu setup using [act](https://github.com/nektos/act) utility: `act -W .github/workflows/lsp-ci.yaml` 
By submitting this pull request, I confirm that my contribution is made under the …
> fix: use the correct command name for testing bundles

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
1. @ workspace is in bold for which current regex can not capture and remove it
2. startLine || -1 will be -1 if startLine is 0, but we want 0 so use startLine ?? -1
> fix: regex should match workspace text in bold style and startLine can be 0

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
We occasionally have a race condition caused by the stop button, where toolResults for cancelled tool executions get processed after the conversation has continued, resulting in erros: 
`Got ValidationError: ToolResult with ID tooluse_ has no corresponding ToolUse`
- Added validation to check when a message has tool results but the last message has no tool uses
- Added logic to filter valid and invalid tool results, keeping valid ones and marking invalid ones as cancelled.
- Added logic to terminate agent loop when history is invalid
> fix: abandon requests with invalid toolResults

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
System generated message `You took too long to respond - try to split up the work into smaller steps. Do not apologize.`sent to the model is still being displayed to users when chat history is reloaded
- Set the `shouldDisplayMessage` to false for this case
> fix: prevent timeout messages from displaying

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
Core logic is needed for managing MCP server configurations.
* Implemented CRUD methods for MCP servers.
* Resolved merge conflicts with main.
* Methods were tested using unit tests and manual debugging ([code](https://paste.amazon.com/show/bywang/1746565989)); both file system and in-memory behavior were verified.
* Tool permission handling is not yet finalized—pending product input. Likely to require a separate configuration file.
* Error handling for configuration is still TODO and tracked separately; errors are currently thrown directly.
>  feat: add CRUD methods for MCP servers

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
- We are seeing errors like "socket hang up", "read ECONNRESET", "aborted", "read ETIMEDOUT" for long-lasting requests, this is caused by streaming client having a shorter timeout than the service timeout
- set streamingClient timeout config to match service limit
> fix: set streamingClient timeout config

- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
- Repos with large git history can bloom the result of listDirectory by 20x and causes listDirectory to error out
- filter out .git folder from listDirectory
> fix: filter out .git folder from listDirectory

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
We do not currently send the requestId to the chat window for errors thrown during sending the request. We log them but do not make them easily accessible for users to fetch. It was requested that we show this in the chat window
- Add requestId to chat window for `QModelResponse` errors
> fix: add requestId to chat for QModelResponse errors

- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
- ListDirectory result can still include directories which will not help with code analysis task
- Add more common ignore patterns for listDirectory which are safe to ignore
> fix: add more common ignore patterns for listDirectory

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Currently when the chat loads up a UI ready event is sent to the lsp, to load up previous chats and start indexing. If loading of previous chats fail, the LSP process crashes. This is particularly evident when openTab event has not been handled by the client.
An error in that flow should not crash the LSP process or block the rest of the indexing from continuing.
This change surrounds the load chat logic within a try catch of its own to allow the rest of the indexing logic to proceed and not crash the server process
> fix: wrap load chats on ready in try-catch

- chat-client/src/client/mynahUi.ts
- We found bunch of `aborted` error  in Kibana dashboard. Found one root cause, we didn't handle stop chat response if customer closes/removes tab before the chat response completes.
```
[Trace - 8:48:45 AM] Received notification 'window/logMessage'.
Params: {
"type": 4,
"message": "[2025-05-08T15:48:45.239Z] Removing tab: aw1sgj"
}
[2025-05-08T15:48:45.239Z] Removing tab: aw1sgj
[Trace - 8:48:45 AM] Received notification 'window/logMessage'.
Params: {
"type": 4,
"message": "[2025-05-08T15:48:45.239Z] Updating tab open state: historyId=b359f1d7-d7d0-4388-8ad8-60616fd7859e, isOpen=false"
}
[2025-05-08T15:48:45.239Z] Updating tab open state: historyId=b359f1d7-d7d0-4388-8ad8-60616fd7859e, isOpen=false
[Trace - 8:48:45 AM] Received notification '$/progress'.
Params: {
"token": …
```
> fix: stop chat response first when close tab

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- Use the tool icon for read only permission, and use warning icon for file modification in permission check for outside of workspace.
- String should not change after “Allow” is clicked
-  Ignored, Rejected, Failed, and Complete commands should have a disabled grey state for all the text and border (except the status)
- Fixed above issues
https://github.com/user-attachments/assets/dd6fe591-bf47-4aec-a1dc-22f4df6d1e24
> fix: permission check ux changes

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
Disabling local indexing in IDE settings was not reflected in the chat results. The message prompting users to "enable workspace indexing" was never emitted, and query index was still being hit with setting disabled. Vector library instance in controller is always initialized, so checking for its existence is not sufficient for disabling indexing.
Call correct method in trigger context conditional to check for indexing enabled and notify extension if disabled. Additionally, add checks in the local context controller to ensure setting is correctly considered during querying, and cache is cleared upon disable.
> Fix bugs impacting indexing disabled functionality

- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
- Wrong icons for destructive and mutate command.
- Reject button should be more grey out.
- Tooltip for the different kinds of command.
https://github.com/user-attachments/assets/c0b400ac-a032-49d9-bd23-a1f73ebe2168
> fix: show tooltip for warning message and remove the warning text 

- chat-client/src/client/utils.ts
Utilize mynah `visibleName` property ([defined here](https://github.com/aws/mynah-ui/blob/516bc6d17f3461fe7d6f795e405409283103ebcd/src/static.ts#L315)) to make sure the name of the directory listed is displayed correctly. 
Previously if the directory ended with a `/` it would show an empty directory name, as it was trying to use the text after `/` namely an empty string.
Old: directory `foo/bar/` rendered as ``
Fixed: directory `foo/bar/` rendered as `bar`
> fix: add visibleName property to fix empty directory name when the directory ends with a slash

- server/aws-lsp-codewhisperer/src/language-server/netTransform/transformHandler.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
Export results archive is failing if profile arn was not passed with new tranform flow
updated  flow.
Testing - verified with Q As well as transform flow, we can download results
> fix: bug fix for exportResultsArchive to call with profileArn as parameter

- chat-client/src/client/chat.ts
remove @ mention in placeholder q chat text if agentic mode not available
**With agentic mode:**
**Without agentic mode:**
> fix: remove @ mention in placeholder q chat text if agentic mode not available

- server/aws-lsp-codewhisperer/src/language-server/netTransform/resources/SupportedProjects.ts
Now we support 'User.Identity.GetUserName'
Remove 'User.Identity.GetUserName' from unsupportedViewComponents
> chore: update netTransform unsupportedViewComponents 

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- server/aws-lsp-codewhisperer/src/shared/userWrittenCodeTracker.test.ts
- server/aws-lsp-codewhisperer/src/shared/userWrittenCodeTracker.ts
add userWrittenCodeTracker in flare
this is behind a configuration `sendUserWrittenCodeMetrics` since this is currently only sent in VSC and JB
related VSC PR: https://github.com/aws/aws-toolkit-vscode/pull/7281
> feat: add userWrittenCodeTracker

- server/aws-lsp-codewhisperer/src/shared/userWrittenCodeTracker.ts
- use performance.now for both timestamp
- missing return
> fix: bug in skip edit for userWrittenCode

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts
Source code which is created under /test/ or /tests/, they are ignored falsely, same as directory which might have hidden repository before the code package.
Remove them from ignore patterns of glob
> fix: update ignore pattern of glob for sspc

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
Tests runtime jumped up after `responseTimeoutMs` was introduced.
Stub the timeout in tests - it decreases total test runtime from 8 and 9 mins to 7 mins.
> chore: stub timeout

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-partiql-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
This PR bumps runtimes version to latest, and fix a broken test due to new changes in runtimes (removeTools in Agent): https://github.com/aws/language-server-runtimes/pull/501
> fix: bump runtimes and fix broken test

- core/aws-lsp-core/src/util/workspaceUtils.test.ts
- core/aws-lsp-core/src/util/workspaceUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/constants.ts
- FileSearch is returning directories in the result
- FileSearch toolSpec is outdated
- Update fileSearch toolSpec and implementation
- This PR is not enabling the tool, we will test offline first
> fix: update fileSearch toolSpec and implementation

- chat-client/src/client/mynahUi.ts
- Welcome card and Disclaimer card is shown every time if user installs a new plugin or refresh the existing plugin.
- Fixed this issue.
> fix(amazonq): welcome card shows everytime after ide restart

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
Export Q chat in windows was not working
`Received response 'aws/chat/tabBarAction - (7)' in 2514ms. Request failed: Request aws/chat/tabBarAction failed with message: ENOENT: no such file or directory, open 'D:\d:\Users\ABC\CDE\q-dev-chat-2025-05-13.md' (-32603). `
Use fsPath instead of path. Fix tested on Mac OS and Windows
> fix(amazonq): export q chat in windows not working due to invalid path

- .husky/commit-msg
Forcing commit-lint locally is very disruptive. It adds friction to local development, and gains little because:
- commits will be checked in CI
- most PRs are squash-merged anyway
Drop the local hook.
> fix: don't force commit-lint locally

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- In the new agentic chat after a user types a message, it may trigger multiple LLM calls, but we only store the final LLM requestID (cwsprChatMessageId), which is the one that generates the response shown to the user. Earlier LLM calls in the sequence, which handle internal processing and aren't visible to users, are not currently emitted.
- Emit all LLM RequestIDs in the order that these requests were made in amazonq_addMessage
-  Will truncate any RequestIDs after 875 based on limit testing
```
[debug] telemetry: amazonq_addMessage {
Metadata: {
metricId: '8d797efd-7c07-4256-baf0-d20e323a0f0c',
traceId: '51be1d87-e728-4576-bdcb-a60575c780b2',
parentId: '91f1f5fb-18f3-44d2-8617-6b97bd4f83d7',
credentialStartUrl: 'https://amzn.awsapps.com/start',
cwsprChatConversationId: …
```
> fix: add requestIds for each LLM call for amazonq_addMessage metric

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- Existing metrics in agentic chat is missing some fields like agentic coding mode etc.
- Missing tool use latency.
- Addressed the above issues.
- adding a new metric `amazonq_InvokeLLM`
- Implemented additional metrics from these two PR's 
- https://github.com/aws/aws-toolkit-common/pull/1025
- https://github.com/aws/aws-toolkit-common/pull/1027
> telemetry(amazonq): adding new telemetry metrics and addtional fields for existing metrics

- chat-client/package.json
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
- bump @aws/language-server-runtimes-types, @aws/chat-client-ui-types to latest npm versions
> chore: bumping language server runtime versions

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codePercentage.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codePercentage.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetry.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
Comparing to the telemetry sent by VSC plugin, there are some attributes in the telemetries emitted from LS are missing. 
Add missing attributes, testing by adding unit test
> feat: migrate inline completion telemetry to Flare

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
More MCP logic changes
* Support execution timeout for MCP tools
* Add mutex to guard local config file read/write operations and prevent concurrent access issues
* Add new interface for tools and their states to simplify UI integration
* Restructure unit tests into per-method test suites
> feat: support mcp exec timeout, add tool state interface

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
Current export chat functionality doesn't properly handle user cancellation of the save dialog, leading to incorrect telemetry reporting and runs into errors.
- Added proper handling of save dialog cancellation.
- Enhanced error handling to differentiate between user cancellation and other failure cases.
- Updated telemetry emission to accurately reflect the export operation outcome.
Changes include:
- Using string literal types for result states
- Improved logging for different export scenarios
- Consistent error handling across export-related functions
Manually tested the following scenarios:
1. Export to both .md and .html formats
2. User cancellation of save dialog
3. Verified correct telemetry emission for all scenarios
By submitting this pull request, I confirm that my contribution …
> fix: adding error handling for export tab

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
We are still seeing a high number of `Improperly formed request` errors caused by backend validation check failures on the history.
Main categories:
- UserInputMessage must be followed by AssistantResponseMessage
- UserInputMessage content cannot be blank if there are no ToolResults
- Got ValidationError: ToolResult with ID tooluse_ID has no corresponding ToolUse
We also see some `Improperly formed requests` caused by: `'conversationState.currentMessage.userInputMessage.userInputMessageContext.editorState.workspaceFolders' failed to satisfy constraint: Member must have length less than or equal to 100`
Add robust validation checks on the history to match backend checks. Specifically:
- Only validate the last message in history and the incoming user message.
- Enforce user-assistant …
> fix: add robust validation logic to fixHistory

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
1. Need to show fsWrite errors in the UX , not just in the messages.
2. Need to show fsWrite is starting before the entire file write is done.
1. Display fsWrite errors in the UX according to the design
https://github.com/user-attachments/assets/19ca5464-8481-417c-a2d2-08da299b1fa4
3. Render fsWrite progress
https://github.com/user-attachments/assets/0b03604e-fc9a-47a9-b00b-5937c1fd9056
https://github.com/user-attachments/assets/c6b911f1-10a2-4473-b0db-3a2ca97d2c15
https://github.com/user-attachments/assets/a3fd3a76-9ed1-4ac5-87e1-de2234753bfc
> fix: Reduce perceived latency of fsWrite. Show fsWrite errors in the UX 

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
- Bump up language server version to
```
language-server-runtimes: 0.2.83
language-server-runtimes-types: 0.1.29
```
> chore: bump up language server version

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
update server shouldn't re-init server
add update server permission method without re-init server
> feat: add update server permission method without re-init server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
Some customers experience errors due to `Agent loop reached iteration limit`
Remove limit on agentic loop entirely
> fix: remove limit on agentic loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
The client side total character can exceed 600k when chat history is long or context is too long, which result in user seeing 4xx Input is too long. Previously we had a mechanism to drop chat history once input is too long is seen, but we should technically not surface such error to customer to begin with.
Truncate API payload and prioritize them using user input > use selected context > current open editor > chat history. 
The limit is still at 500k characters to leave some room for server side prompts and future work.
> fix: truncate API payload for history, relevant documents and current editor

- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
> When installing the latest VSCode version 1.68.0, from client side logs, server-side workspace context wasn't initialized correctly. 
These logs are critical to determine whether or not certain features are enabled. The log level updates are [sent as a notification](https://github.com/aws/aws-toolkit-vscode/blob/ea593e295bcdc30f29ac2c8960af1fa69c754daa/packages/amazonq/src/lsp/config.ts#L85-L89) so there is no guarantee they are set when the initialization of these servers starts. 
- bump the log levels of these statements to info, which is the default sent to the language server in initialization. 
> feat: bump logging level of critical messages

- chat-client/src/client/mynahUi.ts
Stop text was centered. 
When user enter a prompt to stop the workflow, the stop message would show up after user's new prompt
https://github.com/user-attachments/assets/cc97f1b5-0789-44e0-84d7-996d736469f3
> fix: Stop text align

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
https://github.com/aws/language-servers/pull/1001 (connection expired error handling) was negated by https://github.com/aws/language-servers/pull/1299
add back changes in #1001 and add unit test
> fix: missing handle connection expired error for inline suggestions

- chat-client/package.json
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
We need to setup UX for adding, updating permission for MCP server tools.
- Added events for onMCPServerClick to redirect and open MCP servers permission.
- Added events for mcp server permission changes.
- Added UI objects for disable, delete and enable(No events yet)
https://github.com/user-attachments/assets/ba8cf11f-30ae-418e-b897-2595463a5f98
> feat: setup for MCP servers tools permission UX

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
[In this change](https://github.com/aws/language-servers/pull/1372) we now retrieve the history after truncating the request. This causes the request to be logged without the history included. This will make debugging difficult
Move generateAssistant request log statement to after we have retrieved the history
> fix: move generateAssistant request log statement

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
We need to display number of tools for each MCP server.
- Added tool count to the List MCP server UX.
https://github.com/user-attachments/assets/f1555808-5af9-44c2-81fd-cd231d671bcf
> feat: added mcp tool count to MCP server list

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
When there is a timeout error and/or JSON parse error, etc of the tool use and or a user cancel, the error status was not rendered in the progress fsWrite UI. that UI will remain in progress status.
At those code path of timeout error and/or JSON parse error of the tool use and or a user cancel error, render the error in the fsWrite UI.
https://github.com/user-attachments/assets/c5958360-1712-462b-b9f1-82f728de9be1
This was tested by manually injecting errors including timeout error, JSON parse error, etc.
> fix: Render timeout error, JSON parse error, cancellation to the in progress fs.write UI

- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- agentic chat didn't send failed and cancelled event to RTS
- update RTS model, related cr: https://code.amazon.com/reviews/CR-195724096
- copy the model change from [codewhispererruntime-2022-11-11.api.json](https://prod.artifactbrowser.brazil.aws.dev/packages/AWSVectorConsolasRuntimeServiceModel/versions/1.1.4900.0/platforms/AL2_x86_64/flavors/DEV.STD.PTHREAD/smithyprojections/AWSVectorConsolasRuntimeServiceModel/aws-sdk-external-2022-11-11/c2j/codewhispererruntime-2022-11-11.api.json), run `npm run generateClients` and updated [codewhispererbearertokenclient.d.ts](https://github.com/aws/language-servers/compare/main...yueny2020:language-servers:rts-telemetry-event?expand=1#diff-78dca2db09279e2b8e1c808726c59f78ecc55ded0b6581b76f904ae6bf0a1006)
- emit events for failed and cancelled …
> fix: emit telemetry event to RTS when failed or cancelled

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- When reinitializing McpServers, we were originally resetting the singleton instance. Then on refresh, the tools server would not register the server tools
- Do not reset singleton instance so on refresh, it will register server tools
https://github.com/user-attachments/assets/73bfd6df-487e-417f-8cf6-71df4e54d83b
> fix: refresh button should register tools in tool server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
If a user stops the agentic chat mid-execution while the request to Q is in-flight, we abort the request. However, we are currently surfacing that request to customers
Swallow exception and handle it in `isUserAction`
> fix: handle requestAborted errors silently

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
When a new prompt was sent while the first was still processing, the telemetry emission for the cancelled prompt was happening before the request was aborted, which prevented the system from properly handling the second prompt.
Moved the telemetry emission to occur after the request is aborted
https://github.com/user-attachments/assets/d60d4ed2-b31a-496d-8147-800bc864721b
> fix: the new prompt wont stop the process properly

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
We want WorkspaceContextServer still being able to run even if extensions are running on old versions and not passing a workspaceIdentifier to WorkspaceContextServer.
Generate a temporary workspaceIdentifier if not given
> chore: generate a temporary workspaceIdentifier if not given

- server/aws-lsp-codewhisperer/src/client/sigv4/codewhisperersigv4client.d.ts
- server/aws-lsp-codewhisperer/src/client/sigv4/service.json
- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
In order to coordinate the new [aws/language-servers](https://github.com/aws/language-servers/pull/1348) change, GenerateCompletions requests would start expecting the `fileUri` field to be set.
We implemented this in both VSCode and JetBrains extensions, but as we are migrating GenerateCompletions away from them to `aws/language-servers`, we also need to ensure they are added in the relevant code paths here.
- https://github.com/aws/aws-toolkit-vscode/pull/7294
- https://github.com/aws/aws-toolkit-jetbrains/pull/5732
Add `fileUri` to FileContext
> feat: add fileUri to FileContext

- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
The IAM `SendMessage` streaming client uses the `source` parameter to route the request, we currently don't set this parameter resulting in incorrect routing. For example, even when setting the `chatTriggerType` to `INLINE_CHAT` the IAM chat client still responds with natural language.
We set it to `IDE` to route it to the right back-end.
- Verified that the IAM chat client now responds with just code when passing the `INLINE_CHAT` trigger type.
> Set `source` parameter chat request context to 'IDE'

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
https://github.com/aws/language-servers/pull/1389 this change broke LSP initialization as the file does not add the required import for crypto. 
Added the required import
> fix: add crypto import

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
We need to support persona file and move all permission settings into it.
https://quip-amazon.com/B3Z9ADFBZxHi/Agent-personas-in-Q-Developer-CLI-and-IDE
Support persona file
* Fix remaining issues from front end integration.
* There is also requirement changes that not been addressed yet like the default content in persona file, which needs to be addressed.
* Manual test all permission use cases
* Rewrite broken uni tests
> feat: support persona file for MCP permission

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
When '*' is used in persona enable/disable not properly handled
If a server is disabled and '*' is used, add all the remaining severs in mcpServers list
> fix: handle wilcar for enable/disable server

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
We need correct icons displayed for server state
- Adds icons according to server state.
> feat: adding correct icons for MCP servers state

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- after successfully adding mcp server, it stays on the same page. it should go to permissions page
- after failing to add mcp server, it does not show error card to user. it should stay on the page while showing error card to user
- after successfully adding mcp server, goes to permissions page
- after failing to add mcp server, shows error card to user
- currently only validation is checking that name, command, and timeout have been inputted. more validations are needed in a followup
- data will persist so user will not have to retype everything
- persist scope (global or workspace) on success case 
- manually tested:
- happy case for adding mcp server --> goes to permissions page
- with missing name, command, timeout -->  stays on same page, error card shown at top, and data persists …
> fix: success and error case for adding mcp server

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/DependencyWatcher.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JSTSDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JavaDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/LanguageDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/PythonDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
1. Symlink inside dependency folder wasn't resolved and didn't get uploaded
2. Dependency watcher can crash Flare when there are lots of file events happening to file watcher.
1. Resolve symlink
2. Bundle events for file watcher
> SSPC dependency upload and watcher fixes

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
We need to add Built-in tools in mcp server list to setup permissions. and there is an issue with splash loader closing once server initialization completes.
- Fixed splash loader once server initialization completes.
- added built-in tools in UX for non-mcp tools
- added permission check for permissions from persona.
- fixed permission duplicates.
- fixed permission propogation.
- bug with saving permission and it reverting when loading for both built-in and mcp tools.
> feat: added built-in tools with proper permissions

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContexts.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
There is uncaught exception thrown from a Promise. The Promise get replaced by new one and when rejection happened on the old promise, there is no try catch block to catch it. 
Instead of rejection, we are using resolve to ensure the functionality of waiting snapshot set.
> fix: fix uncaught exception in workspaceFolderManager

- chat-client/src/client/mynahUi.ts
- If user click on close it return previous menu instead should return to chat menu.
- Fixed this issue.
https://github.com/user-attachments/assets/cba29443-32a2-4796-88ac-92fd863c116e
> fix: closing mcp servers and each server should return to chat

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- Removing `edit config` text from add mcp config.
> fix: removing edit config text from add mcp config 

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Q CLI uses delimiter `___` in namespace between serverName and toolName
To align with Q CLI, Q IDE also uses delimiter `___` in namespace between serverName and toolName
> fix: use delimiter ___ between serverName and toolName for MCP

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
Line numbers displayed in the webview were off by 1 when showing code symbol ranges. This is because the editor's internal line numbering starts at 0, but UI displays typically show line numbers starting at 1. This inconsistency affects all IDEs and creates confusion for users when they see line numbers that don't match what's shown in their editor. 
VS:
VSC:
JB:
Added +1 to both the start and end line numbers when displaying the line range in the code context command description. This ensures that the line numbers shown in the UI match what users see in their editor interface, providing a consistent experience across all IDEs.
> fix line number display in code context commands

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- If there is any syntax error like Invalid mcp.json error or any configuration error. This wont show up at the list of MCP servers UX.
- No proper error handling.
- Fixed above issues
- Added valid test cases
https://github.com/user-attachments/assets/5a275a05-1cd5-411e-8d2b-7d82d4abd7bf
> fix: adding error handling for config load errors to display them to ux

- app/aws-lsp-codewhisperer-runtimes/src/agent-standalone.ts
Adding `WorkspaceContextServerTokenProxy` to the agent-standalone bundle so that the bundle used for local testing 
> chore: add workspace context server to the agent-standalone bundle

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.test.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
This change adds tests for changes introduced in PR #1479 to add support for updating context commands on `didWorkspaceFoldersChange` event.
This change also converts the void call of `updateIndexAndContextCommands` to await within the updateworkspacefolders call
> fix: add tests for PR#1479 that added support for updating context commands

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
1. Update title description in MCP List of servers
2. In Chat summary card view the explanation is missing on top of chat summary card view.
3. Need to remove Icons of Disable and delete servers in Permissions page.
4. Enable servers icon is different from the UX in MCP Servers page.
5. “Delete option” will not show the modal view in the MCP Servers page.
1,4
5
2
3
> fix: ux fit and finish task and adding explanation to chat summary card

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/shared/testUtils.ts
Inline completion request should send the `filename` field with the relative path of the file instead of just the base name, which would benefit model generation quality.
Related PR on VSCode side for more context: https://github.com/aws/aws-toolkit-vscode/pull/5543
Send relative file path for the `filename` field for inline completion.
> feat(amazonq): send relative file path for inline completion

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTypes.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
QCLI decided to use json for persona and also need some default values, we need to aligned in order to not breaking QCLI user. 
Change persona file to json, add default permissions.
> fix: use json for persona, add default persona

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- fsRead on Windows doesn't properly format the path array, causing file read failure.
- fix paths array not being respected by LLM for fsRead tool
Now the fsRead succeeds on the first run.
> fix: fix paths array issue in fsRead

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
We can not remove the mcp servers which failed initialized
https://github.com/user-attachments/assets/1d90a00c-7e04-4d5f-8951-570547f239b0
> fix: add remove function for inactive mcp server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
When user ask agentic what tools it has, if users ask multiple times, the tool name agentic return would with numbers. 
Add a clear function to reset the Set so every time we truncate the same server_tool, it would be the same name.
> fix: clear the set to make sure truncate function work as expected

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
In the first request in a session, below, it truncates left/right context, but didn't store them in the session,
when sending the second request it should use the same truncation logic.
> fix(amazonq): pagination request should also used truncated left/right context

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- When updating a server and not including any args or env variables, it would update the mcp.json file with an empty args list or empty env variables like this:
```
{
"mcpServers": {
"json": {
"command": "npx",
"timeout": 0,
"args": [
"@gongrzhe/server-json-mcp@1.0.3"
],
"env": {
"": ""
}
}
}
}
```
- After updating server in UI without any args or env variables, mcp.json file will look like this:
```
{
"mcpServers": {
"json": {
"command": "npx",
"timeout": 0,
"args": [
"@gongrzhe/server-json-mcp@1.0.3"
]
}
}
}
```
https://github.com/user-attachments/assets/85b55a30-42bb-4c07-ac72-9e15ea27193a
> fix: do not have empty args or env in config while updating server

- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
The indexing library does not properly support Windows ARM64 and is causing the Flare process to blow up during initialization.
Long term we need to add proper support for ARM64. As a short term workaround we need a switch to be able to bypass indexing library initialization in cases like these.
> Add environment variable override to disable indexing library init

- chat-client/src/client/mynahUi.ts
Issue from bug bash:
- In "MCP servers" table, make the entire row (highlighted in red rectangle in the screenshot) clickable. Users are not going to know that they need to click on the small ">" icon on the right to view details.
- first row highlighted by default
- still a blue outline around the first mcp server even when selecting another mcp server
- same issues with history tab
https://github.com/user-attachments/assets/3501898e-f5f0-458d-86bb-611b5db9c46d
> fix: make whole row clickable in mcp servers list view

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- Address some of Arun's P0 bugs
1. Default persona file does not match spec
2. Tool permission labels does not match persona file 
1. toolPerms for `execute_bash` and `use_aws` need to be:
```
"alwaysAllow": [ 
{"preset": "readOnly"}
]
```
2. Change the tool permission labels as follows:
- "Ask to run" --> "Ask"
- "Always run" --> "Always allow"
- "Disabled" --> "Deny"
> fix: update default persona file spec and  tool permisions strings

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- Permissions are not being loaded correctly from the persona file. Therefore are not being honored properly.
- mcp config file is being edited incase of mcp server initialization failure.
- fixes persona file loading with wildcard for permissions.
- honors permission accordingly during tool executions
- logging for errors
- Removing mcp server from config file incase of failure in initialization.
> fix: fix to correctly load the permissions

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- Don't show MCP server initialization errors in the MCP overview screen. (As if there are a lot of MCP servers each with long error messages, this can get overwhelming.) 
- The only error which will show on list mcp servers screen is if they have an invalid mcp.json config file
- If there are server specific errors, user will click see this error once they click into an MCP server
https://github.com/user-attachments/assets/e7a76236-e391-4f89-a3a0-e0458f1e98bf
> fix: only show invalid json error on list mcp server page

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
When an mcp server is enabled, all servers are getting refreshed.
- fix to refresh only one server that is enabled
> fix: fix to refresh only one server that is enabled

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
We receive `Improperly formed requests` failures due to: `Message with ToolResults must be preceded by AssistantResponseMessage`
There is an edge case where when the context size is exceeded, we remove the history entirely if we cannot find a valid userInputMessage without toolResults to trim up to. This results in validation issues on the backend if the new UserInputMessage contains toolResults (there is no existing previous message with toolUses to pair with the toolResult).
Short-term solution: Abandon the toolResult for this case and inform the LLM that the context limit was execeeded.
This is the current approach done by CLI: https://github.com/aws/amazon-q-developer-cli/blob/main/crates/cli/src/cli/chat/conversation_state.rs#L327
TODO:
Long-term: Come up with a way to preserve the …
> fix: handle dangling tool results when history is cleared due to size limits

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
1. Inconsistent Error Handling Across IDEs 
Currently, Flare throws _QModelResponse_ errors directly, requiring each IDE to catch and handle them separately, which leads to inconsistent UI experiences across different IDEs compared to VS Code.
2. Model Selection Error Code Issues
_QModelResponse_ errors don't send a error code back to IDE, as we only receive a body with errorMessageId inside instead of standardized error codes, which makes us hard to have a generalized way to handle logic for QModelResponse Error. 
VS Code as a source of truth tries to show the error message from QModelResponse error directly to chat UI. We've modified the error handling approach to return a result instead of throwing exceptions for QModelResponse errors. This ensures that errors are displayed …
> fix: return QModelResponse as a response not an error

- chat-client/src/client/chat.ts
- chat-client/src/client/messager.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/texts/paidTier.ts
- chat-client/src/client/withAdapter.ts
- chat-client/src/contracts/chatClientAdapter.ts
- server/aws-lsp-codewhisperer/src/client/sigv4/codewhisperersigv4client.d.ts
- server/aws-lsp-codewhisperer/src/client/sigv4/service.json
- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts
- server/aws-lsp-codewhisperer/src/language-server/paidTier/paidTier.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/errors.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
When "free tier" limit is reached, there are no clear next steps.
- Handle "free tier exceeded" throttling/quota service error: show a chat card with an `Upgrade` button, and an IDE message.
- Handle the "Upgrade" button event.
- Wait for upgrade to complete, show a message on success.
- Handle the `aws/chat/manageSubscription` command, so clients can invoke the "Upgrade" codepath.
Related IDE changes:
- VSC: https://github.com/aws/aws-toolkit-vscode/pull/7379
- JB: todo
- VS: todo
```
1) MynahUI
openTab
should create a new tab with welcome messages if tabId not passed and previous messages not passed:
AssertError: expected getChatItems to be called once and with exact arguments 
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> feat(q): builderid "paid tier" flow

- chat-client/src/client/tabs/tabFactory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
When user failed adding a MCP server, the error is not been proper logged and it's very confusing.
Classify three different kinds of logs to make it clearer to user what happened when they failed adding a mcp server
> fix: add more detailed log when mcp server initialize failed and tooltip change

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
We want to skip sending websocket request when uploading to S3 fails
Let `uploadToS3` function return `undefined` to the callers when there is an exception.
> fix(amazonq): skip sending websocket request when uploading fails

- chat-client/src/client/mynahUi.ts
- chat-client/src/client/texts/paidTier.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/errors.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
- Fix spinner placement.
- Ensure "upgrade successful" notification happens without needing to switch tabs.
- Check for pro-tier before showing the "Upgrade to Pro" message.
- limit reached
- <img width="1495" alt="image" src="https://github.com/user-attachments/assets/fcec4534-9458-4a6b-905a-0d743476652b" />
- upgrade in progress
- <img width="402" alt="image" src="https://github.com/user-attachments/assets/ca5f022b-a268-4750-a2aa-36b297739a1a" />
> fix(paidtier): "Upgrade success" message is unreliable

- chat-client/src/client/tabs/tabFactory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- wrong icon for mcp
- when adding an invalid mcp server and pressing save, scope would change from global to workspace
https://github.com/user-attachments/assets/181ae952-b122-4250-86a5-27660dbb1d33
- correct icon for mcp according to figma
- when adding an invalid mcp server and pressing save, scope will persist to whatever user chooses
https://github.com/user-attachments/assets/8460d04f-96f4-439d-b8dc-2800f3a9ffa9
> fix: correct icon for mcp button

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
When user remove a server, we did not remove the server's tool name from set. Which might case when next time user add the same server, there would be a conflict when we create name mapping for serverName_toolName
https://github.com/user-attachments/assets/6ffd66fb-3054-4e7f-98ec-fbc71203d526
(00:00:55 in this video)
We are removing the tool name in set for creating the Map. To make sure when user remove the sever, the tool would be completely removed from the memory as well.
https://github.com/user-attachments/assets/86648754-9555-4e9f-8472-b8959e2181ff
> fix: remove the tool from the mapping after user delete the server

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/LanguageDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
Currently, workspace context workflow is creating zip files and writing them to disk before further processing (uploading to S3, sending notification to backend, etc.), however, when examining the logic, there is no place where it reads from these zip files.
We should avoid saving these unused files to reduce disk usage and prevent leaving residues on users disk.
Remove storing zips under `workspaceContextArtifacts`
Tested locally and verified that:
1. Zipping and uploading logic works correctly as before.
2. No temporary files are created under `/tmp/aws-language-servers/workspaceContextArtifacts` anymore.
> fix(amazonq): remove storing zips under workspaceContextArtifacts

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
Right now, we are checking remote workspace status even when there is no workspace folders, for example, when chatting to Amazon Q in an IDE window without opening any folder or workspace.
Skip checking remote workspace status when no workspaceFolders.
Tested the logic:
> chore(amazonq): skip checking remote workspace status when no workspaceFolders

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants.ts
Clients are using the default value of sonnet 3.7 even though dropdown has not been enabled yet
Temporarily set default model to undefined
> fix: default model should be undefined until feature is enabled

- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatHistoryMaintainer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatHistoryMaintainer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
1. Current history logic is mixing up the history sent to service and the history persisted in disk.
2. The limit on history size is 600,000 chars or 250 messages, which is way to small.
1. Separate the "fix history" logic for service requests and DB
- History for service requests:
- Length is less than 250 messages(ensured when retrieving from DB) and 600,000 chars
- Drop the last empty assistant message and the user prompt before that
- Ensure the messages have a valid sequence - alternating sequence of user prompt followed by a assistant message
- Validate and fix tool usage
- Persisted history in DB:
- addMessage now skips empty assistant message
- (Already in place) Skip adding message if the agent loop is cancelled, this is likely the root cause of incorrect message sequence.
2. …
> feat: apply a max 200MB total history size

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
Currently, clients/IDEs pass if model selection is enabled in webview provider to hide/show the model selection dropdown. However, extensions should be data-driven in indicating to chat UI if model selection is available from server side. 
Server could pass its ability of model selection in ChatOptions of awsServerCapabilities during Initialize handshake happened. Then, the clients would be purely data-driven to reduce blast radius. 
> chore: pass modelSelection as true in ChatOptions to IDE

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/quickActions.ts
/manage option are shown in the / popup in the chat prompt. This option was put in place with the builder-id paid tier launch. However, is not a requirement. 
This PR removes the /manage option from quick actions
> fix: remove /manage options from the chat prompt popup

- chat-client/src/client/mynahUi.ts
- chat-client/src/client/texts/modelSelection.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
For better customer experience, we are showing throttling message as an error card instead of a chat message. 
VSC:
JB:
Note: To unblock release, there will need to be another PR to update MyNahUi version once they released the new version. 
> feat(amazonq): model throttling message as card instead of chat message

- server/aws-lsp-codewhisperer/src/language-server/netTransform/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/models.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/converter.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/mockData.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
This PR adds support for WebForms to Blazor transformations by introducing a new `EnableWebFormsToBlazorTransform` flag in the netTransform component. This flag works similarly to the existing `EnableRazorViewTransform` flag and allows the IDE to specify when WebForms to Blazor transformations should be enabled.
- Added `EnableWebFormsToBlazorTransform` flag to the `RequirementJson` interface
- Added `EnableWebFormsToBlazorTransform` flag to the `StartTransformRequest` interface
- Updated the `createRequirementJsonContent` method to include the new flag in the generated JSON
- Updated test files with appropriate default values for the new flag
All existing tests pass, confirming backward compatibility with existing functionality.
This change supports the new WebForms to Blazor …
> Add WebForms to Blazor transformation support

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
When user add a new server, even if there is a project level persona, it would still load global persona first.
1. instead of setting personaPath as globalPath inside #handleSaveMcp, we are calling #getPersonaPath() to get persona 
path.
2. After user remove a mcp server, we should not refresh the whole list, it would cause unnecessary time consuming and resource usage.
https://github.com/user-attachments/assets/c9eca4fa-05cd-4a1a-a514-babe89238cf9
> fix: when user add a new server, it would load global persona at first time

- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
- requestHandler is not set correctly for SDK v3
-  use NodeHttpHandler when configuring requestHandler
> fix: use NodeHttpHandler when configuring requestHandler

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- if multiple timeouts happen in the same loop, only the first timeout will be auto-retried, the second timeout would lead to stuck request
- Properly clean timeout after it happened so that the next auto-retry for timeout will work as intended
> fix: timeout auto-retry only works for the first time in the loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- When we send followup toolUse/toolResult request loop, we still include IDE context which is not needed and can confuse the model
- clear IDE context for toolUse/toolResults requests not initiated by the user
> fix: clear IDE context for followup toolUse/toolResult loop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- missing some latency metrics which is required by science
- `amazonq_invokeLLM` metric has these fields:
- `llmLatency`: time of LLM request until when the full response comes back from LLM and is processed
- `toolCallLatency`: time between when user requests to use a tool, and when the user sees the tool has finished executing
- `timeToFirstChunk`: time of when the LLM request is sent, and when the user sees the first token in the LLM response, ie ("Hi")
- `timeBetweenChunks`: the time in between each chunk coming in from LLM response stream (The first chunk might be "Hi", the second chunk is "I want", the 3rd chunk is "to help", etc)
> fix: add latency metrics for invokeLLM metric

- chat-client/package.json
- package-lock.json
The new mynah-ui version has a bug where the `Pin context with ⌥ Enter` hint should not be displayed in the quick action overlay (when typing /), since the overlay lists quick actions, not context items.
https://github.com/aws/mynah-ui/releases/tag/v4.35.5
Upgrade to the latest mynah-ui version
> chore(amazonq): bump mynah-ui to 4.35.5

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpTool.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Current tools setup for MCP servers follows mcpServerName___toolName format. product requirement is to send just tools with tool names and include serverName as prefix only in case a tool has duplicate/ other tool with same name.
- Updated to use only toolNames and removed serverName from request.
> fix: update MCP tools implementation

- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
> chore(amazonq): nep cherrypick codewhispererService.ts

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
This reverts commit 4272eec6ce4554560fdf8888d85d31315db2d964.
Locking the previous version of `main`  to fasten the current deployment needed.
Will add the commit back after the current deployment.
Revert "fix(amazonq): filter languages at workspace context server onDeleteFiles (#1684)"
> Revert "fix(amazonq): filter languages at workspace context server onDeleteFiles (#1684)"

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/fileUploadJobManager.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
We observed that individual users are generating excessive API call volume to the `CreateUploadUrl` endpoint in a very short period of time (milliseconds).
This occurs when the LSP processes large batches of file events and sends them to the workspace context server. Since these file events are processed in parallel, they trigger simultaneous S3 upload requests, creating traffic spikes that impact backend performance (for example, cache miss leads to extra load to downstream services).
Serialize S3 uploads for file events from workspace context server, which includes:
- onDidSaveTextDocument
- onDidCreateFiles
- onDidRenameFiles
Tested that events are sent to the backend instance and processed correctly with this change.
By submitting this pull request, I confirm that my contribution is …
> fix(amazonq): serialize S3 uploads for file events from workspace context server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Explanation field is causing failure for users running remote mcp using `npx`, as this field is getting blocked since it was an additonal field added by us.
- Removed explanation field from tool input schema.
> fix(amazonq): removed explanation field for mcp servers

- server/aws-lsp-codewhisperer/src/shared/telemetryUtils.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetryUtils.ts
IDE mapping for STE API is incorrect based on what Visual Studio and Eclipse sends. [Visual Studio'](https://github.com/aws/aws-toolkit-common/blob/a0f5c9f5e5a99294d41a87662e68bf69400be4f5/telemetry/service/service-model.json#L47)s and[ Eclipse](https://github.com/aws/amazon-q-eclipse/blob/3f9a056fc813caa6c0e74cb0a2dc2aae514f6100/plugin/codegen-resources/service-2.json#L66) is defined in the telemetry module which does not match the values used in the mapping.
This change fixes it to match expected values sent by the clients.
> fix: ide mapping for VS/Eclipse for send telemetry API

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsReplace.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsWrite.ts
File operation errors should be visible.
- Map file operation errors to user-friendly error messages
- Surface error message to the error status description so that it appears on hover
> feat: surface file operation errors in tooltip

- core/aws-lsp-core/src/util/workspaceUtils.ts
LLM can respond with case insensitive responses which breaks our path.relative function 
hence handling this for mac and windows so that files which are in the workspace are not marked as out of workspace. 
> fix(amazonq): workspace files being tagged as out of workspace issue

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
fsReplace tool is still available when agentic mode off. Which is not expected.
Add fsReplace to writeTool Set
https://github.com/user-attachments/assets/6744385e-ee31-40da-b0aa-3cd442c5de4a
> fix: fsReplace still available when agentic mode off

- chat-client/src/client/mynahUi.ts
Intermediate file cards are not rendered correctly with a border because `fullWidth` is not set correctly.
Before:
After:
> fix: intermediate file card does not have border

- server/aws-lsp-codewhisperer/src/language-server/localProjectContext/localProjectContextServer.ts
- When adding, deleting, or renaming a file on Windows, it does not properly retrigger indexing and therefore, the context list is not updated accordingly. This means that a user won't be able to reference `@fileName` after creating a file in the IDE (i.e. File -> New File). 
- Use `URI.file()` instead of `URI.parse()` as `URI.file()` preserves the Windows drive letter 
- On Mac
- URI.parse(): `/Users/chungjac/repos/tempFolder/abc.py`
-  URI.file(): `/Users/chungjac/repos/tempFolder/abc.py`
- On Windows         
- URI.parse(): `\\Users\\chungjac\\repos\\tempFolder\\abc.py`
-  URI.file(): `c:\\Users\\chungjac\\repos\\tempFolder\\abc.py `
-  Now on windows, a user will be able to reference `@fileName` after creating a file in the IDE (i.e. File -> New File)
- Separate known issue:
- When a …
> fix: adding files on windows properly triggers reindexing

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsReplace.ts
- Model hallucinates and wraps the array in quotes
- Update fsReplace toolSpec to emphasize JSON array syntax
> fix: update fsReplace toolSpec to emphasize JSON array syntax

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/editPredictionAutoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/tracker/codeEditTracker.ts
> fix(amazonq): nep trigger detection should use file uri but filename is used

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
While auditing the API usage for the recent goal to reduce the call volume to backend `ListWorkspaceMetadata` API, we noticed that there is one unnecessary `listWorkspaceMetadata` call within `processNewWorkspaceFolders()`, whose original purpose is to detect user server-side opt-out behavior and has been covered by `listWorkspaceMetadata` invocation within `checkRemoteWorkspaceStatusAndReact()`.
We should delegate the user server-side opt-out detection to the same place (`continuousMonitorInterval`) and avoid this unnecessary call.
Avoid calling `listWorkspaceMetadata` within `processNewWorkspaceFolders()`
> fix(amazonq): save one unnecessary listWorkspaceMetadata call

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/client.ts
We need to prevent the thundering herd problem when there is a network issue or backend issue causing a large amount of WebSocket clients disconnected.
Introduce randomness into the timing of retries to avoid simultaneous requests to re-establish WebSocket connection.
> fix(amazonq): add jitter for websocket client re-connections

- app/aws-lsp-codewhisperer-runtimes/package.json
- package-lock.json
- package.json
- server/aws-lsp-codewhisperer/package.json
The internal build failed because package.json and package-lock.json is not in sync. 
> fix: move ignore walk from app/package.json to server/package.json

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
We were printing the chat processing stopped acknowledging message in the wrong order where it was coming after the new message. 
We moved the message publication to the mynah.ts file so that we can handle it at source and hence we dont publish it after the message is published.
> fix(amazonq): fix the order of publishing the chat stop ack message

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Many MCP servers do not allow custom fields in tool schema like `explanation` which we use to add a directive message for tool executions. The  mcp tools are breaking and initialization is failing due to this.
- Added explanation back to tool schema.
- removed it right before user facing messages with parameters and tool execution.
> fix(amazonq): fix to include explanation field in mcp tools schema

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/documentContext.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
- When there are multiple workspace folders, the model needs to guess which folder is the relativePath for
- add workspace folder to the relativePath so that model knows the correct full path without guessing
> fix: add workspace folder to the relativePath

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
empty prediction type will case 4xx error
> fix(amazonq): return empty if nep auto trigger is not triggered

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- Init all MCP servers in parallel could slow down plugin initialization if there are high number of MCPs as Promise.all() itself doesn't have a built-in limit
-  Process servers init in batches of 5 at a time
- before
https://github.com/user-attachments/assets/df3dc75a-ccda-418c-b0f9-f15f596548d5
- after
https://github.com/user-attachments/assets/2fdb9fde-1119-4f48-93ca-5b5ea2067cf3
> fix(amazonq): init mcp servers in batch of 5

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- ToolSpec is not included in the character count when we decide to trim the history. With MCP, the toolSpec can be large and cause Input to exceed context window
- Include toolSpec character count for history trimming
```
2025-06-26 16:12:17.211 [info] [2025-06-26T23:12:17.206Z] Current history characters: 435
2025-06-26 16:12:17.212 [info] [2025-06-26T23:12:17.206Z] Current user message characters input: 98 + toolSpec: 5082
2025-06-26 16:12:17.213 [info] [2025-06-26T23:12:17.206Z] Current remaining character budget: 564820
```
> fix: include toolSpec count for history trimming

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
Grep search command is not present in readonly commands prompting repeasted permission breaking user experience.
- updated the read only commands list to include grep
> fix(amazonq): fix to add grep to read only commands

- chat-client/src/client/mynahUi.ts
Text was coming in the chat before the UI card.
Added slight delay to get it to come after. 
> fix(amazonq): add slight delay to print chat string after card

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/mergeRightUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/mergeRightUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/shared/testUtils.ts
Currently all previous suggestions are discarded before generating new suggestions.
add logic to merge with previous suggestions for EDITS
> feat: add logic to merge with previous suggestions for EDITS

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
In the non-Flare auto trigger for VSC and JB, we do not auto trigger when there is immediate right context.
But when switch to Flare, we are triggering. 
See https://github.com/aws/aws-toolkit-vscode/blob/amazonq/v1.74.0/packages/core/src/codewhisperer/service/keyStrokeHandler.ts#L102
This causes API request to increase a lot.
Do not auto trigger when there is immediate right context.
We are not changing Eclipse and VS because these products were using the Flare auto trigger to begin with. Changing this affects user experience
> fix: do not auto trigger when there is immediate right context for VSC/JB

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/coefficients.json
The VS Code coefficient should be -0.1905. See https://github.com/aws/aws-toolkit-vscode/blob/amazonq/v1.74.0/packages/core/src/codewhisperer/service/classifierTrigger.ts#L77
With the -0.13566, we will be making more auto triggers
Revert the VSC coefficient to the previous one.
> fix: adjust vs code auto trigger coefficients

- chat-client/package.json
- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/tabs/tabFactory.ts
- chat-client/src/client/texts/pairProgramming.ts
- chat-client/src/client/withAdapter.test.ts
- chat-client/src/client/withAdapter.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/qAgenticChatServer.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/configuration/qConfigurationServer.ts
- Q IDE is transitioning its /test, /dev, and /doc agents to use the new Q Agentic chat capabilities, while /review and /transform agents will continue using the original mechanisms.
https://github.com/user-attachments/assets/d43c585b-6fad-4749-b0d0-b422c778bc01
> feat(amazonq): migrating / agents to q agentic chat

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
We observed that if there is a workspace folder like `file:///someFolder` and an event for a file like `file:///someFolderAndSuffix/file.txt`, the workspace folder will be wrongly matched by the `findWorkspaceRootFolder()` function.
Added a forward slash at the end of the `workspaceFolder` path when checking whether a file belongs to a workspace folder. 
> fix(amazonq): prevent WCS matching workspaceFolder with only prefix

- server/aws-lsp-codewhisperer/src/shared/languageDetection.ts
Data plane requests coming to RuntimeService have normalized language field (e.g. recognizing `tsx` files as `typescript`), so those files are accepted correctly in the backend.
However, workspace context server is not normalizing the language type when checking files, which makes those files being ignored:
https://github.com/aws/language-servers/blob/233c7d7c86d0be3960175a9fcbff594665581515/server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts#L21
Normalize language type when workspace context server checking whether a file should be included or not.
> fix(amazonq): include tsx and jsx files in workspace context server

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
We were wrongly tagging the message as a file inside the workspace. It should have been outside of the workspace.
Changed the message.
> fix(amazonq): change the UI message from to out of workspace

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
> fix(amazonq): shouldn't exit inline  flow before we're sure there is no Edit/Completion trigger

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
> chore(amazonq): manual trigger should always assign Completions prediction type

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
Service validation fails for descriptions crossing 10240 characters. This causes chat wise failures if we add an MCP tools with longer description than limit.
- Added upper limit validation for tool description in initialization.
> fix(amazonq): fix to add upper limit validation for tool description

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/pathValidation.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/pathValidation.ts
Sometime due to different reasons if LLM gave us undefined paths our tools would not perform correctly as we would start to ask for permissions for out of workspace access for them.
Added check for filePath and used the existing retry mechanism to retry with LLM.
> fix(amazonq): handle undefined paths gracefully and retry

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/shared/constants.ts
We are starting a new A/B testing experiment called `BuilderIdServiceSideProjectContext` for BuilderID users.
Also, we are going to switch all internal users to another experiment that needs workspace context server enabled.
Allow `BuilderIdServiceSideProjectContext` for WCS A/B testing.
Set WCS `abTestingEnabled` to true for all internal users.
Tested locally with my Amazon internal user credentials and verified it works.
> feat(amazonq): update workspace context server A/B testing filter

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
During integration of Flare changes with Visual Studio, following bugs have been identified
- On windows, when we add an image using the options @image or @image: options, full file name is shown, we should only show file name.
- I was able to add only one image when I used @image context menu option, when I add another image, it does not show up in pinned context.
Images for the these bugs are below.
- After fixing these issues.
> fix: imagecontext image name bug, mutliple images in pinned context

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/contextCommandsProvider.ts
There's grammar mistake in the context list 
Fix the grammar mistake
> fix(amazonq): fix grammar mistake in image context list

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
passing partialResultToken to onInlineCompletionHandler result for EDITS
> feat: passing partialResultToken to onInlineCompletionHandler result for EDITS

- chat-client/src/client/chat.ts
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
Clients need a way to override Mynah-UI strings. For example, a "workspace" in one IDE might be called a "project" in another IDE. Or when displaying keyboard shortcut hints, an IDE might want to display `Alt Enter` instead of `⌥ Enter`.
Add an optional `stringOverrides` property to ChatClientConfig. This allows clients to override Mynah-UI [ConfigTexts](https://github.com/aws/mynah-ui/blob/aabb08d924a27ba19a0db3b01c3e3e371e7f6226/src/static.ts#L726) by passing in strings to createChat.
> feat(chat-client): add stringOverrides to createChat config

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- Missing telemetry fields like agenticCoding fields in `amazonq_addMessage` if the result is `Failed` or `Cancelled`
- Fixed this above issue.
> telemetry: adding agenticCoding field to amazonq_addMessage metric

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- Use absolute file path when invoking shell
> fix: use absolute file path for shell

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
Currently, We didn't have the full system information in logs and were asking users to collect it when submitting tickets.
Added the system information to the logs.
System Information: {"languageServerVersion":"0.1.0","clientName":"vscode","clientVersion":"1.101.2","OS":"darwin","OSVersion":"24.5.0","ComputeEnv":"unknown","extensionVersion":"testPluginVersion"}
> feat(amazonq): added full system information to the logs

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
This reverts commit 7052132a5198944ef05ddbf857d622ba518e71da as telemetry event is broken.
> revert: adding streakLength back for UserTriggerDecisionEvent

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
Trust mode/auto-approve mode in execute bash tool needs additional security measure.
- additional checks for binary and credential files
> fix(amazonq): additional checks for binary and credential files

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
After we migrated inline completion to Flare, we are seeing a 30%+ throttling rate for inline APIs. This rate had been very high for Eclipse since Feb 2025. The server side throttling is 1TPS. 
As user types in the IDE, the `onInlineCompletionHandler` will be invoked per user typing, but this function is not designed to properly handle concurrency. And in the old VSC/JB inline completion, we block such concurrent request, instead of keeping firing and discard the old request. 
As user types, the model is supposed to generate a suggestion that matches the user typeahead, which will get rendered. The previous in flight trigger should not be abandoned. 
Block concurrent inline completion handler.
Eventually this needs integration test. To properly test this, we need to create a real …
> fix: Disable Concurrent inline completion handler

- chat-client/src/client/chat.ts
- we don't want the disclaimer message at the bottom, as we already have a popup warning when user tries Q for the first time
- removing disclaimer message at the bottom
> fix: remove disclaimer message from chat window

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/toolConstants.ts
code quality CR for moving string literals.
Moved the string literals out.
> refactor(amazonq): moved string literals to const file for code quality

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
as discussed in internal channels
> fix: treat `echo`/`find`/`grep` as mutating

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatController.ts
This change adds type omissions to ChatHandlers, so that a future runtimes dependency update (https://github.com/aws/language-server-runtimes/pull/620) will not cause this codebase to fail.
> fix: update ChatHandlers before adding new types dependency

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
> fix(amazonq): continueous edits trigger returns earlier as first session is already closed

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
When a keystroke is input, the classifier of Flare will output a different score, which result in different behavior in auto trigger.
By comparing the classifier score given the example same input, AFTER the fix of document event based trigger, we find that the only difference between the IDE auto trigger and Flare is the OS. 
The Flare auto trigger has a OS field that is not implemented correctly, it is marked as TODO. 
> fix: Make the classifier of auto trigger output the same score as the IDE auto trigger classifier

- chat-client/src/client/mcpMynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
File Watchers are triggering mcp server refresh during permission changes and random clicks. Permission page close results into mcp list re-opening and refresh
- Added debounce for file watchers and programmatic change tracking update to correctly track them.
- permission page close is also marked as mcp servers list page as not active.
> fix(amazonq): fix for mcp server unnecessary refresh from file watchers

- chat-client/src/client/mynahUi.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- This [PR](https://github.com/aws/language-servers/pull/1922) replaced `"Stop"` with `"Cancel"`
- We would like to not use `"Cancel"` and instead go back to `"Stop"`
- Use `"Stop"`
> fix: replace cancel with stop

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
The image context is not added to history, as a result, if customer ask follow-up questions, the model does not know the previous chat context
Add image context to history
https://github.com/user-attachments/assets/a0f3d3fa-6b45-49cb-b67f-51aaa19d4b5b
> fix(amazonq): add image context to chat history

- client/vscode/package.json
- server/aws-lsp-codewhisperer/README.md
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/inlineChatExtraContext.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/contexts/triggerContext.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/configurationUtils.ts
We need to pass extra context for the inline chat, adding a new workspace config for the same
- Added extra context as a new workspace config for inline chat
- This will be checked and passed in the relevant documents
> feat: adding extra context as a workspace config for inline chat

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyDiscoverer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyEventBundler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JSTSDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/JavaDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/LanguageDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyHandler/PythonDependencyHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
There are two issues with workspace context server receiving `didChangeDependencyPaths` events:
- **Lost initial events:** Before the workspace context server properly determines user eligibility (`isUserEligibleForWorkspaceContext()`) and completes initialization, all `didChangeDependencyPaths` events sent from the IDE extension are lost.
- **Lost historical events:** When `dependencyDiscoverer` is disposed (due to user opt-out, admin opt-out or user logout), all previously received `didChangeDependencyPaths` events are lost as dependency maps are reset. These events cannot be recovered if the workspace context server needs to run for the user again later.
Implement an in-memory recording system for all didChangeDependencyPaths events that:
- Stores events regardless of workspace context …
> fix(amazonq): avoid workspace context server missing historical dependency events

- integration-tests/q-agentic-chat-server/package.json
- integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
- integration-tests/q-agentic-chat-server/src/tests/lspClient.ts
- integration-tests/q-agentic-chat-server/src/tests/testUtils.ts
- package-lock.json
Basic tool execution is not tested
- Replace `ts-lsp-client` with a custom jsonrpc endpoint implementation that supports asynchronous out-of-order messages
- Log errors without needing to set `DEBUG=true` for easier debugging of test failures
- Add integration tests for built-in tools: `fsRead`, `listDirectory`, `executeBash`, `fsWrite`, `fsReplace`, and `fileSearch`
> test(amazonq): add integ tests for built-in tools

- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/validation.ts
This PR enables WebForms to Blazor transformation without officially adding 'AspNetWebForms' to the supportedProjects array. It implements a temporary solution by modifying the validation logic to specifically allow AspNetWebForms projects while maintaining backward compatibility with existing project types.
Changes:
- Modified validateProject function to accept AspNetWebForms projects
- Updated validateSolution function to exclude AspNetWebForms from unsupported projects list
- Added documentation explaining the temporary nature of this approach
> feat: enable webforms to blazor transformation via validation bypass

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
This PR addresses two issues related to `ListWorkspaceMetadata` API call volume:
1. `CONTINUOUS_MONITOR_INTERVAL` was mistakenly set to 5 minutes while the intention is to set to 30 minutes.
2. When a user has reached their maximum allowed remote workspaces quota, the system continues to make periodic `ListWorkspaceMetadata` calls, even though no new workspaces can be created. This is inefficient, especially when users have multiple IDE windows open.
1. Ensure the `CONTINUOUS_MONITOR_INTERVAL` is correctly set to 30 minutes.
2. When a `ServiceQuotaExceededException` is detected during a CreateWorkspace API call, set the `isServiceQuotaExceeded` flag and stop the continuous monitoring.
1. Added unit tests.
2. Tested the code change locally and verified continuous monitor is not started …
> fix(amazonq): stop continuous monitor when WCS sees ServiceQuotaExceeded

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- MCP permission change is triggering file watchers
- MCP delete is not remivng from mcp config file which is causing the server to re-appear after restart from config migration
- Incorrect log
- Corrected programmatic state
- removing server from mcp config file for delete
- corrected log to remove VSCode server.
> fix: fix for mcp delete to remove it from mcp config file

- package-lock.json
```
(base) ➜  language-servers git:(main) ✗ git fetch upstream 
(base) ➜  language-servers git:(main) ✗ git reset --hard upstream/main
HEAD is now at 8c2cab699 fix(amazonq): revert commit f17b631d9e06371a11ef8e9cb1413762fb51a143 (#1965)
(base) ➜  language-servers git:(main) npm i
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'undici@7.11.0',
npm warn EBADENGINE   required: { node: '>=20.18.1' },
npm warn EBADENGINE   current: { node: 'v20.15.0', npm: '10.8.1' }
npm warn EBADENGINE }
> @amzn/monorepo-language-servers@1.0.0 prepare
> husky .husky
changed 1 package, and audited 2123 packages in 3s
317 packages are looking for funding
run `npm fund` for details
4 vulnerabilities (2 low, 1 high, 1 critical)
To address all issues, run:
npm audit fix
Run `npm audit` for …
```
> fix: npm security vulnerabilities

- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.ts
The repomap index, aka the inline completion index should be enabled for all users and it should be used in supplemental context. But it was turned off for users who do not have workspace index enabled. The workspace index enable flag is only meant for vector index. 
Enable repomap as inline completion supplemental context for all users
> fix: enable repomap as inline completion supplemental context for all users

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/agenticChatTriggerContext.ts
The logs are printing the wrong path for the function.
Fixed the logs.
> fix(amazonq): wrong path in the logs for the function

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
Fix issues from security ticket
Malicious characters should be removed from command description
> fix: remove malicious characters from MCP tool description

- chat-client/src/client/tabs/tabFactory.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/executeBash.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/grepSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolShared.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/tests/validation.test.ts
- server/aws-lsp-codewhisperer/src/language-server/netTransform/validation.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
- Reverted commits for auto-approve feature emergency deployment revert.
- reapplying the commits that are reverted
> chore(amazonq): revert for emergency reverts for auto-approve feature

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- missing metric for tool error
- emit metric when there is a tool error
- exclude tool errors relating to user rejecting/canceling the shell command, as this is intended by the user
> fix: emit metric for tool error

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/telemetry.ts
`codewhispererServer.ts` as the activation code of Q inline, it servers as the entry point of all components' initialization however currently there are also lots of business logic implemented in the same place, which makes it harder to read this file and work on.
> refactor: move telemetry functions outside codewhispererServer.ts

- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.test.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
This change resolves merge conflicts between main and feature/subscription
> Resolve conflicts between feature/subscription and main

- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
This PR adds comprehensive logging to the Amazon Q Developer Profiles fetching process to help diagnose the "failed to fetch: developerProfiles" error that customers are experiencing with ATX transformation. The enhanced logging captures detailed information about endpoints accessed, regions queried, profiles returned, and provides structured error details without modifying any existing functionality.
Key improvements:
- Log all endpoints and regions being queried
- Capture raw API responses and request parameters
- Track profile retrieval success/failure by region
- Provide detailed error information including HTTP status codes and AWS metadata
- Summarize total profiles fetched across all regions
These changes will help identify the root cause of login issues by providing visibility …
> feat: enhance profile fetching logs to diagnose developerProfiles errors

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
In certain cases, when a user hit Enter in certain languages, the documentChangeEvent has a empty string. This is a valid auto trigger. In fact user only input Enter but the IDE decides to add some other documentChangeEvents
Enable auto trigger for this case.
> fix: sometimes Enter does not auto trigger in Java when Java extension is installed

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
Previously auto trigger and manual trigger are not separated in if-else branches. They are entangled.
Perform auto trigger logic under the `if (isAutomaticLspTriggerKind) {` branch
> refactor: separate auto trigger and manual trigger code path

- chat-client/src/client/mynahUi.ts
Invalid Image notification shown even all dropped images are valid.
Add conditional check to only show the notification when there are more than one errors
> fix(amazonq): fix the issue that invalid image notification always show

- server/aws-lsp-codewhisperer/src/shared/models/constants.ts
1. Config is incorrect.
2. Found another problem. The workspace.getAllTextDocuments() API only returns the open tabs that were clicked during this IDE session. If you open, close, reopen IDE, this API returns empty unless user re-click those files again.
1. Correct the config
2. Fix the bug later.
> fix: adjust cross file context config

- server/aws-lsp-identity/src/iam/iamProvider.test.ts
- server/aws-lsp-identity/src/iam/iamProvider.ts
- server/aws-lsp-identity/src/iam/utils.ts
- server/aws-lsp-identity/src/language-server/identityService.test.ts
- server/aws-lsp-identity/src/language-server/identityService.ts
The identity LSP can only discover IAM credentials from the shared config files, temporary credentials cache, and STS AssumeRole calls. To reach feature parity with the Toolkit extensions and for potential auth migrations in the future, the identity LSP should also discover credentials from credentials processes, EC2 metadata, ECS metadata, and environment variables.
This is part of https://github.com/aws/language-servers/pull/1981.
- Add credentials discovery from EC2 metadata, ECS metadata, and environment variables to authenticate with STS AssumeRole
- Add credentials retrieval from credentials process
> feat: add IAM credentials discovery from process, metadata, and env

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
MCP server permissions save has seen regression due to recent changes.
fixed the permission save for mcp server tools and its telemetry
> fix(amazonq): fix for mcp server permissions

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
Customers can inject malicious prompts through Unicode tag characters (U+E0000-U+E007F) in prompt files and file content read by the `fsRead` tool. These invisible characters can encode hidden instructions that bypass security controls, allowing prompt injection attacks where malicious content appears as legitimate text to users but contains embedded commands for the AI system.
- Applied sanitization to the entire request before sending to the front-end
- Added unit tests
- Tested on a prompt file with hidden content (https://embracethered.com/blog/ascii-smuggler.html) and the contents were not able to be picked up:
https://github.com/user-attachments/assets/e975f221-d291-46fa-b4b8-ec596496aa03
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> fix: sanitize request input

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReview.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReview.ts
- Extend timeout from 10 to 15 minutes (MAX_POLLING_ATTEMPTS: 60 → 90)
- Add latency tracking for performance monitoring
- Improve error messages for better user experience
- Standardize error handling to throw exceptions consistently so that agent will retry the tool accordingly
- Update tests to properly handle exception-based error flow
> fix(amazonq): improve code review tool reliability and error handling

- integration-tests/q-agentic-chat-server/package.json
- integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
- integration-tests/q-agentic-chat-server/src/tests/testUtils.ts
- package-lock.json
Integration tests fail on a Windows environment, for example: https://github.com/aws/language-servers/actions/runs/16686697168/job/47237441990
Update test cases for Windows
> test: fix integration tests on windows

- README.md
Integration test results are hidden under the actions tab.
Add integration test workflow badge to readme
> chore: add integ test badge

- server/aws-lsp-identity/src/iam/utils.ts
- server/aws-lsp-identity/src/language-server/identityServer.ts
- server/aws-lsp-identity/src/language-server/profiles/profileWatcher.test.ts
- server/aws-lsp-identity/src/language-server/profiles/profileWatcher.ts
To reach feature parity with the Toolkits and allow them to automatically refresh their profile UI, Flare should send notifications to the language client when the shared config files change.
This is part of https://github.com/aws/language-servers/pull/1981.
This PR allows the identity LSP to send notifications containing profile data whenever the shared config files change.
> feat: add shared config file watcher

- chat-client/src/client/mynahUi.ts
Currently, the Mynah-UI elements do not show `data-testid` at the production level of Amazon Q. This makes UI Tests very flakey because we have to rely on CSS Selectors to grab Mynah-UI elements, and these CSS Selectors can be shared across multiple different elements.
In `mynahUI.ts` we set `test:true` so `data-testid` will show at production level. Now instead of using CSS Selectors, test writers can grab the `data-testid`
```
const mynahUiProps: MynahUIProps = {
...
config: {
maxTabs: 10,
test: true,
...
```
_This is the code in Mynah-UI that turns on test-ids when test config is set to `true`_
https://github.com/aws/mynah-ui/blob/main/src/helper/dom.ts#L264
> fix: Enable Test Flag For AmazonQ UI Testing

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-buildspec-runtimes/package.json
- app/aws-lsp-cloudformation-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-s3-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- app/hello-world-lsp-runtimes/package.json
- chat-client/package.json
- client/vscode/package.json
- core/aws-lsp-core/package.json
- integration-tests/q-agentic-chat-server/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-buildspec/package.json
- server/aws-lsp-cloudformation/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-s3/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
New runtimes version is available
Bump runtimes to 0.2.121
> chore: bump runtimes

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
Read/List/Search messages are combined in the same component as the conversation continues, making it easy to miss tool executions as new messages are added.
New UI for Read/List/Search messages:
- Files are shown as pills instead of a file tree
- Updating existing message only happens if the previous message and current message are the same tool type, preventing updating messages that are earlier in the conversation.
> feat(amazonq): read tool message revamp

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/util.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- History is not updated when trimming happens, causing follow up request to throw ValidationException
- Bug in calculating context window when history trimming happened
- Missing metric for compaction 
- Update history when trimming happens
- Fix a bug in calculating character count causing compaction nudge to show when history is trimmed
- Add missing metric for compaction
> fix: outdated history when trimming happens, add missing metric for compaction

- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- If user opens a new tab, both agentic coding toggle and model selection drop down flickers.
https://github.com/user-attachments/assets/5ca2f0ca-eba7-4fcb-aa06-dd6496b7f855
- Fixed above issue.
- This issue will be completely fixed once user changes any `promptInputOptions`
https://github.com/user-attachments/assets/94337177-5c58-4331-b95f-b52b14b6b64f
> fix(amazonq): fix flickering issue for model selection dropdown and agenticCoding toggle

- chat-client/src/client/texts/modelSelection.test.ts
- chat-client/src/client/texts/modelSelection.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/agenticChatControllerHelper.ts
Sonnet 4 is available for eu-central-1
Enable Sonnet 4 for eu-central-1 region profile
> feat(amazonq): enable sonnet 4 for fra region

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
The invokeLLM event doesn't emit failed status correctly.
Emit failure status for time out and check result status before emit succeeded event.
> fix(amazonq): emit failed status for amazonq_invokeLLM

- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/artifactManager.ts
Adding the original .classpath and .project file generation as a fallback from
https://github.com/aws/language-servers/pull/1955/files
> fix(amazonq): add fallback classpath generation

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/editCompletionHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/telemetry.ts
Sometimes the session is closed before the UTDE telemetry is emitted
Creating a new session for Edits trigger with next token for easier state maintenance
> fix: creating a new sesion for Edits trigger with next token

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
- package-lock.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/editCompletionHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/telemetry.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/IdleWorkspaceManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/IdleWorkspaceManager.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/dependency/dependencyDiscoverer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
Sync test smus branch with main branch commits
> Chore: Sync test smus branch with main branch commits

- client/vscode/src/credentialsActivation.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.test.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
Inline suggestion currently is not supported for IAM Auth client and throws error message in logs
```Amazon Q service is not signed in```
- Changes are to add baseRequest type that can support both IAM based GenerateRecommendations Request along with Token based GenerateSuggestionsRequest and handle the request creation and response parsing properly
- Tested in local using the test configuration ``` "configurations": ["CodeWhisperer Server IAM", "Attach to AWS Documents Language Server"]```
- 
> feat(amazonq): add inline suggestion support for iam auth client

- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
To invoke Maestro backend which is based on request origin checks, need to support client Info check from SMUS Q CodeEditor client
- Updated origin in LSP client to support SMUS CE Q client case
- Added unit tests
- ```npm run format && npm run test``` succeeded in local
- Related [PR](https://github.com/aws/language-servers/pull/2032)
> fix: update client name to support Sagemaker AI origin for agentic chat

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- If user selected a default model and then switched the profile which does not have the model available from the backend. Existing plugin shows empty dropdown.
- Check if backend models are empty before assigning the default selected hardcoded value.
- If user is in IAD profile and selected claude-3.7-sonnet as preference and if user switched to FRA, and if FRA does not have claude-3.7-sonnet then IDE shows null right now. After this change, IDE fall back to backend default model.
> fix: check available models from backend before selecting default model from fallback models

- chat-client/src/client/mynahUi.ts
- integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
Previously reverted this change https://github.com/aws/language-servers/pull/2104 due to a UI bug where contextList files were getting added to executeBash header.
Revert the revert, and fixed the bug: https://github.com/aws/language-servers/commit/7ceb635bd21686c6664597ef1889114bdfab762e
> feat(amazonq): read tool ui revamp

- .github/workflows/create-release-candidate-branch.yml
- .release-please-manifest.json
- app/aws-lsp-codewhisperer-runtimes/src/version.json
- chat-client/CHANGELOG.md
- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- integration-tests/q-agentic-chat-server/src/tests/agenticChatInteg.test.ts
- package-lock.json
- server/aws-lsp-codewhisperer/CHANGELOG.md
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatResultStream.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fileSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codePercentage.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/diffUtils.ts
- server/aws-lsp-codewhisperer/src/shared/utils.test.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
Sync feature smus inline suggestions branch from main commits
> Sync feature smus inline suggestions branch from main commits

- chat-client/src/client/texts/modelSelection.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts
API now returns proper display names for models.
Update the labels and update mapping logic by separating the old bedrock modelId mapping to a separate constant.
> feat(amazonq): use model display names

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/additionalContextProvider.ts
The `@prompt` feature  was not working on Windows systems due to incorrect path separator handling, while the same functionality worked correctly on Mac
How it failed on Windows:
- Uses `Array.join('/')` which always uses forward slashes
- `['C:\\Users\\chungjac\\.aws\\amazonq\\prompts', 'hello.md'].join('/') `
- Results in: `C:\Users\chungjac\.aws\amazonq\prompts/hello.md` (mixed separators)
Why it worked on Mac:
- Unix systems use forward slashes natively
- `['/Users/chungjac/.aws/amazonq/prompts', 'hello.md'].join('/')`
- Results in: `/Users/chungjac/.aws/amazonq/prompts/hello.md` (consistent forward slashes)
Replace `Array.join('/')` with Node.js `path.join()` for proper cross-platform path handling
`useRelevantDocuments` is now set to `true`, as it was previously `false`
``` …
```
> fix: proper path handling for additional context

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/profileStatusMonitor.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/profileStatusMonitor.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/toolServer.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
mcp admin state needs disk caching
Auth change needs to also do the mcp state check
- Added disk caching for mcp admin state
- Added mcp state check for auth change with event
> fix: fix to add disk caching for mcp admin state

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.ts
- server/aws-lsp-codewhisperer/src/shared/localProjectContextController.ts
Currently we don't support remote MCP server that require OAuth with dynamic client registration.
Add basic OAuth client to support dynamic client registration with PKCE, more details can be found, https://quip-amazon.com/DnsKAhaSjC4B/OAuth-enabled-MCP-HTTPSSE-support
This PR also include a couple of fixes for the regression of http support.
Disable DCR when plugin loads
UX changes during browser authenticaiton
Some UX edge case handling.
> feat: add basic OAuth client for remote MCP

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/errors.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.ts
If MCP server failed to init with auth issue, PKCE flow shouldn't be launched in browser.
Disable pkce flow during plugin load
> feat: disable pkce flow during plugin load

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.ts
Some Issues edge cases in PKCE auth flow
* Added timeout for PKCE flow.
* Fixed issue when Auth Failed, UI stuck in "activating" page, now error will be catched and displayed on add/edit view
* Fixed issue when Auth failed, UI always jump back to list server view
* Fixed Windows path
> fix: multiple fixes on auth flow edge cases

- chat-client/package.json
- chat-client/src/client/mynahUi.ts
- package-lock.json
When larger responses are being streamed, the typewriter animation logic can cause significant delays in text rendering (perceived latency) and also causes the UI to lag.
Disable typewriter animation. Chunks are added immediately to the UI as soon as they are streamed in, and all remaining content is flushed as soon as the stream completes.
> fix(amazonq): disable typewriter animation

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpOauthClient.ts
url path is not correct on Windows
Fix it along with some other issues from bug bash
> fix: fix pkce windows url path

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
When an MCP tools is accpeted, it shows completed as status.
- Updated it to `Accepted`
> fix(amazonq): status message update for mcp tool permission acceptance

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
We need to emit the number of accepted lines of code generated by the agentic chat
A new interaction type for `AGENTIC_CODE_ACCEPTED` was added to our backend. Add `AGENTIC_CODE_ACCEPTED` telemetry event to track when users accept code changes from agentic write tools. Emit telemetry with net line count difference (after - before) when `FS_WRITE`/`FS_REPLACE` tools are executed.
Tested in RTS alpha:
IDE local log:
```
[Info  - 12:16:39 PM] [2025-08-27T19:16:39.232Z] lserver: Invoking SendTelemetryEvent:ChatInteractWithMessageEvent with:
"interactionType": AGENTIC_CODE_ACCEPTED
"acceptedLineCount": 4
```
Local RTS Server Logs:
```
[java] 2025-08-27T22:09:05,293 [DEBUG] 5e271ff1-4c2a-4436-bf59-c65bbbca012e (coral-orchestrator-13) com.amazon.aws.vector.consolas.runtimeservice.component.SendTe …
```
> fix: emit acceptedLineCount metric and AgenticCodeAccepted interaction type

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
for the classifier score, we are supposed to send the score after taking sigmoid but current the raw score is sent.
> fix: should send classifier score after taking sigmoid

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- The first accepted compaction nudge is being updated by newer nudge action
- Fixed the bug
> fix: compact UI is not updated correctly when multiple nudges are displayed

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
CW dashboard requires errorMessage to be in addMessage
emit errorMessage in addMessage
> fix: emit errorMessage in addMessage

- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/fileModificationMetrics.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/utils/fileModificationMetrics.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/telemetry/chatTelemetryController.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/auto-trigger/autoTrigger.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/codeWhispererServer.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/editCompletionHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/session/sessionManager.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/userTriggerDecision.test.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/crossFileContextUtil.ts
- server/aws-lsp-codewhisperer/src/shared/supplementalContextUtil/supplementalContextUtil.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.test.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/telemetryService.ts
- server/aws-lsp-codewhisperer/src/shared/telemetry/types.ts
- server/aws-lsp-codewhisperer/src/shared/telemetryUtils.ts
> Merge from main to terminal-integration branch

- server/aws-lsp-codewhisperer/src/client/token/bearer-token-service.json
- server/aws-lsp-codewhisperer/src/client/token/codewhispererbearertokenclient.d.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReview.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReview.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReviewSchemas.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/qCodeAnalysis/codeReviewTypes.ts
Currently for code review tool , the selected model data is not sent to the RTS requests.
Hence adding additional attributes to send the selected model Id and origin related data
Tested in alpha (used RTS alpha to initiate a new scan)
modelId and origin is saved in scanMetadata table 
> Model selection for code review tool

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/workspaceContext/semanticSearch.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/workspaceContext/semanticSearch.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/util.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceContextServer.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.test.ts
- server/aws-lsp-codewhisperer/src/language-server/workspaceContext/workspaceFolderManager.ts
> Semantic search tool integration

- package-lock.json
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.test.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/qDeveloperProfiles.ts
- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
- server/aws-lsp-codewhisperer/src/shared/testUtils.ts
- server/aws-lsp-codewhisperer/src/shared/utils.ts
External IdP request behavior is not quite `builderId` and not quite like `identityCenter`
Add new type to runtimes and handle in language-serers
Related: https://github.com/aws/language-server-runtimes/pull/679
> feat: support sending requests with the 'external_idp' type

- app/aws-lsp-antlr4-runtimes/package.json
- app/aws-lsp-buildspec-runtimes/package.json
- app/aws-lsp-cloudformation-runtimes/package.json
- app/aws-lsp-codewhisperer-runtimes/package.json
- app/aws-lsp-identity-runtimes/package.json
- app/aws-lsp-json-runtimes/package.json
- app/aws-lsp-notification-runtimes/package.json
- app/aws-lsp-s3-runtimes/package.json
- app/aws-lsp-yaml-json-webworker/package.json
- app/aws-lsp-yaml-runtimes/package.json
- chat-client/package.json
- client/vscode/package.json
- core/aws-lsp-core/package.json
- integration-tests/q-agentic-chat-server/package.json
- package-lock.json
- server/aws-lsp-antlr4/package.json
- server/aws-lsp-buildspec/package.json
- server/aws-lsp-cloudformation/package.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-identity/package.json
- server/aws-lsp-json/package.json
- server/aws-lsp-notification/package.json
- server/aws-lsp-partiql/package.json
- server/aws-lsp-s3/package.json
- server/aws-lsp-yaml/package.json
- server/device-sso-auth-lsp/package.json
- server/hello-world-lsp/package.json
New runtimes version is available: https://github.com/aws/language-server-runtimes/pull/680
Bump runtimes to 0.2.129
> chore: bump runtimes to 0.2.129

- .github/workflows/create-agent-standalone.yml
The `create-agent-standalone.yml` workflow requires empty commits to trigger builds on release branches because the job condition `github.actor_id == github.repository_owner_id` fails for collaborators with write access (only works for admin users).
Remove the redundant if condition and rely on GitHub's built-in permissions. GitHub automatically restricts workflow triggers to users with appropriate repository permissions. This eliminates the need for workaround empty commits while maintaining security through GitHub's native access controls.
> ci: remove condition preventing manual trigger of build actions

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpEventHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpManager.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
Filewatchers needs to be attached to mcp config as well
- Added filewatchers as well
> fix(amazonq): fix to add filewatcher for mcp config files

- server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts
suggestionType is inferred by the statements
https://github.com/aws/language-servers/blob/main/server/aws-lsp-codewhisperer/src/shared/codeWhispererService.ts#L544-L572
specifically
```
if (apiResponse?.predictions && apiResponse.predictions.length > 0) {
const suggestionType = apiResponse.predictions[0].edit ? SuggestionType.EDIT : SuggestionType.COMPLETION
const predictionType = suggestionType === SuggestionType.COMPLETION ? 'completion' : 'edit'
return {
suggestions: apiResponse.predictions.map(prediction => ({
content: prediction[predictionType]?.content ?? '',
references: prediction[predictionType]?.references ?? [],
itemId: this.generateItemId(),
})),
suggestionType,
responseContext,
}
}
```
so if it's an Edit request and service returns empty suggestion then it will be determined …
> fix: inline UTD telemetry empty cases dont differentiate Edit and Completion

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/mcp/mcpUtils.ts
MCP servers are failing in windows at workspace level due to incorrect path recognition.
- Fix to correct the path for workspace.
> fix(amazonq): fix to normlize workspace paths in windows

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/chatDb/chatDb.ts
> fix: improve history management

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
There are instances of newlines in the errorMessage value. 
The errorMessage value (dimension value) is used as the label name in Cloudwatch. However Cloudwatch does not support dimension values having newlines: `ASCII control characters are not supported as part of dimension values.`
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html
Therefore, the data where errorMessage value was not being logged to Cloudwatch.
Remove new lines when emitting error message
> fix: trim new line when emitting error message

- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQIAMServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/AmazonQTokenServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/amazonQServiceManager/BaseAmazonQServiceManager.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.test.ts
- server/aws-lsp-codewhisperer/src/shared/streamingClientService.ts
We need to revert the opt-out commit from main for release.
This PR reverts PR #2365 
> revert(amazonq): fix to add opt-out header to streaming client

- chat-client/src/client/features/rules.test.ts
- chat-client/src/client/features/rules.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/constants.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/context/memorybank/memoryBankController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tools/fsRead.ts
- server/aws-lsp-codewhisperer/src/language-server/chat/chatSessionService.ts
Amazon Q IDE is encountering issues where conversation history is unexpectedly cleared due to exceeding token limits. This leads to a poor user experience and loss of context in ongoing conversations. We need to implement strategies to prevent hitting these limits and handle cases where we do exceed them more gracefully.
- Reduced memory bank file processing from 10 to 5 files with custom fsRead limits (20K per file, 100K total vs standard 200K/400K)
- Memory bank generation now automatically opens in a dedicated new tab, keeping original conversations clean (Note/
- We need to open new tabs when memory bank is triggered by the prompt rather than the explicit button. It still runs in the current chat window for this case)
- We don't currently de-dupe the Memory Bank tabs (similar to …
> fix: optimize memory bank token usage and add new tab support

- chat-client/package.json
- chat-client/src/client/mynahUi.test.ts
- chat-client/src/client/mynahUi.ts
- chat-client/src/client/texts/modelSelection.ts
- client/vscode/package.json
- package-lock.json
- server/aws-lsp-codewhisperer/package.json
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/agenticChatController.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/constants/modelSelection.ts
The backend now provides a model description, which we would also like to display as a tooltip when hovering over the model name
Add model description as a tooltip when hovering over model:
- Updated runtimes which adds description field to model: https://github.com/aws/language-server-runtimes/pull/689
- Updated mynahui which adds tooltip when hovering capability: https://github.com/aws/mynah-ui/pull/438
- Display tooltip when hovering over model
- Remove Sonnet 3.7 as a fallback model
https://github.com/user-attachments/assets/dc37b0c0-2b9b-43a0-9693-253a47ebbd49
> feat: add model description to dropdown

- server/aws-lsp-codewhisperer/src/language-server/inline-completion/handler/editCompletionHandler.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/diffUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/diffUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/mergeRightUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/mergeRightUtils.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/triggerUtils.test.ts
- server/aws-lsp-codewhisperer/src/language-server/inline-completion/utils/triggerUtils.ts
add tests for inline utils files
add tests for inline utils files and remove unused files
Coverage should go to 85% after this change: https://app.codecov.io/gh/aws/language-servers/commit/b91f1a0de8b711cd1ce24a7389b64daf15e06f72/tree/server/aws-lsp-codewhisperer/src/language-server?dropdown=coverage
> chore(amazonq): add more tests for inline completion codes

- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.test.ts
- server/aws-lsp-codewhisperer/src/language-server/agenticChat/tabBarController.ts
**Description**
Team has decided to use `SAGEMAKER_APP_TYPE_LOWERCASE` env var to support conversation history on refresh for JupterLab. 
**Testing Done**
- npm test
- Build server bundle and tested in a SMUS space
> feat(amazonq): env var change for JupyterLab conversation history on refresh support
